// Code generated by protoc-gen-go. DO NOT EDIT.
// source: election_contract.proto

package Election

import (
	aelf "aelf"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitialElectionContractInput struct {
	MinimumLockTime      int64    `protobuf:"zigzag64,1,opt,name=minimum_lock_time,json=minimumLockTime,proto3" json:"minimum_lock_time,omitempty"`
	MaximumLockTime      int64    `protobuf:"zigzag64,2,opt,name=maximum_lock_time,json=maximumLockTime,proto3" json:"maximum_lock_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialElectionContractInput) Reset()         { *m = InitialElectionContractInput{} }
func (m *InitialElectionContractInput) String() string { return proto.CompactTextString(m) }
func (*InitialElectionContractInput) ProtoMessage()    {}
func (*InitialElectionContractInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{0}
}

func (m *InitialElectionContractInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialElectionContractInput.Unmarshal(m, b)
}
func (m *InitialElectionContractInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialElectionContractInput.Marshal(b, m, deterministic)
}
func (m *InitialElectionContractInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialElectionContractInput.Merge(m, src)
}
func (m *InitialElectionContractInput) XXX_Size() int {
	return xxx_messageInfo_InitialElectionContractInput.Size(m)
}
func (m *InitialElectionContractInput) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialElectionContractInput.DiscardUnknown(m)
}

var xxx_messageInfo_InitialElectionContractInput proto.InternalMessageInfo

func (m *InitialElectionContractInput) GetMinimumLockTime() int64 {
	if m != nil {
		return m.MinimumLockTime
	}
	return 0
}

func (m *InitialElectionContractInput) GetMaximumLockTime() int64 {
	if m != nil {
		return m.MaximumLockTime
	}
	return 0
}

type ConfigElectionContractInput struct {
	MinerList            []string `protobuf:"bytes,1,rep,name=miner_list,json=minerList,proto3" json:"miner_list,omitempty"`
	TimeEachTerm         int64    `protobuf:"zigzag64,2,opt,name=time_each_term,json=timeEachTerm,proto3" json:"time_each_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigElectionContractInput) Reset()         { *m = ConfigElectionContractInput{} }
func (m *ConfigElectionContractInput) String() string { return proto.CompactTextString(m) }
func (*ConfigElectionContractInput) ProtoMessage()    {}
func (*ConfigElectionContractInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{1}
}

func (m *ConfigElectionContractInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigElectionContractInput.Unmarshal(m, b)
}
func (m *ConfigElectionContractInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigElectionContractInput.Marshal(b, m, deterministic)
}
func (m *ConfigElectionContractInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigElectionContractInput.Merge(m, src)
}
func (m *ConfigElectionContractInput) XXX_Size() int {
	return xxx_messageInfo_ConfigElectionContractInput.Size(m)
}
func (m *ConfigElectionContractInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigElectionContractInput.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigElectionContractInput proto.InternalMessageInfo

func (m *ConfigElectionContractInput) GetMinerList() []string {
	if m != nil {
		return m.MinerList
	}
	return nil
}

func (m *ConfigElectionContractInput) GetTimeEachTerm() int64 {
	if m != nil {
		return m.TimeEachTerm
	}
	return 0
}

type GetTermSnapshotInput struct {
	TermNumber           int64    `protobuf:"zigzag64,1,opt,name=term_number,json=termNumber,proto3" json:"term_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTermSnapshotInput) Reset()         { *m = GetTermSnapshotInput{} }
func (m *GetTermSnapshotInput) String() string { return proto.CompactTextString(m) }
func (*GetTermSnapshotInput) ProtoMessage()    {}
func (*GetTermSnapshotInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{2}
}

func (m *GetTermSnapshotInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTermSnapshotInput.Unmarshal(m, b)
}
func (m *GetTermSnapshotInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTermSnapshotInput.Marshal(b, m, deterministic)
}
func (m *GetTermSnapshotInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTermSnapshotInput.Merge(m, src)
}
func (m *GetTermSnapshotInput) XXX_Size() int {
	return xxx_messageInfo_GetTermSnapshotInput.Size(m)
}
func (m *GetTermSnapshotInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTermSnapshotInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTermSnapshotInput proto.InternalMessageInfo

func (m *GetTermSnapshotInput) GetTermNumber() int64 {
	if m != nil {
		return m.TermNumber
	}
	return 0
}

type UpdateCandidateInformationInput struct {
	PublicKey               string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RecentlyProducedBlocks  int64    `protobuf:"zigzag64,2,opt,name=recently_produced_blocks,json=recentlyProducedBlocks,proto3" json:"recently_produced_blocks,omitempty"`
	RecentlyMissedTimeSlots int64    `protobuf:"zigzag64,3,opt,name=recently_missed_time_slots,json=recentlyMissedTimeSlots,proto3" json:"recently_missed_time_slots,omitempty"`
	IsEvilNode              bool     `protobuf:"varint,4,opt,name=is_evil_node,json=isEvilNode,proto3" json:"is_evil_node,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *UpdateCandidateInformationInput) Reset()         { *m = UpdateCandidateInformationInput{} }
func (m *UpdateCandidateInformationInput) String() string { return proto.CompactTextString(m) }
func (*UpdateCandidateInformationInput) ProtoMessage()    {}
func (*UpdateCandidateInformationInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{3}
}

func (m *UpdateCandidateInformationInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCandidateInformationInput.Unmarshal(m, b)
}
func (m *UpdateCandidateInformationInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCandidateInformationInput.Marshal(b, m, deterministic)
}
func (m *UpdateCandidateInformationInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCandidateInformationInput.Merge(m, src)
}
func (m *UpdateCandidateInformationInput) XXX_Size() int {
	return xxx_messageInfo_UpdateCandidateInformationInput.Size(m)
}
func (m *UpdateCandidateInformationInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCandidateInformationInput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCandidateInformationInput proto.InternalMessageInfo

func (m *UpdateCandidateInformationInput) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UpdateCandidateInformationInput) GetRecentlyProducedBlocks() int64 {
	if m != nil {
		return m.RecentlyProducedBlocks
	}
	return 0
}

func (m *UpdateCandidateInformationInput) GetRecentlyMissedTimeSlots() int64 {
	if m != nil {
		return m.RecentlyMissedTimeSlots
	}
	return 0
}

func (m *UpdateCandidateInformationInput) GetIsEvilNode() bool {
	if m != nil {
		return m.IsEvilNode
	}
	return false
}

type ReleaseTreasuryProfitsInput struct {
	TermNumber           int64    `protobuf:"zigzag64,1,opt,name=term_number,json=termNumber,proto3" json:"term_number,omitempty"`
	MinedBlocks          int64    `protobuf:"zigzag64,2,opt,name=mined_blocks,json=minedBlocks,proto3" json:"mined_blocks,omitempty"`
	RoundNumber          int64    `protobuf:"zigzag64,3,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseTreasuryProfitsInput) Reset()         { *m = ReleaseTreasuryProfitsInput{} }
func (m *ReleaseTreasuryProfitsInput) String() string { return proto.CompactTextString(m) }
func (*ReleaseTreasuryProfitsInput) ProtoMessage()    {}
func (*ReleaseTreasuryProfitsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{4}
}

func (m *ReleaseTreasuryProfitsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseTreasuryProfitsInput.Unmarshal(m, b)
}
func (m *ReleaseTreasuryProfitsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseTreasuryProfitsInput.Marshal(b, m, deterministic)
}
func (m *ReleaseTreasuryProfitsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseTreasuryProfitsInput.Merge(m, src)
}
func (m *ReleaseTreasuryProfitsInput) XXX_Size() int {
	return xxx_messageInfo_ReleaseTreasuryProfitsInput.Size(m)
}
func (m *ReleaseTreasuryProfitsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseTreasuryProfitsInput.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseTreasuryProfitsInput proto.InternalMessageInfo

func (m *ReleaseTreasuryProfitsInput) GetTermNumber() int64 {
	if m != nil {
		return m.TermNumber
	}
	return 0
}

func (m *ReleaseTreasuryProfitsInput) GetMinedBlocks() int64 {
	if m != nil {
		return m.MinedBlocks
	}
	return 0
}

func (m *ReleaseTreasuryProfitsInput) GetRoundNumber() int64 {
	if m != nil {
		return m.RoundNumber
	}
	return 0
}

type VoteMinerInput struct {
	CandidatePublicKey   string               `protobuf:"bytes,1,opt,name=candidate_publicKey,json=candidatePublicKey,proto3" json:"candidate_publicKey,omitempty"`
	Amount               int64                `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	EndTimestamp         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VoteMinerInput) Reset()         { *m = VoteMinerInput{} }
func (m *VoteMinerInput) String() string { return proto.CompactTextString(m) }
func (*VoteMinerInput) ProtoMessage()    {}
func (*VoteMinerInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{5}
}

func (m *VoteMinerInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteMinerInput.Unmarshal(m, b)
}
func (m *VoteMinerInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteMinerInput.Marshal(b, m, deterministic)
}
func (m *VoteMinerInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteMinerInput.Merge(m, src)
}
func (m *VoteMinerInput) XXX_Size() int {
	return xxx_messageInfo_VoteMinerInput.Size(m)
}
func (m *VoteMinerInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteMinerInput.DiscardUnknown(m)
}

var xxx_messageInfo_VoteMinerInput proto.InternalMessageInfo

func (m *VoteMinerInput) GetCandidatePublicKey() string {
	if m != nil {
		return m.CandidatePublicKey
	}
	return ""
}

func (m *VoteMinerInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *VoteMinerInput) GetEndTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.EndTimestamp
	}
	return nil
}

type UpdateTermNumberInput struct {
	TermNumber           int64    `protobuf:"zigzag64,1,opt,name=term_number,json=termNumber,proto3" json:"term_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTermNumberInput) Reset()         { *m = UpdateTermNumberInput{} }
func (m *UpdateTermNumberInput) String() string { return proto.CompactTextString(m) }
func (*UpdateTermNumberInput) ProtoMessage()    {}
func (*UpdateTermNumberInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{6}
}

func (m *UpdateTermNumberInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTermNumberInput.Unmarshal(m, b)
}
func (m *UpdateTermNumberInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTermNumberInput.Marshal(b, m, deterministic)
}
func (m *UpdateTermNumberInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTermNumberInput.Merge(m, src)
}
func (m *UpdateTermNumberInput) XXX_Size() int {
	return xxx_messageInfo_UpdateTermNumberInput.Size(m)
}
func (m *UpdateTermNumberInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTermNumberInput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTermNumberInput proto.InternalMessageInfo

func (m *UpdateTermNumberInput) GetTermNumber() int64 {
	if m != nil {
		return m.TermNumber
	}
	return 0
}

type GetElectionResultInput struct {
	TermNumber           int64    `protobuf:"zigzag64,1,opt,name=term_number,json=termNumber,proto3" json:"term_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetElectionResultInput) Reset()         { *m = GetElectionResultInput{} }
func (m *GetElectionResultInput) String() string { return proto.CompactTextString(m) }
func (*GetElectionResultInput) ProtoMessage()    {}
func (*GetElectionResultInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{7}
}

func (m *GetElectionResultInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetElectionResultInput.Unmarshal(m, b)
}
func (m *GetElectionResultInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetElectionResultInput.Marshal(b, m, deterministic)
}
func (m *GetElectionResultInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetElectionResultInput.Merge(m, src)
}
func (m *GetElectionResultInput) XXX_Size() int {
	return xxx_messageInfo_GetElectionResultInput.Size(m)
}
func (m *GetElectionResultInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetElectionResultInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetElectionResultInput proto.InternalMessageInfo

func (m *GetElectionResultInput) GetTermNumber() int64 {
	if m != nil {
		return m.TermNumber
	}
	return 0
}

type ElectionResult struct {
	TermNumber           int64            `protobuf:"zigzag64,1,opt,name=term_number,json=termNumber,proto3" json:"term_number,omitempty"`
	Results              map[string]int64 `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag64,2,opt,name=value,proto3"`
	IsActive             bool             `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ElectionResult) Reset()         { *m = ElectionResult{} }
func (m *ElectionResult) String() string { return proto.CompactTextString(m) }
func (*ElectionResult) ProtoMessage()    {}
func (*ElectionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{8}
}

func (m *ElectionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectionResult.Unmarshal(m, b)
}
func (m *ElectionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectionResult.Marshal(b, m, deterministic)
}
func (m *ElectionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectionResult.Merge(m, src)
}
func (m *ElectionResult) XXX_Size() int {
	return xxx_messageInfo_ElectionResult.Size(m)
}
func (m *ElectionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectionResult.DiscardUnknown(m)
}

var xxx_messageInfo_ElectionResult proto.InternalMessageInfo

func (m *ElectionResult) GetTermNumber() int64 {
	if m != nil {
		return m.TermNumber
	}
	return 0
}

func (m *ElectionResult) GetResults() map[string]int64 {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ElectionResult) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type ElectorVote struct {
	ActiveVotingRecordIds    []*aelf.Hash            `protobuf:"bytes,1,rep,name=active_voting_record_ids,json=activeVotingRecordIds,proto3" json:"active_voting_record_ids,omitempty"`
	WithdrawnVotingRecordIds []*aelf.Hash            `protobuf:"bytes,2,rep,name=withdrawn_voting_record_ids,json=withdrawnVotingRecordIds,proto3" json:"withdrawn_voting_record_ids,omitempty"`
	ActiveVotedVotesAmount   int64                   `protobuf:"zigzag64,3,opt,name=active_voted_votes_amount,json=activeVotedVotesAmount,proto3" json:"active_voted_votes_amount,omitempty"`
	AllVotedVotesAmount      int64                   `protobuf:"zigzag64,4,opt,name=all_voted_votes_amount,json=allVotedVotesAmount,proto3" json:"all_voted_votes_amount,omitempty"`
	ActiveVotingRecords      []*ElectionVotingRecord `protobuf:"bytes,5,rep,name=active_voting_records,json=activeVotingRecords,proto3" json:"active_voting_records,omitempty"`
	WithdrawnVotesRecords    []*ElectionVotingRecord `protobuf:"bytes,6,rep,name=withdrawn_votes_records,json=withdrawnVotesRecords,proto3" json:"withdrawn_votes_records,omitempty"`
	PublicKey                []byte                  `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                `json:"-"`
	XXX_unrecognized         []byte                  `json:"-"`
	XXX_sizecache            int32                   `json:"-"`
}

func (m *ElectorVote) Reset()         { *m = ElectorVote{} }
func (m *ElectorVote) String() string { return proto.CompactTextString(m) }
func (*ElectorVote) ProtoMessage()    {}
func (*ElectorVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{9}
}

func (m *ElectorVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectorVote.Unmarshal(m, b)
}
func (m *ElectorVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectorVote.Marshal(b, m, deterministic)
}
func (m *ElectorVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectorVote.Merge(m, src)
}
func (m *ElectorVote) XXX_Size() int {
	return xxx_messageInfo_ElectorVote.Size(m)
}
func (m *ElectorVote) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectorVote.DiscardUnknown(m)
}

var xxx_messageInfo_ElectorVote proto.InternalMessageInfo

func (m *ElectorVote) GetActiveVotingRecordIds() []*aelf.Hash {
	if m != nil {
		return m.ActiveVotingRecordIds
	}
	return nil
}

func (m *ElectorVote) GetWithdrawnVotingRecordIds() []*aelf.Hash {
	if m != nil {
		return m.WithdrawnVotingRecordIds
	}
	return nil
}

func (m *ElectorVote) GetActiveVotedVotesAmount() int64 {
	if m != nil {
		return m.ActiveVotedVotesAmount
	}
	return 0
}

func (m *ElectorVote) GetAllVotedVotesAmount() int64 {
	if m != nil {
		return m.AllVotedVotesAmount
	}
	return 0
}

func (m *ElectorVote) GetActiveVotingRecords() []*ElectionVotingRecord {
	if m != nil {
		return m.ActiveVotingRecords
	}
	return nil
}

func (m *ElectorVote) GetWithdrawnVotesRecords() []*ElectionVotingRecord {
	if m != nil {
		return m.WithdrawnVotesRecords
	}
	return nil
}

func (m *ElectorVote) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type CandidateVote struct {
	ObtainedActiveVotingRecordIds    []*aelf.Hash            `protobuf:"bytes,1,rep,name=obtained_active_voting_record_ids,json=obtainedActiveVotingRecordIds,proto3" json:"obtained_active_voting_record_ids,omitempty"`
	ObtainedWithdrawnVotingRecordIds []*aelf.Hash            `protobuf:"bytes,2,rep,name=obtained_withdrawn_voting_record_ids,json=obtainedWithdrawnVotingRecordIds,proto3" json:"obtained_withdrawn_voting_record_ids,omitempty"`
	ObtainedActiveVotedVotesAmount   int64                   `protobuf:"zigzag64,3,opt,name=obtained_active_voted_votes_amount,json=obtainedActiveVotedVotesAmount,proto3" json:"obtained_active_voted_votes_amount,omitempty"`
	AllObtainedVotedVotesAmount      int64                   `protobuf:"zigzag64,4,opt,name=all_obtained_voted_votes_amount,json=allObtainedVotedVotesAmount,proto3" json:"all_obtained_voted_votes_amount,omitempty"`
	ObtainedActiveVotingRecords      []*ElectionVotingRecord `protobuf:"bytes,5,rep,name=obtained_active_voting_records,json=obtainedActiveVotingRecords,proto3" json:"obtained_active_voting_records,omitempty"`
	ObtainedWithdrawnVotesRecords    []*ElectionVotingRecord `protobuf:"bytes,6,rep,name=obtained_withdrawn_votes_records,json=obtainedWithdrawnVotesRecords,proto3" json:"obtained_withdrawn_votes_records,omitempty"`
	PublicKey                        []byte                  `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                `json:"-"`
	XXX_unrecognized                 []byte                  `json:"-"`
	XXX_sizecache                    int32                   `json:"-"`
}

func (m *CandidateVote) Reset()         { *m = CandidateVote{} }
func (m *CandidateVote) String() string { return proto.CompactTextString(m) }
func (*CandidateVote) ProtoMessage()    {}
func (*CandidateVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{10}
}

func (m *CandidateVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateVote.Unmarshal(m, b)
}
func (m *CandidateVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateVote.Marshal(b, m, deterministic)
}
func (m *CandidateVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateVote.Merge(m, src)
}
func (m *CandidateVote) XXX_Size() int {
	return xxx_messageInfo_CandidateVote.Size(m)
}
func (m *CandidateVote) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateVote.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateVote proto.InternalMessageInfo

func (m *CandidateVote) GetObtainedActiveVotingRecordIds() []*aelf.Hash {
	if m != nil {
		return m.ObtainedActiveVotingRecordIds
	}
	return nil
}

func (m *CandidateVote) GetObtainedWithdrawnVotingRecordIds() []*aelf.Hash {
	if m != nil {
		return m.ObtainedWithdrawnVotingRecordIds
	}
	return nil
}

func (m *CandidateVote) GetObtainedActiveVotedVotesAmount() int64 {
	if m != nil {
		return m.ObtainedActiveVotedVotesAmount
	}
	return 0
}

func (m *CandidateVote) GetAllObtainedVotedVotesAmount() int64 {
	if m != nil {
		return m.AllObtainedVotedVotesAmount
	}
	return 0
}

func (m *CandidateVote) GetObtainedActiveVotingRecords() []*ElectionVotingRecord {
	if m != nil {
		return m.ObtainedActiveVotingRecords
	}
	return nil
}

func (m *CandidateVote) GetObtainedWithdrawnVotesRecords() []*ElectionVotingRecord {
	if m != nil {
		return m.ObtainedWithdrawnVotesRecords
	}
	return nil
}

func (m *CandidateVote) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type CandidateInformation struct {
	PublicKey                 string     `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Terms                     []int64    `protobuf:"zigzag64,2,rep,packed,name=terms,proto3" json:"terms,omitempty"`
	ProducedBlocks            int64      `protobuf:"zigzag64,3,opt,name=produced_blocks,json=producedBlocks,proto3" json:"produced_blocks,omitempty"`
	MissedTimeSlots           int64      `protobuf:"zigzag64,4,opt,name=missed_time_slots,json=missedTimeSlots,proto3" json:"missed_time_slots,omitempty"`
	ContinualAppointmentCount int64      `protobuf:"zigzag64,5,opt,name=continual_appointment_count,json=continualAppointmentCount,proto3" json:"continual_appointment_count,omitempty"`
	AnnouncementTransactionId *aelf.Hash `protobuf:"bytes,6,opt,name=announcement_transaction_id,json=announcementTransactionId,proto3" json:"announcement_transaction_id,omitempty"`
	IsCurrentCandidate        bool       `protobuf:"varint,7,opt,name=is_current_candidate,json=isCurrentCandidate,proto3" json:"is_current_candidate,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}   `json:"-"`
	XXX_unrecognized          []byte     `json:"-"`
	XXX_sizecache             int32      `json:"-"`
}

func (m *CandidateInformation) Reset()         { *m = CandidateInformation{} }
func (m *CandidateInformation) String() string { return proto.CompactTextString(m) }
func (*CandidateInformation) ProtoMessage()    {}
func (*CandidateInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{11}
}

func (m *CandidateInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateInformation.Unmarshal(m, b)
}
func (m *CandidateInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateInformation.Marshal(b, m, deterministic)
}
func (m *CandidateInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateInformation.Merge(m, src)
}
func (m *CandidateInformation) XXX_Size() int {
	return xxx_messageInfo_CandidateInformation.Size(m)
}
func (m *CandidateInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateInformation.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateInformation proto.InternalMessageInfo

func (m *CandidateInformation) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *CandidateInformation) GetTerms() []int64 {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *CandidateInformation) GetProducedBlocks() int64 {
	if m != nil {
		return m.ProducedBlocks
	}
	return 0
}

func (m *CandidateInformation) GetMissedTimeSlots() int64 {
	if m != nil {
		return m.MissedTimeSlots
	}
	return 0
}

func (m *CandidateInformation) GetContinualAppointmentCount() int64 {
	if m != nil {
		return m.ContinualAppointmentCount
	}
	return 0
}

func (m *CandidateInformation) GetAnnouncementTransactionId() *aelf.Hash {
	if m != nil {
		return m.AnnouncementTransactionId
	}
	return nil
}

func (m *CandidateInformation) GetIsCurrentCandidate() bool {
	if m != nil {
		return m.IsCurrentCandidate
	}
	return false
}

type CandidateDetail struct {
	CandidateInformation *CandidateInformation `protobuf:"bytes,1,opt,name=candidate_information,json=candidateInformation,proto3" json:"candidate_information,omitempty"`
	ObtainedVotesAmount  int64                 `protobuf:"zigzag64,2,opt,name=obtained_votes_amount,json=obtainedVotesAmount,proto3" json:"obtained_votes_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CandidateDetail) Reset()         { *m = CandidateDetail{} }
func (m *CandidateDetail) String() string { return proto.CompactTextString(m) }
func (*CandidateDetail) ProtoMessage()    {}
func (*CandidateDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{12}
}

func (m *CandidateDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateDetail.Unmarshal(m, b)
}
func (m *CandidateDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateDetail.Marshal(b, m, deterministic)
}
func (m *CandidateDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateDetail.Merge(m, src)
}
func (m *CandidateDetail) XXX_Size() int {
	return xxx_messageInfo_CandidateDetail.Size(m)
}
func (m *CandidateDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateDetail proto.InternalMessageInfo

func (m *CandidateDetail) GetCandidateInformation() *CandidateInformation {
	if m != nil {
		return m.CandidateInformation
	}
	return nil
}

func (m *CandidateDetail) GetObtainedVotesAmount() int64 {
	if m != nil {
		return m.ObtainedVotesAmount
	}
	return 0
}

type ElectionVotingRecord struct {
	Voter                *aelf.Address        `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Candidate            string               `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Amount               int64                `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TermNumber           int64                `protobuf:"zigzag64,4,opt,name=term_number,json=termNumber,proto3" json:"term_number,omitempty"`
	VoteId               *aelf.Hash           `protobuf:"bytes,5,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	LockTime             int64                `protobuf:"zigzag64,7,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	UnlockTimestamp      *timestamp.Timestamp `protobuf:"bytes,10,opt,name=unlock_timestamp,json=unlockTimestamp,proto3" json:"unlock_timestamp,omitempty"`
	WithdrawTimestamp    *timestamp.Timestamp `protobuf:"bytes,11,opt,name=withdraw_timestamp,json=withdrawTimestamp,proto3" json:"withdraw_timestamp,omitempty"`
	VoteTimestamp        *timestamp.Timestamp `protobuf:"bytes,12,opt,name=vote_timestamp,json=voteTimestamp,proto3" json:"vote_timestamp,omitempty"`
	IsWithdrawn          bool                 `protobuf:"varint,13,opt,name=is_withdrawn,json=isWithdrawn,proto3" json:"is_withdrawn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ElectionVotingRecord) Reset()         { *m = ElectionVotingRecord{} }
func (m *ElectionVotingRecord) String() string { return proto.CompactTextString(m) }
func (*ElectionVotingRecord) ProtoMessage()    {}
func (*ElectionVotingRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{13}
}

func (m *ElectionVotingRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectionVotingRecord.Unmarshal(m, b)
}
func (m *ElectionVotingRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectionVotingRecord.Marshal(b, m, deterministic)
}
func (m *ElectionVotingRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectionVotingRecord.Merge(m, src)
}
func (m *ElectionVotingRecord) XXX_Size() int {
	return xxx_messageInfo_ElectionVotingRecord.Size(m)
}
func (m *ElectionVotingRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectionVotingRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ElectionVotingRecord proto.InternalMessageInfo

func (m *ElectionVotingRecord) GetVoter() *aelf.Address {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *ElectionVotingRecord) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

func (m *ElectionVotingRecord) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ElectionVotingRecord) GetTermNumber() int64 {
	if m != nil {
		return m.TermNumber
	}
	return 0
}

func (m *ElectionVotingRecord) GetVoteId() *aelf.Hash {
	if m != nil {
		return m.VoteId
	}
	return nil
}

func (m *ElectionVotingRecord) GetLockTime() int64 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

func (m *ElectionVotingRecord) GetUnlockTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.UnlockTimestamp
	}
	return nil
}

func (m *ElectionVotingRecord) GetWithdrawTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.WithdrawTimestamp
	}
	return nil
}

func (m *ElectionVotingRecord) GetVoteTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.VoteTimestamp
	}
	return nil
}

func (m *ElectionVotingRecord) GetIsWithdrawn() bool {
	if m != nil {
		return m.IsWithdrawn
	}
	return false
}

type PageInformation struct {
	Start                int32    `protobuf:"zigzag32,1,opt,name=start,proto3" json:"start,omitempty"`
	Length               int32    `protobuf:"zigzag32,2,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInformation) Reset()         { *m = PageInformation{} }
func (m *PageInformation) String() string { return proto.CompactTextString(m) }
func (*PageInformation) ProtoMessage()    {}
func (*PageInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{14}
}

func (m *PageInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInformation.Unmarshal(m, b)
}
func (m *PageInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInformation.Marshal(b, m, deterministic)
}
func (m *PageInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInformation.Merge(m, src)
}
func (m *PageInformation) XXX_Size() int {
	return xxx_messageInfo_PageInformation.Size(m)
}
func (m *PageInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PageInformation proto.InternalMessageInfo

func (m *PageInformation) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *PageInformation) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type StringInput struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringInput) Reset()         { *m = StringInput{} }
func (m *StringInput) String() string { return proto.CompactTextString(m) }
func (*StringInput) ProtoMessage()    {}
func (*StringInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{15}
}

func (m *StringInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringInput.Unmarshal(m, b)
}
func (m *StringInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringInput.Marshal(b, m, deterministic)
}
func (m *StringInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringInput.Merge(m, src)
}
func (m *StringInput) XXX_Size() int {
	return xxx_messageInfo_StringInput.Size(m)
}
func (m *StringInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StringInput.DiscardUnknown(m)
}

var xxx_messageInfo_StringInput proto.InternalMessageInfo

func (m *StringInput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StringOutput struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringOutput) Reset()         { *m = StringOutput{} }
func (m *StringOutput) String() string { return proto.CompactTextString(m) }
func (*StringOutput) ProtoMessage()    {}
func (*StringOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{16}
}

func (m *StringOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringOutput.Unmarshal(m, b)
}
func (m *StringOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringOutput.Marshal(b, m, deterministic)
}
func (m *StringOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringOutput.Merge(m, src)
}
func (m *StringOutput) XXX_Size() int {
	return xxx_messageInfo_StringOutput.Size(m)
}
func (m *StringOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StringOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StringOutput proto.InternalMessageInfo

func (m *StringOutput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PublicKeysList struct {
	Value                [][]byte `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeysList) Reset()         { *m = PublicKeysList{} }
func (m *PublicKeysList) String() string { return proto.CompactTextString(m) }
func (*PublicKeysList) ProtoMessage()    {}
func (*PublicKeysList) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{17}
}

func (m *PublicKeysList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeysList.Unmarshal(m, b)
}
func (m *PublicKeysList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeysList.Marshal(b, m, deterministic)
}
func (m *PublicKeysList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeysList.Merge(m, src)
}
func (m *PublicKeysList) XXX_Size() int {
	return xxx_messageInfo_PublicKeysList.Size(m)
}
func (m *PublicKeysList) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeysList.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeysList proto.InternalMessageInfo

func (m *PublicKeysList) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TermSnapshot struct {
	EndRoundNumber       int64            `protobuf:"zigzag64,1,opt,name=end_round_number,json=endRoundNumber,proto3" json:"end_round_number,omitempty"`
	MinedBlocks          int64            `protobuf:"zigzag64,2,opt,name=mined_blocks,json=minedBlocks,proto3" json:"mined_blocks,omitempty"`
	ElectionResult       map[string]int64 `protobuf:"bytes,3,rep,name=election_result,json=electionResult,proto3" json:"election_result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TermSnapshot) Reset()         { *m = TermSnapshot{} }
func (m *TermSnapshot) String() string { return proto.CompactTextString(m) }
func (*TermSnapshot) ProtoMessage()    {}
func (*TermSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{18}
}

func (m *TermSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermSnapshot.Unmarshal(m, b)
}
func (m *TermSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermSnapshot.Marshal(b, m, deterministic)
}
func (m *TermSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermSnapshot.Merge(m, src)
}
func (m *TermSnapshot) XXX_Size() int {
	return xxx_messageInfo_TermSnapshot.Size(m)
}
func (m *TermSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_TermSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_TermSnapshot proto.InternalMessageInfo

func (m *TermSnapshot) GetEndRoundNumber() int64 {
	if m != nil {
		return m.EndRoundNumber
	}
	return 0
}

func (m *TermSnapshot) GetMinedBlocks() int64 {
	if m != nil {
		return m.MinedBlocks
	}
	return 0
}

func (m *TermSnapshot) GetElectionResult() map[string]int64 {
	if m != nil {
		return m.ElectionResult
	}
	return nil
}

type UpdateMinersCountInput struct {
	MinersCount          int32    `protobuf:"zigzag32,1,opt,name=miners_count,json=minersCount,proto3" json:"miners_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMinersCountInput) Reset()         { *m = UpdateMinersCountInput{} }
func (m *UpdateMinersCountInput) String() string { return proto.CompactTextString(m) }
func (*UpdateMinersCountInput) ProtoMessage()    {}
func (*UpdateMinersCountInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{19}
}

func (m *UpdateMinersCountInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMinersCountInput.Unmarshal(m, b)
}
func (m *UpdateMinersCountInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMinersCountInput.Marshal(b, m, deterministic)
}
func (m *UpdateMinersCountInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMinersCountInput.Merge(m, src)
}
func (m *UpdateMinersCountInput) XXX_Size() int {
	return xxx_messageInfo_UpdateMinersCountInput.Size(m)
}
func (m *UpdateMinersCountInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMinersCountInput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMinersCountInput proto.InternalMessageInfo

func (m *UpdateMinersCountInput) GetMinersCount() int32 {
	if m != nil {
		return m.MinersCount
	}
	return 0
}

type GetWelfareRewardAmountSampleInput struct {
	Value                []int64  `protobuf:"zigzag64,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWelfareRewardAmountSampleInput) Reset()         { *m = GetWelfareRewardAmountSampleInput{} }
func (m *GetWelfareRewardAmountSampleInput) String() string { return proto.CompactTextString(m) }
func (*GetWelfareRewardAmountSampleInput) ProtoMessage()    {}
func (*GetWelfareRewardAmountSampleInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{20}
}

func (m *GetWelfareRewardAmountSampleInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWelfareRewardAmountSampleInput.Unmarshal(m, b)
}
func (m *GetWelfareRewardAmountSampleInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWelfareRewardAmountSampleInput.Marshal(b, m, deterministic)
}
func (m *GetWelfareRewardAmountSampleInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWelfareRewardAmountSampleInput.Merge(m, src)
}
func (m *GetWelfareRewardAmountSampleInput) XXX_Size() int {
	return xxx_messageInfo_GetWelfareRewardAmountSampleInput.Size(m)
}
func (m *GetWelfareRewardAmountSampleInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWelfareRewardAmountSampleInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetWelfareRewardAmountSampleInput proto.InternalMessageInfo

func (m *GetWelfareRewardAmountSampleInput) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetWelfareRewardAmountSampleOutput struct {
	Value                []int64  `protobuf:"zigzag64,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWelfareRewardAmountSampleOutput) Reset()         { *m = GetWelfareRewardAmountSampleOutput{} }
func (m *GetWelfareRewardAmountSampleOutput) String() string { return proto.CompactTextString(m) }
func (*GetWelfareRewardAmountSampleOutput) ProtoMessage()    {}
func (*GetWelfareRewardAmountSampleOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{21}
}

func (m *GetWelfareRewardAmountSampleOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWelfareRewardAmountSampleOutput.Unmarshal(m, b)
}
func (m *GetWelfareRewardAmountSampleOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWelfareRewardAmountSampleOutput.Marshal(b, m, deterministic)
}
func (m *GetWelfareRewardAmountSampleOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWelfareRewardAmountSampleOutput.Merge(m, src)
}
func (m *GetWelfareRewardAmountSampleOutput) XXX_Size() int {
	return xxx_messageInfo_GetWelfareRewardAmountSampleOutput.Size(m)
}
func (m *GetWelfareRewardAmountSampleOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWelfareRewardAmountSampleOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetWelfareRewardAmountSampleOutput proto.InternalMessageInfo

func (m *GetWelfareRewardAmountSampleOutput) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetPageableCandidateInformationOutput struct {
	Value                []*CandidateDetail `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPageableCandidateInformationOutput) Reset()         { *m = GetPageableCandidateInformationOutput{} }
func (m *GetPageableCandidateInformationOutput) String() string { return proto.CompactTextString(m) }
func (*GetPageableCandidateInformationOutput) ProtoMessage()    {}
func (*GetPageableCandidateInformationOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_beb1d82cbada648c, []int{22}
}

func (m *GetPageableCandidateInformationOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageableCandidateInformationOutput.Unmarshal(m, b)
}
func (m *GetPageableCandidateInformationOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageableCandidateInformationOutput.Marshal(b, m, deterministic)
}
func (m *GetPageableCandidateInformationOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageableCandidateInformationOutput.Merge(m, src)
}
func (m *GetPageableCandidateInformationOutput) XXX_Size() int {
	return xxx_messageInfo_GetPageableCandidateInformationOutput.Size(m)
}
func (m *GetPageableCandidateInformationOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageableCandidateInformationOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageableCandidateInformationOutput proto.InternalMessageInfo

func (m *GetPageableCandidateInformationOutput) GetValue() []*CandidateDetail {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*InitialElectionContractInput)(nil), "Election.InitialElectionContractInput")
	proto.RegisterType((*ConfigElectionContractInput)(nil), "Election.ConfigElectionContractInput")
	proto.RegisterType((*GetTermSnapshotInput)(nil), "Election.GetTermSnapshotInput")
	proto.RegisterType((*UpdateCandidateInformationInput)(nil), "Election.UpdateCandidateInformationInput")
	proto.RegisterType((*ReleaseTreasuryProfitsInput)(nil), "Election.ReleaseTreasuryProfitsInput")
	proto.RegisterType((*VoteMinerInput)(nil), "Election.VoteMinerInput")
	proto.RegisterType((*UpdateTermNumberInput)(nil), "Election.UpdateTermNumberInput")
	proto.RegisterType((*GetElectionResultInput)(nil), "Election.GetElectionResultInput")
	proto.RegisterType((*ElectionResult)(nil), "Election.ElectionResult")
	proto.RegisterMapType((map[string]int64)(nil), "Election.ElectionResult.ResultsEntry")
	proto.RegisterType((*ElectorVote)(nil), "Election.ElectorVote")
	proto.RegisterType((*CandidateVote)(nil), "Election.CandidateVote")
	proto.RegisterType((*CandidateInformation)(nil), "Election.CandidateInformation")
	proto.RegisterType((*CandidateDetail)(nil), "Election.CandidateDetail")
	proto.RegisterType((*ElectionVotingRecord)(nil), "Election.ElectionVotingRecord")
	proto.RegisterType((*PageInformation)(nil), "Election.PageInformation")
	proto.RegisterType((*StringInput)(nil), "Election.StringInput")
	proto.RegisterType((*StringOutput)(nil), "Election.StringOutput")
	proto.RegisterType((*PublicKeysList)(nil), "Election.PublicKeysList")
	proto.RegisterType((*TermSnapshot)(nil), "Election.TermSnapshot")
	proto.RegisterMapType((map[string]int64)(nil), "Election.TermSnapshot.ElectionResultEntry")
	proto.RegisterType((*UpdateMinersCountInput)(nil), "Election.UpdateMinersCountInput")
	proto.RegisterType((*GetWelfareRewardAmountSampleInput)(nil), "Election.GetWelfareRewardAmountSampleInput")
	proto.RegisterType((*GetWelfareRewardAmountSampleOutput)(nil), "Election.GetWelfareRewardAmountSampleOutput")
	proto.RegisterType((*GetPageableCandidateInformationOutput)(nil), "Election.GetPageableCandidateInformationOutput")
}

func init() { proto.RegisterFile("election_contract.proto", fileDescriptor_beb1d82cbada648c) }

var fileDescriptor_beb1d82cbada648c = []byte{
	// 1930 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5f, 0x73, 0x1b, 0x49,
	0x11, 0x47, 0x96, 0xed, 0xd8, 0x2d, 0x59, 0xb6, 0xc7, 0xb6, 0x2c, 0x4b, 0x49, 0x6c, 0x6f, 0x72,
	0x87, 0x39, 0x40, 0xbe, 0x72, 0x28, 0x48, 0x72, 0x55, 0x04, 0xc5, 0x11, 0x3e, 0x85, 0xcb, 0x25,
	0xac, 0x84, 0xc3, 0xc1, 0xc3, 0xd6, 0x78, 0x77, 0x2c, 0x4f, 0x65, 0x77, 0x56, 0xb5, 0x33, 0x72,
	0xf0, 0x1b, 0x0f, 0x14, 0x05, 0x5f, 0x81, 0x8f, 0xc0, 0x23, 0x9f, 0x80, 0x77, 0xee, 0x03, 0xc0,
	0x0b, 0x5f, 0x82, 0x2a, 0x78, 0xa5, 0x66, 0x66, 0xff, 0x4a, 0xab, 0x3f, 0x4e, 0x5e, 0x6c, 0xcd,
	0x4c, 0xf7, 0x6f, 0x7b, 0xba, 0x7b, 0xa6, 0x7f, 0x3d, 0xb0, 0x4b, 0x5c, 0x62, 0x0b, 0xea, 0x33,
	0xcb, 0xf6, 0x99, 0x08, 0xb0, 0x2d, 0x9a, 0x83, 0xc0, 0x17, 0x3e, 0x5a, 0x69, 0x87, 0x0b, 0x75,
	0x84, 0x89, 0x7b, 0x79, 0xec, 0x0f, 0xe4, 0x80, 0xeb, 0xd5, 0xfa, 0xba, 0x9a, 0xb3, 0xfd, 0x80,
	0x84, 0x13, 0x8d, 0xbe, 0xef, 0xf7, 0x5d, 0x72, 0xac, 0x46, 0x17, 0xc3, 0xcb, 0x63, 0xe2, 0x0d,
	0xc4, 0x4d, 0xb8, 0xb8, 0x3f, 0xba, 0x28, 0xa8, 0x47, 0xb8, 0xc0, 0xde, 0x40, 0x0b, 0x18, 0xd7,
	0x70, 0xb7, 0xc3, 0xa8, 0xa0, 0xd8, 0x8d, 0xbe, 0x7a, 0x1a, 0x5a, 0xd3, 0x61, 0x83, 0xa1, 0x40,
	0x9f, 0xc1, 0xa6, 0x47, 0x19, 0xf5, 0x86, 0x9e, 0xe5, 0xfa, 0xf6, 0x3b, 0x4b, 0xea, 0xd7, 0x0a,
	0x07, 0x85, 0x23, 0x64, 0xae, 0x87, 0x0b, 0x5f, 0xf9, 0xf6, 0xbb, 0x1e, 0xf5, 0x88, 0x92, 0xc5,
	0xbf, 0x1b, 0x91, 0x5d, 0x08, 0x65, 0xf5, 0x42, 0x24, 0x6b, 0x5c, 0x40, 0xe3, 0xd4, 0x67, 0x97,
	0xb4, 0x9f, 0xff, 0xd9, 0x7b, 0x00, 0x1e, 0x65, 0x24, 0xb0, 0x5c, 0xca, 0x45, 0xad, 0x70, 0x50,
	0x3c, 0x5a, 0x35, 0x57, 0xd5, 0xcc, 0x57, 0x94, 0x0b, 0xf4, 0x10, 0x2a, 0x12, 0xdc, 0x22, 0xd8,
	0xbe, 0xb2, 0x04, 0x09, 0xbc, 0xf0, 0x33, 0x65, 0x39, 0xdb, 0xc6, 0xf6, 0x55, 0x8f, 0x04, 0x9e,
	0xf1, 0x13, 0xd8, 0x3e, 0x23, 0x42, 0xfe, 0xec, 0x32, 0x3c, 0xe0, 0x57, 0x7e, 0x08, 0xbe, 0x0f,
	0x25, 0xa9, 0x63, 0xb1, 0xa1, 0x77, 0x41, 0x82, 0x70, 0x37, 0x20, 0xa7, 0xbe, 0x56, 0x33, 0xc6,
	0xbf, 0x0a, 0xb0, 0xff, 0xab, 0x81, 0x83, 0x05, 0x39, 0xc5, 0xcc, 0xa1, 0xf2, 0x47, 0x87, 0x5d,
	0xfa, 0x81, 0x87, 0xa5, 0xa5, 0xb1, 0x85, 0x83, 0xe1, 0x85, 0x4b, 0x6d, 0xeb, 0x1d, 0xb9, 0x51,
	0x18, 0xab, 0xe6, 0xaa, 0x9e, 0xf9, 0x05, 0xb9, 0x41, 0x8f, 0xa1, 0x16, 0x10, 0x9b, 0x30, 0xe1,
	0xde, 0x58, 0x83, 0xc0, 0x77, 0x86, 0x36, 0x71, 0xac, 0x0b, 0xe9, 0x16, 0x1e, 0xda, 0x5a, 0x8d,
	0xd6, 0xdf, 0x84, 0xcb, 0xcf, 0xd5, 0x2a, 0xfa, 0x02, 0xea, 0xb1, 0xa6, 0x47, 0x39, 0x27, 0x8e,
	0x72, 0xa4, 0xc5, 0x5d, 0x5f, 0xf0, 0x5a, 0x51, 0xe9, 0xee, 0x46, 0x12, 0xaf, 0x94, 0x80, 0xf4,
	0x68, 0x57, 0x2e, 0xa3, 0x03, 0x28, 0x53, 0x6e, 0x91, 0x6b, 0xea, 0x5a, 0xcc, 0x77, 0x48, 0x6d,
	0xf1, 0xa0, 0x70, 0xb4, 0x62, 0x02, 0xe5, 0xed, 0x6b, 0xea, 0x7e, 0xed, 0x3b, 0xc4, 0xf8, 0x43,
	0x01, 0x1a, 0x26, 0x71, 0x09, 0xe6, 0xa4, 0x17, 0x10, 0xcc, 0x87, 0x81, 0x34, 0xe0, 0x92, 0x0a,
	0x3e, 0x9f, 0x73, 0xd0, 0x21, 0x94, 0x65, 0x20, 0x46, 0x76, 0x53, 0x52, 0x73, 0xe1, 0x16, 0x0e,
	0xa1, 0x1c, 0xf8, 0x43, 0xe6, 0x44, 0x20, 0xda, 0xe8, 0x92, 0x9a, 0x0b, 0x5d, 0xfc, 0x97, 0x02,
	0x54, 0xce, 0x7d, 0x41, 0x5e, 0xc9, 0x98, 0xea, 0x2f, 0x1f, 0xc3, 0x96, 0x1d, 0xb9, 0xdb, 0x8a,
	0x3d, 0x19, 0xba, 0x16, 0xc5, 0x4b, 0x6f, 0x62, 0x1f, 0x57, 0x61, 0x19, 0x7b, 0xfe, 0x90, 0x89,
	0xd0, 0x86, 0x70, 0x84, 0x9e, 0xc1, 0x1a, 0x61, 0xda, 0x6b, 0x2a, 0xd5, 0xd5, 0xf7, 0x4b, 0x27,
	0xf5, 0xa6, 0x3e, 0x0c, 0xcd, 0xe8, 0x30, 0x34, 0x7b, 0x91, 0x84, 0x59, 0x26, 0xcc, 0x89, 0x47,
	0xc6, 0x63, 0xd8, 0xd1, 0xe1, 0xef, 0xc5, 0xdb, 0x9e, 0x33, 0x73, 0x9e, 0x40, 0xf5, 0x8c, 0x88,
	0x28, 0xa7, 0x4d, 0xc2, 0x87, 0xee, 0xbc, 0x49, 0xf7, 0x8f, 0x02, 0x54, 0xb2, 0x8a, 0xb3, 0x63,
	0xf1, 0x0c, 0xee, 0x04, 0x4a, 0x54, 0x86, 0xa1, 0x78, 0x54, 0x3a, 0xf9, 0xa4, 0x19, 0x41, 0x34,
	0xb3, 0x58, 0x4d, 0xfd, 0x8f, 0xb7, 0x99, 0x08, 0x6e, 0xcc, 0x48, 0x0b, 0x35, 0x60, 0x95, 0x72,
	0x0b, 0xdb, 0x82, 0x5e, 0x13, 0xe5, 0xa6, 0x15, 0x73, 0x85, 0xf2, 0x96, 0x1a, 0xd7, 0x9f, 0x42,
	0x39, 0xad, 0x85, 0x36, 0xa0, 0x98, 0xe4, 0xba, 0xfc, 0x89, 0xb6, 0x61, 0xe9, 0x1a, 0xbb, 0xc3,
	0xe8, 0x94, 0xeb, 0xc1, 0xd3, 0x85, 0xc7, 0x05, 0xe3, 0x9f, 0x45, 0x28, 0x29, 0x0b, 0xfc, 0x40,
	0x86, 0x19, 0x9d, 0x42, 0x4d, 0x7f, 0xc5, 0xba, 0xf6, 0x05, 0x65, 0x7d, 0x2b, 0x20, 0xb6, 0x1f,
	0x38, 0x16, 0x75, 0xb8, 0x3a, 0xde, 0xa5, 0x13, 0x68, 0xca, 0x9b, 0xad, 0xf9, 0x25, 0xe6, 0x57,
	0xe6, 0x8e, 0x96, 0x3d, 0x57, 0xa2, 0xa6, 0x92, 0xec, 0x38, 0x1c, 0x75, 0xa0, 0xf1, 0x9e, 0x8a,
	0x2b, 0x27, 0xc0, 0xef, 0x59, 0x0e, 0xce, 0xc2, 0x18, 0x4e, 0x2d, 0x16, 0x1f, 0x85, 0x7a, 0x02,
	0x7b, 0x89, 0x3d, 0xc4, 0x51, 0x7f, 0xb9, 0x15, 0xa6, 0x93, 0xce, 0xd7, 0x6a, 0x6c, 0x04, 0x71,
	0xe4, 0x1f, 0xde, 0xd2, 0xe9, 0xf5, 0x08, 0xaa, 0xd8, 0x75, 0xf3, 0xf4, 0x16, 0x95, 0xde, 0x16,
	0x76, 0xdd, 0x31, 0x25, 0x13, 0x76, 0xf2, 0xf6, 0xcf, 0x6b, 0x4b, 0xca, 0xe8, 0xfb, 0xe3, 0x71,
	0x4b, 0x5b, 0x6c, 0x6e, 0x8d, 0x3b, 0x84, 0xa3, 0x73, 0xd8, 0xcd, 0xb8, 0x83, 0xf0, 0x18, 0x75,
	0x79, 0x2e, 0xd4, 0x9d, 0xb4, 0x7b, 0x08, 0x8f, 0x70, 0xb3, 0x57, 0xdb, 0x9d, 0x83, 0xc2, 0x51,
	0x39, 0x75, 0xb5, 0x19, 0x7f, 0x5f, 0x84, 0xb5, 0xf8, 0x5e, 0x54, 0xc1, 0xed, 0xc1, 0xa1, 0x7f,
	0x21, 0xb0, 0xba, 0x15, 0x6e, 0x11, 0xe5, 0x7b, 0x91, 0x52, 0x2b, 0x37, 0xda, 0xbf, 0x81, 0x87,
	0x31, 0xea, 0xed, 0xc2, 0x7e, 0x10, 0xe9, 0xbd, 0x9d, 0x14, 0xfe, 0x97, 0x60, 0xe4, 0x58, 0x9c,
	0x9f, 0x07, 0xf7, 0xc7, 0xcc, 0xcc, 0x86, 0xf6, 0x05, 0xec, 0xcb, 0x7c, 0x88, 0xf1, 0x26, 0x26,
	0x46, 0x03, 0xbb, 0xee, 0xeb, 0x50, 0x6a, 0x0c, 0xc5, 0x86, 0xfb, 0x53, 0x7d, 0x38, 0x6f, 0xa6,
	0x34, 0x26, 0x3b, 0x95, 0xa3, 0x3e, 0x1c, 0xe4, 0xbb, 0xf4, 0xd6, 0xa9, 0x73, 0x2f, 0xcf, 0xc5,
	0x73, 0xa7, 0xd0, 0xbf, 0x17, 0x60, 0x3b, 0xaf, 0xb4, 0xce, 0xaa, 0xaa, 0xdb, 0xb0, 0x24, 0x6f,
	0x3f, 0x1d, 0x73, 0x64, 0xea, 0x01, 0xfa, 0x2e, 0xac, 0x8f, 0x96, 0x58, 0x1d, 0xb9, 0xca, 0x20,
	0x5b, 0x5a, 0x15, 0x99, 0x19, 0xad, 0xa8, 0x8b, 0x11, 0x99, 0xc9, 0x56, 0xd2, 0x9f, 0x42, 0x43,
	0xf2, 0x32, 0xca, 0x86, 0xd8, 0xb5, 0xf0, 0x60, 0xe0, 0x53, 0x26, 0x3c, 0xc2, 0x84, 0x65, 0xab,
	0x88, 0x2e, 0x29, 0xad, 0xbd, 0x58, 0xa4, 0x95, 0x48, 0x9c, 0xaa, 0x78, 0xbe, 0x84, 0x06, 0x66,
	0xcc, 0x1f, 0x32, 0x9b, 0x28, 0x35, 0x11, 0x60, 0xc6, 0xb1, 0x26, 0x7c, 0xd4, 0xa9, 0x2d, 0xab,
	0x92, 0x94, 0x4e, 0xda, 0xbd, 0xb4, 0x78, 0x2f, 0x91, 0xee, 0x38, 0xe8, 0x73, 0xd8, 0xa6, 0xdc,
	0xb2, 0x87, 0x41, 0xa0, 0x0c, 0x88, 0x1c, 0xa7, 0xfc, 0xba, 0x62, 0x22, 0xca, 0x4f, 0xf5, 0x52,
	0xec, 0x52, 0x59, 0x5e, 0xd7, 0xe3, 0xd1, 0x0b, 0x22, 0x30, 0x75, 0x51, 0x17, 0x76, 0x92, 0xfa,
	0x4a, 0x13, 0xa7, 0x2b, 0x37, 0x67, 0x22, 0x9e, 0x17, 0x1a, 0x73, 0xdb, 0xce, 0x0b, 0xd8, 0x09,
	0xec, 0x64, 0x12, 0x3f, 0x4e, 0x79, 0x5d, 0x11, 0xb6, 0xfc, 0x54, 0xbe, 0x87, 0xa9, 0x6e, 0x7c,
	0x5b, 0x84, 0xed, 0xbc, 0xa4, 0x42, 0x0f, 0x60, 0x49, 0x62, 0x04, 0xa1, 0x45, 0x6b, 0xda, 0x3b,
	0x2d, 0xc7, 0x09, 0x08, 0xe7, 0xa6, 0x5e, 0x43, 0x77, 0x61, 0x35, 0xf1, 0xc0, 0x82, 0xce, 0x90,
	0x78, 0x22, 0xc5, 0x09, 0x8a, 0x19, 0x4e, 0x30, 0x52, 0x4a, 0x17, 0xc7, 0x4a, 0xe9, 0x03, 0xb8,
	0x23, 0xf1, 0x65, 0x6c, 0x96, 0xc6, 0x62, 0xb3, 0x2c, 0x97, 0x3a, 0x8e, 0x2c, 0x97, 0x09, 0xb3,
	0xbd, 0xa3, 0x30, 0x56, 0xdc, 0x88, 0xfe, 0xb6, 0x61, 0x63, 0xc8, 0xe2, 0x65, 0xcd, 0x3c, 0x60,
	0x26, 0xf3, 0x58, 0xd7, 0x3a, 0xf1, 0x04, 0xea, 0x00, 0x8a, 0x8e, 0x66, 0x0a, 0xa8, 0x34, 0x13,
	0x68, 0x33, 0xd2, 0x4a, 0xa0, 0x5a, 0x50, 0x51, 0x7b, 0x4a, 0x60, 0xca, 0x33, 0x61, 0xd6, 0xa4,
	0x46, 0x02, 0x71, 0xa8, 0x08, 0x65, 0x7c, 0x57, 0xd4, 0xd6, 0x54, 0xca, 0x95, 0x28, 0x8f, 0xcf,
	0xbd, 0xf1, 0x0c, 0xd6, 0xdf, 0xe0, 0x7e, 0x26, 0x2b, 0xb6, 0x61, 0x89, 0x0b, 0x1c, 0x08, 0x15,
	0xc8, 0x4d, 0x53, 0x0f, 0x64, 0x6c, 0x5c, 0xc2, 0xfa, 0xe2, 0x4a, 0x85, 0x6d, 0xd3, 0x0c, 0x47,
	0xc6, 0x03, 0x28, 0x75, 0x45, 0x40, 0x59, 0x5f, 0x33, 0xa5, 0x98, 0x54, 0xe8, 0xe3, 0xaf, 0x07,
	0xc6, 0x43, 0x28, 0x6b, 0xa1, 0xd7, 0x43, 0x31, 0x59, 0xea, 0x53, 0xa8, 0xc4, 0xfc, 0x90, 0xab,
	0x56, 0x21, 0x25, 0x57, 0x3c, 0x2a, 0x47, 0x72, 0xff, 0x29, 0x40, 0x39, 0xdd, 0x18, 0xa0, 0x23,
	0xd8, 0x90, 0x9c, 0x31, 0x43, 0x5b, 0x35, 0xdf, 0xaa, 0x10, 0xe6, 0x98, 0x09, 0x73, 0x9d, 0x87,
	0xff, 0x76, 0x61, 0x3d, 0x6e, 0xee, 0x34, 0xd3, 0xaa, 0x15, 0xd5, 0xad, 0xfa, 0x59, 0x72, 0xc6,
	0xd2, 0x5f, 0x1f, 0xe1, 0x6a, 0x9a, 0xa3, 0x55, 0x48, 0x66, 0xb2, 0xde, 0x82, 0xad, 0x1c, 0xb1,
	0x5b, 0x91, 0xb2, 0x2f, 0xa0, 0xaa, 0x79, 0xad, 0x62, 0xdd, 0x5c, 0x5d, 0x54, 0xda, 0xe7, 0xe1,
	0xa6, 0x02, 0x1e, 0x5e, 0x6f, 0x3a, 0x6e, 0x25, 0x2f, 0x91, 0x33, 0x9e, 0xc0, 0xe1, 0x19, 0x11,
	0x6f, 0x89, 0x7b, 0x89, 0x03, 0x62, 0x92, 0xf7, 0x38, 0x70, 0xf4, 0x79, 0xee, 0x62, 0x6f, 0xe0,
	0x92, 0xb1, 0xd8, 0x15, 0xe3, 0x6f, 0x1b, 0x4f, 0xc1, 0x98, 0xa6, 0x3a, 0x1e, 0xd1, 0x94, 0xee,
	0xaf, 0xe1, 0x93, 0x33, 0x22, 0x64, 0x82, 0xe1, 0x0b, 0x37, 0xb7, 0x1f, 0x0b, 0xd5, 0x8f, 0xd3,
	0xea, 0xa5, 0x93, 0xbd, 0x9c, 0xeb, 0x4c, 0x5f, 0x84, 0x21, 0xf2, 0xc9, 0x1f, 0xb7, 0x61, 0x63,
	0xb4, 0xfb, 0x44, 0xbf, 0x85, 0xdd, 0x09, 0xfd, 0x30, 0xfa, 0x34, 0x41, 0x9c, 0xd6, 0x32, 0xd7,
	0xab, 0x63, 0xa7, 0xab, 0x2d, 0x3b, 0x72, 0xe3, 0x3b, 0xe8, 0x1b, 0xa8, 0xe6, 0x37, 0xbd, 0x28,
	0xc5, 0xdb, 0xa7, 0xb4, 0xc5, 0x53, 0xa0, 0x5f, 0xcb, 0xae, 0xae, 0x4f, 0xb9, 0x20, 0x41, 0xf6,
	0x6a, 0x6d, 0x5f, 0x13, 0x26, 0xd0, 0x04, 0xc5, 0x29, 0x80, 0x2f, 0x60, 0xa3, 0x15, 0x16, 0xa4,
	0x08, 0xf0, 0x03, 0x50, 0x7e, 0x06, 0xe5, 0x5f, 0x0e, 0xa9, 0xf8, 0x08, 0x84, 0xa7, 0xb0, 0xa8,
	0x38, 0x66, 0x2d, 0xf1, 0x50, 0xb6, 0x6f, 0x9c, 0xa2, 0xfb, 0x39, 0xac, 0x44, 0xd7, 0x14, 0x4a,
	0x5d, 0xe7, 0x53, 0x34, 0x30, 0xd4, 0x27, 0x37, 0xfe, 0xe8, 0x7b, 0x89, 0x0d, 0x33, 0x9e, 0x07,
	0xa6, 0x46, 0x6a, 0x73, 0xec, 0x10, 0xa2, 0x83, 0x51, 0xe4, 0xd1, 0x13, 0x3a, 0x05, 0xf0, 0x39,
	0x54, 0x4e, 0x03, 0x22, 0xbb, 0xd5, 0xb0, 0x9f, 0xff, 0x00, 0x2f, 0xff, 0x1c, 0x50, 0x94, 0x3e,
	0x3d, 0xff, 0x23, 0x70, 0xbe, 0x81, 0x6a, 0xfe, 0xe3, 0x42, 0x3a, 0xc3, 0xa7, 0x3c, 0x3f, 0x4c,
	0x81, 0xfe, 0x12, 0xd6, 0xce, 0x48, 0x42, 0x71, 0xf8, 0x44, 0xeb, 0x52, 0x99, 0x92, 0xad, 0x05,
	0xc6, 0xd2, 0x9f, 0xfe, 0xfc, 0xbf, 0x42, 0x01, 0xbd, 0x85, 0xdd, 0x34, 0x52, 0x3a, 0xc2, 0x3b,
	0x89, 0x6e, 0xaa, 0x24, 0xd5, 0x67, 0x70, 0xa3, 0x08, 0xf8, 0x0c, 0xca, 0x67, 0x44, 0x9c, 0x53,
	0xd9, 0xf5, 0xd2, 0x8f, 0xb1, 0xf0, 0x0d, 0xac, 0x8f, 0xbc, 0x5c, 0xa1, 0x94, 0x09, 0x79, 0x8f,
	0x5a, 0xf5, 0x6a, 0x7e, 0x69, 0x89, 0x10, 0x9f, 0x43, 0xe5, 0x8c, 0x88, 0x74, 0xca, 0x4d, 0x32,
	0x6e, 0x53, 0x1f, 0x94, 0x6e, 0x87, 0x89, 0x47, 0x27, 0xe7, 0xea, 0x0e, 0x0e, 0x31, 0xce, 0x61,
	0x73, 0xec, 0x71, 0x23, 0x9d, 0xb9, 0xf9, 0x2f, 0x1f, 0xe9, 0xdd, 0x66, 0x97, 0x23, 0xdc, 0xb6,
	0xb2, 0x2d, 0xfd, 0x5a, 0x30, 0x21, 0x0c, 0x3b, 0x23, 0x48, 0x5a, 0x3a, 0x71, 0xda, 0x5e, 0x16,
	0x46, 0x9e, 0xfd, 0xa8, 0x21, 0xf9, 0x20, 0xc4, 0x2e, 0xdc, 0x1d, 0x47, 0x6c, 0xb9, 0xee, 0x47,
	0x81, 0x76, 0x60, 0x23, 0x9d, 0x7d, 0xd3, 0xf6, 0xbb, 0x9b, 0x93, 0x76, 0x69, 0xa8, 0x1e, 0x34,
	0x46, 0xa1, 0xe6, 0xd8, 0xf3, 0x2c, 0xd4, 0xb7, 0x70, 0x3f, 0x0f, 0x75, 0xf6, 0xbe, 0x67, 0x01,
	0xeb, 0x1c, 0x94, 0x33, 0xb7, 0xc8, 0xc1, 0x1f, 0xff, 0x28, 0x93, 0x83, 0x09, 0x46, 0xd4, 0x38,
	0xdf, 0x1e, 0xe3, 0xa5, 0x7a, 0xa4, 0x0b, 0x7b, 0xa6, 0x57, 0x94, 0xa9, 0x06, 0x44, 0x92, 0x92,
	0x0f, 0xc0, 0xfa, 0x7d, 0x41, 0xe5, 0xc8, 0x44, 0x6e, 0x83, 0xbe, 0x9f, 0x39, 0x1f, 0xd3, 0xe9,
	0x53, 0xfd, 0x07, 0xf3, 0x09, 0x6b, 0xc6, 0x93, 0x6c, 0x67, 0x37, 0xd9, 0x4e, 0x46, 0x67, 0x52,
	0xa0, 0x26, 0x6f, 0x47, 0xc0, 0xfe, 0x0c, 0xb6, 0x85, 0x52, 0xc4, 0x6a, 0x84, 0xf6, 0xd7, 0x8f,
	0x33, 0xe6, 0xcf, 0xe6, 0x6c, 0xc9, 0x91, 0xb8, 0x1b, 0x5d, 0x4e, 0x59, 0xf2, 0xd2, 0x11, 0xc4,
	0xeb, 0x4c, 0x0e, 0x4b, 0xaa, 0xa6, 0x87, 0x50, 0xf5, 0x93, 0xbf, 0x7d, 0xfb, 0xdf, 0xc2, 0x0f,
	0x5b, 0x6d, 0xf7, 0xb2, 0x19, 0x51, 0x27, 0x3e, 0x7e, 0xff, 0x44, 0x4b, 0x5d, 0x81, 0x05, 0x79,
	0x5e, 0xff, 0xeb, 0xc2, 0xee, 0x04, 0x8d, 0x8b, 0x65, 0xf5, 0xc9, 0x47, 0xff, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0x0e, 0xed, 0x57, 0xaf, 0xae, 0x19, 0x00, 0x00,
}
