// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profit_contract.proto

package profit

import (
	aelf "aelf"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProfitItemInput struct {
	TotalWeight              int64    `protobuf:"zigzag64,1,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	TokenSymbol              string   `protobuf:"bytes,2,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`
	ExpiredPeriodNumber      int64    `protobuf:"zigzag64,3,opt,name=expired_period_number,json=expiredPeriodNumber,proto3" json:"expired_period_number,omitempty"`
	ReleaseAllIfAmountIsZero bool     `protobuf:"varint,4,opt,name=release_all_if_amount_is_zero,json=releaseAllIfAmountIsZero,proto3" json:"release_all_if_amount_is_zero,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *CreateProfitItemInput) Reset()         { *m = CreateProfitItemInput{} }
func (m *CreateProfitItemInput) String() string { return proto.CompactTextString(m) }
func (*CreateProfitItemInput) ProtoMessage()    {}
func (*CreateProfitItemInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{0}
}

func (m *CreateProfitItemInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfitItemInput.Unmarshal(m, b)
}
func (m *CreateProfitItemInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfitItemInput.Marshal(b, m, deterministic)
}
func (m *CreateProfitItemInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfitItemInput.Merge(m, src)
}
func (m *CreateProfitItemInput) XXX_Size() int {
	return xxx_messageInfo_CreateProfitItemInput.Size(m)
}
func (m *CreateProfitItemInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfitItemInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfitItemInput proto.InternalMessageInfo

func (m *CreateProfitItemInput) GetTotalWeight() int64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *CreateProfitItemInput) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *CreateProfitItemInput) GetExpiredPeriodNumber() int64 {
	if m != nil {
		return m.ExpiredPeriodNumber
	}
	return 0
}

func (m *CreateProfitItemInput) GetReleaseAllIfAmountIsZero() bool {
	if m != nil {
		return m.ReleaseAllIfAmountIsZero
	}
	return false
}

type ProfitItem struct {
	VirtualAddress           *aelf.Address    `protobuf:"bytes,1,opt,name=virtual_address,json=virtualAddress,proto3" json:"virtual_address,omitempty"`
	TotalWeight              int64            `protobuf:"zigzag64,2,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	TotalAmount              int64            `protobuf:"zigzag64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CurrentPeriod            int64            `protobuf:"zigzag64,4,opt,name=current_period,json=currentPeriod,proto3" json:"current_period,omitempty"`
	TokenSymbol              string           `protobuf:"bytes,5,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`
	SubProfitItems           []*SubProfitItem `protobuf:"bytes,7,rep,name=sub_profit_items,json=subProfitItems,proto3" json:"sub_profit_items,omitempty"`
	Creator                  *aelf.Address    `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	ExpiredPeriodNumber      int64            `protobuf:"zigzag64,9,opt,name=expired_period_number,json=expiredPeriodNumber,proto3" json:"expired_period_number,omitempty"`
	ReleaseAllIfAmountIsZero bool             `protobuf:"varint,10,opt,name=release_all_if_amount_is_zero,json=releaseAllIfAmountIsZero,proto3" json:"release_all_if_amount_is_zero,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}         `json:"-"`
	XXX_unrecognized         []byte           `json:"-"`
	XXX_sizecache            int32            `json:"-"`
}

func (m *ProfitItem) Reset()         { *m = ProfitItem{} }
func (m *ProfitItem) String() string { return proto.CompactTextString(m) }
func (*ProfitItem) ProtoMessage()    {}
func (*ProfitItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{1}
}

func (m *ProfitItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfitItem.Unmarshal(m, b)
}
func (m *ProfitItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfitItem.Marshal(b, m, deterministic)
}
func (m *ProfitItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfitItem.Merge(m, src)
}
func (m *ProfitItem) XXX_Size() int {
	return xxx_messageInfo_ProfitItem.Size(m)
}
func (m *ProfitItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfitItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProfitItem proto.InternalMessageInfo

func (m *ProfitItem) GetVirtualAddress() *aelf.Address {
	if m != nil {
		return m.VirtualAddress
	}
	return nil
}

func (m *ProfitItem) GetTotalWeight() int64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *ProfitItem) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *ProfitItem) GetCurrentPeriod() int64 {
	if m != nil {
		return m.CurrentPeriod
	}
	return 0
}

func (m *ProfitItem) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

func (m *ProfitItem) GetSubProfitItems() []*SubProfitItem {
	if m != nil {
		return m.SubProfitItems
	}
	return nil
}

func (m *ProfitItem) GetCreator() *aelf.Address {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *ProfitItem) GetExpiredPeriodNumber() int64 {
	if m != nil {
		return m.ExpiredPeriodNumber
	}
	return 0
}

func (m *ProfitItem) GetReleaseAllIfAmountIsZero() bool {
	if m != nil {
		return m.ReleaseAllIfAmountIsZero
	}
	return false
}

type SubProfitItem struct {
	ProfitId             *aelf.Hash `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Weight               int64      `protobuf:"zigzag64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SubProfitItem) Reset()         { *m = SubProfitItem{} }
func (m *SubProfitItem) String() string { return proto.CompactTextString(m) }
func (*SubProfitItem) ProtoMessage()    {}
func (*SubProfitItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{2}
}

func (m *SubProfitItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubProfitItem.Unmarshal(m, b)
}
func (m *SubProfitItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubProfitItem.Marshal(b, m, deterministic)
}
func (m *SubProfitItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubProfitItem.Merge(m, src)
}
func (m *SubProfitItem) XXX_Size() int {
	return xxx_messageInfo_SubProfitItem.Size(m)
}
func (m *SubProfitItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SubProfitItem.DiscardUnknown(m)
}

var xxx_messageInfo_SubProfitItem proto.InternalMessageInfo

func (m *SubProfitItem) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *SubProfitItem) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type AddWeightInput struct {
	Receiver             *aelf.Address `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	ProfitId             *aelf.Hash    `protobuf:"bytes,2,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Weight               int64         `protobuf:"zigzag64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	EndPeriod            int64         `protobuf:"zigzag64,4,opt,name=end_period,json=endPeriod,proto3" json:"end_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddWeightInput) Reset()         { *m = AddWeightInput{} }
func (m *AddWeightInput) String() string { return proto.CompactTextString(m) }
func (*AddWeightInput) ProtoMessage()    {}
func (*AddWeightInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{3}
}

func (m *AddWeightInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWeightInput.Unmarshal(m, b)
}
func (m *AddWeightInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWeightInput.Marshal(b, m, deterministic)
}
func (m *AddWeightInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWeightInput.Merge(m, src)
}
func (m *AddWeightInput) XXX_Size() int {
	return xxx_messageInfo_AddWeightInput.Size(m)
}
func (m *AddWeightInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWeightInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddWeightInput proto.InternalMessageInfo

func (m *AddWeightInput) GetReceiver() *aelf.Address {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *AddWeightInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *AddWeightInput) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *AddWeightInput) GetEndPeriod() int64 {
	if m != nil {
		return m.EndPeriod
	}
	return 0
}

type SubWeightInput struct {
	Receiver             *aelf.Address `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	ProfitId             *aelf.Hash    `protobuf:"bytes,2,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SubWeightInput) Reset()         { *m = SubWeightInput{} }
func (m *SubWeightInput) String() string { return proto.CompactTextString(m) }
func (*SubWeightInput) ProtoMessage()    {}
func (*SubWeightInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{4}
}

func (m *SubWeightInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubWeightInput.Unmarshal(m, b)
}
func (m *SubWeightInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubWeightInput.Marshal(b, m, deterministic)
}
func (m *SubWeightInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubWeightInput.Merge(m, src)
}
func (m *SubWeightInput) XXX_Size() int {
	return xxx_messageInfo_SubWeightInput.Size(m)
}
func (m *SubWeightInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SubWeightInput.DiscardUnknown(m)
}

var xxx_messageInfo_SubWeightInput proto.InternalMessageInfo

func (m *SubWeightInput) GetReceiver() *aelf.Address {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *SubWeightInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

type AddWeightsInput struct {
	ProfitId             *aelf.Hash   `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Weights              []*WeightMap `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty"`
	EndPeriod            int64        `protobuf:"zigzag64,4,opt,name=end_period,json=endPeriod,proto3" json:"end_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddWeightsInput) Reset()         { *m = AddWeightsInput{} }
func (m *AddWeightsInput) String() string { return proto.CompactTextString(m) }
func (*AddWeightsInput) ProtoMessage()    {}
func (*AddWeightsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{5}
}

func (m *AddWeightsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWeightsInput.Unmarshal(m, b)
}
func (m *AddWeightsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWeightsInput.Marshal(b, m, deterministic)
}
func (m *AddWeightsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWeightsInput.Merge(m, src)
}
func (m *AddWeightsInput) XXX_Size() int {
	return xxx_messageInfo_AddWeightsInput.Size(m)
}
func (m *AddWeightsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWeightsInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddWeightsInput proto.InternalMessageInfo

func (m *AddWeightsInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *AddWeightsInput) GetWeights() []*WeightMap {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *AddWeightsInput) GetEndPeriod() int64 {
	if m != nil {
		return m.EndPeriod
	}
	return 0
}

type SubWeightsInput struct {
	Receivers            []*aelf.Address `protobuf:"bytes,1,rep,name=receivers,proto3" json:"receivers,omitempty"`
	ProfitId             *aelf.Hash      `protobuf:"bytes,2,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SubWeightsInput) Reset()         { *m = SubWeightsInput{} }
func (m *SubWeightsInput) String() string { return proto.CompactTextString(m) }
func (*SubWeightsInput) ProtoMessage()    {}
func (*SubWeightsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{6}
}

func (m *SubWeightsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubWeightsInput.Unmarshal(m, b)
}
func (m *SubWeightsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubWeightsInput.Marshal(b, m, deterministic)
}
func (m *SubWeightsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubWeightsInput.Merge(m, src)
}
func (m *SubWeightsInput) XXX_Size() int {
	return xxx_messageInfo_SubWeightsInput.Size(m)
}
func (m *SubWeightsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SubWeightsInput.DiscardUnknown(m)
}

var xxx_messageInfo_SubWeightsInput proto.InternalMessageInfo

func (m *SubWeightsInput) GetReceivers() []*aelf.Address {
	if m != nil {
		return m.Receivers
	}
	return nil
}

func (m *SubWeightsInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

type WeightMap struct {
	Receiver             *aelf.Address `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Weight               int64         `protobuf:"zigzag64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WeightMap) Reset()         { *m = WeightMap{} }
func (m *WeightMap) String() string { return proto.CompactTextString(m) }
func (*WeightMap) ProtoMessage()    {}
func (*WeightMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{7}
}

func (m *WeightMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightMap.Unmarshal(m, b)
}
func (m *WeightMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightMap.Marshal(b, m, deterministic)
}
func (m *WeightMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightMap.Merge(m, src)
}
func (m *WeightMap) XXX_Size() int {
	return xxx_messageInfo_WeightMap.Size(m)
}
func (m *WeightMap) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightMap.DiscardUnknown(m)
}

var xxx_messageInfo_WeightMap proto.InternalMessageInfo

func (m *WeightMap) GetReceiver() *aelf.Address {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *WeightMap) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ProfitInput struct {
	ProfitId             *aelf.Hash `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProfitInput) Reset()         { *m = ProfitInput{} }
func (m *ProfitInput) String() string { return proto.CompactTextString(m) }
func (*ProfitInput) ProtoMessage()    {}
func (*ProfitInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{8}
}

func (m *ProfitInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfitInput.Unmarshal(m, b)
}
func (m *ProfitInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfitInput.Marshal(b, m, deterministic)
}
func (m *ProfitInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfitInput.Merge(m, src)
}
func (m *ProfitInput) XXX_Size() int {
	return xxx_messageInfo_ProfitInput.Size(m)
}
func (m *ProfitInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfitInput.DiscardUnknown(m)
}

var xxx_messageInfo_ProfitInput proto.InternalMessageInfo

func (m *ProfitInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

type ReleaseProfitInput struct {
	ProfitId             *aelf.Hash `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Period               int64      `protobuf:"zigzag64,2,opt,name=period,proto3" json:"period,omitempty"`
	Amount               int64      `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TotalWeight          int64      `protobuf:"zigzag64,4,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReleaseProfitInput) Reset()         { *m = ReleaseProfitInput{} }
func (m *ReleaseProfitInput) String() string { return proto.CompactTextString(m) }
func (*ReleaseProfitInput) ProtoMessage()    {}
func (*ReleaseProfitInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{9}
}

func (m *ReleaseProfitInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseProfitInput.Unmarshal(m, b)
}
func (m *ReleaseProfitInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseProfitInput.Marshal(b, m, deterministic)
}
func (m *ReleaseProfitInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseProfitInput.Merge(m, src)
}
func (m *ReleaseProfitInput) XXX_Size() int {
	return xxx_messageInfo_ReleaseProfitInput.Size(m)
}
func (m *ReleaseProfitInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseProfitInput.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseProfitInput proto.InternalMessageInfo

func (m *ReleaseProfitInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *ReleaseProfitInput) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *ReleaseProfitInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReleaseProfitInput) GetTotalWeight() int64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

type ProfitDetails struct {
	Details              []*ProfitDetail `protobuf:"bytes,1,rep,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProfitDetails) Reset()         { *m = ProfitDetails{} }
func (m *ProfitDetails) String() string { return proto.CompactTextString(m) }
func (*ProfitDetails) ProtoMessage()    {}
func (*ProfitDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{10}
}

func (m *ProfitDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfitDetails.Unmarshal(m, b)
}
func (m *ProfitDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfitDetails.Marshal(b, m, deterministic)
}
func (m *ProfitDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfitDetails.Merge(m, src)
}
func (m *ProfitDetails) XXX_Size() int {
	return xxx_messageInfo_ProfitDetails.Size(m)
}
func (m *ProfitDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfitDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ProfitDetails proto.InternalMessageInfo

func (m *ProfitDetails) GetDetails() []*ProfitDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type ProfitDetail struct {
	StartPeriod          int64    `protobuf:"zigzag64,1,opt,name=start_period,json=startPeriod,proto3" json:"start_period,omitempty"`
	EndPeriod            int64    `protobuf:"zigzag64,2,opt,name=end_period,json=endPeriod,proto3" json:"end_period,omitempty"`
	Weight               int64    `protobuf:"zigzag64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	LastProfitPeriod     int64    `protobuf:"zigzag64,4,opt,name=last_profit_period,json=lastProfitPeriod,proto3" json:"last_profit_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfitDetail) Reset()         { *m = ProfitDetail{} }
func (m *ProfitDetail) String() string { return proto.CompactTextString(m) }
func (*ProfitDetail) ProtoMessage()    {}
func (*ProfitDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{11}
}

func (m *ProfitDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfitDetail.Unmarshal(m, b)
}
func (m *ProfitDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfitDetail.Marshal(b, m, deterministic)
}
func (m *ProfitDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfitDetail.Merge(m, src)
}
func (m *ProfitDetail) XXX_Size() int {
	return xxx_messageInfo_ProfitDetail.Size(m)
}
func (m *ProfitDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfitDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ProfitDetail proto.InternalMessageInfo

func (m *ProfitDetail) GetStartPeriod() int64 {
	if m != nil {
		return m.StartPeriod
	}
	return 0
}

func (m *ProfitDetail) GetEndPeriod() int64 {
	if m != nil {
		return m.EndPeriod
	}
	return 0
}

func (m *ProfitDetail) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ProfitDetail) GetLastProfitPeriod() int64 {
	if m != nil {
		return m.LastProfitPeriod
	}
	return 0
}

type AddProfitsInput struct {
	ProfitId             *aelf.Hash `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Amount               int64      `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Period               int64      `protobuf:"zigzag64,3,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddProfitsInput) Reset()         { *m = AddProfitsInput{} }
func (m *AddProfitsInput) String() string { return proto.CompactTextString(m) }
func (*AddProfitsInput) ProtoMessage()    {}
func (*AddProfitsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{12}
}

func (m *AddProfitsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProfitsInput.Unmarshal(m, b)
}
func (m *AddProfitsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProfitsInput.Marshal(b, m, deterministic)
}
func (m *AddProfitsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProfitsInput.Merge(m, src)
}
func (m *AddProfitsInput) XXX_Size() int {
	return xxx_messageInfo_AddProfitsInput.Size(m)
}
func (m *AddProfitsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProfitsInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddProfitsInput proto.InternalMessageInfo

func (m *AddProfitsInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *AddProfitsInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AddProfitsInput) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

type RegisterSubProfitItemInput struct {
	ProfitId             *aelf.Hash `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	SubProfitId          *aelf.Hash `protobuf:"bytes,2,opt,name=sub_profit_id,json=subProfitId,proto3" json:"sub_profit_id,omitempty"`
	SubItemWeight        int64      `protobuf:"zigzag64,3,opt,name=sub_item_weight,json=subItemWeight,proto3" json:"sub_item_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterSubProfitItemInput) Reset()         { *m = RegisterSubProfitItemInput{} }
func (m *RegisterSubProfitItemInput) String() string { return proto.CompactTextString(m) }
func (*RegisterSubProfitItemInput) ProtoMessage()    {}
func (*RegisterSubProfitItemInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{13}
}

func (m *RegisterSubProfitItemInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSubProfitItemInput.Unmarshal(m, b)
}
func (m *RegisterSubProfitItemInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSubProfitItemInput.Marshal(b, m, deterministic)
}
func (m *RegisterSubProfitItemInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSubProfitItemInput.Merge(m, src)
}
func (m *RegisterSubProfitItemInput) XXX_Size() int {
	return xxx_messageInfo_RegisterSubProfitItemInput.Size(m)
}
func (m *RegisterSubProfitItemInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSubProfitItemInput.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSubProfitItemInput proto.InternalMessageInfo

func (m *RegisterSubProfitItemInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *RegisterSubProfitItemInput) GetSubProfitId() *aelf.Hash {
	if m != nil {
		return m.SubProfitId
	}
	return nil
}

func (m *RegisterSubProfitItemInput) GetSubItemWeight() int64 {
	if m != nil {
		return m.SubItemWeight
	}
	return 0
}

type CancelSubProfitItemInput struct {
	ItemName             string        `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	SubItemName          string        `protobuf:"bytes,2,opt,name=sub_item_name,json=subItemName,proto3" json:"sub_item_name,omitempty"`
	SubItemCreator       *aelf.Address `protobuf:"bytes,3,opt,name=sub_item_creator,json=subItemCreator,proto3" json:"sub_item_creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CancelSubProfitItemInput) Reset()         { *m = CancelSubProfitItemInput{} }
func (m *CancelSubProfitItemInput) String() string { return proto.CompactTextString(m) }
func (*CancelSubProfitItemInput) ProtoMessage()    {}
func (*CancelSubProfitItemInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{14}
}

func (m *CancelSubProfitItemInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelSubProfitItemInput.Unmarshal(m, b)
}
func (m *CancelSubProfitItemInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelSubProfitItemInput.Marshal(b, m, deterministic)
}
func (m *CancelSubProfitItemInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelSubProfitItemInput.Merge(m, src)
}
func (m *CancelSubProfitItemInput) XXX_Size() int {
	return xxx_messageInfo_CancelSubProfitItemInput.Size(m)
}
func (m *CancelSubProfitItemInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelSubProfitItemInput.DiscardUnknown(m)
}

var xxx_messageInfo_CancelSubProfitItemInput proto.InternalMessageInfo

func (m *CancelSubProfitItemInput) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *CancelSubProfitItemInput) GetSubItemName() string {
	if m != nil {
		return m.SubItemName
	}
	return ""
}

func (m *CancelSubProfitItemInput) GetSubItemCreator() *aelf.Address {
	if m != nil {
		return m.SubItemCreator
	}
	return nil
}

type ReleasedProfitsInformation struct {
	TotalWeight          int64    `protobuf:"zigzag64,1,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	ProfitsAmount        int64    `protobuf:"zigzag64,2,opt,name=profits_amount,json=profitsAmount,proto3" json:"profits_amount,omitempty"`
	IsReleased           bool     `protobuf:"varint,3,opt,name=is_released,json=isReleased,proto3" json:"is_released,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleasedProfitsInformation) Reset()         { *m = ReleasedProfitsInformation{} }
func (m *ReleasedProfitsInformation) String() string { return proto.CompactTextString(m) }
func (*ReleasedProfitsInformation) ProtoMessage()    {}
func (*ReleasedProfitsInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{15}
}

func (m *ReleasedProfitsInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasedProfitsInformation.Unmarshal(m, b)
}
func (m *ReleasedProfitsInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasedProfitsInformation.Marshal(b, m, deterministic)
}
func (m *ReleasedProfitsInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasedProfitsInformation.Merge(m, src)
}
func (m *ReleasedProfitsInformation) XXX_Size() int {
	return xxx_messageInfo_ReleasedProfitsInformation.Size(m)
}
func (m *ReleasedProfitsInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasedProfitsInformation.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasedProfitsInformation proto.InternalMessageInfo

func (m *ReleasedProfitsInformation) GetTotalWeight() int64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *ReleasedProfitsInformation) GetProfitsAmount() int64 {
	if m != nil {
		return m.ProfitsAmount
	}
	return 0
}

func (m *ReleasedProfitsInformation) GetIsReleased() bool {
	if m != nil {
		return m.IsReleased
	}
	return false
}

type CreatedProfitItems struct {
	ProfitIds            []*aelf.Hash `protobuf:"bytes,1,rep,name=ProfitIds,proto3" json:"ProfitIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatedProfitItems) Reset()         { *m = CreatedProfitItems{} }
func (m *CreatedProfitItems) String() string { return proto.CompactTextString(m) }
func (*CreatedProfitItems) ProtoMessage()    {}
func (*CreatedProfitItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{16}
}

func (m *CreatedProfitItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedProfitItems.Unmarshal(m, b)
}
func (m *CreatedProfitItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedProfitItems.Marshal(b, m, deterministic)
}
func (m *CreatedProfitItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedProfitItems.Merge(m, src)
}
func (m *CreatedProfitItems) XXX_Size() int {
	return xxx_messageInfo_CreatedProfitItems.Size(m)
}
func (m *CreatedProfitItems) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedProfitItems.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedProfitItems proto.InternalMessageInfo

func (m *CreatedProfitItems) GetProfitIds() []*aelf.Hash {
	if m != nil {
		return m.ProfitIds
	}
	return nil
}

type GetCreatedProfitItemsInput struct {
	Creator              *aelf.Address `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCreatedProfitItemsInput) Reset()         { *m = GetCreatedProfitItemsInput{} }
func (m *GetCreatedProfitItemsInput) String() string { return proto.CompactTextString(m) }
func (*GetCreatedProfitItemsInput) ProtoMessage()    {}
func (*GetCreatedProfitItemsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{17}
}

func (m *GetCreatedProfitItemsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCreatedProfitItemsInput.Unmarshal(m, b)
}
func (m *GetCreatedProfitItemsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCreatedProfitItemsInput.Marshal(b, m, deterministic)
}
func (m *GetCreatedProfitItemsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCreatedProfitItemsInput.Merge(m, src)
}
func (m *GetCreatedProfitItemsInput) XXX_Size() int {
	return xxx_messageInfo_GetCreatedProfitItemsInput.Size(m)
}
func (m *GetCreatedProfitItemsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCreatedProfitItemsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetCreatedProfitItemsInput proto.InternalMessageInfo

func (m *GetCreatedProfitItemsInput) GetCreator() *aelf.Address {
	if m != nil {
		return m.Creator
	}
	return nil
}

type GetProfitItemVirtualAddressInput struct {
	ProfitId             *aelf.Hash `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Period               int64      `protobuf:"zigzag64,2,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProfitItemVirtualAddressInput) Reset()         { *m = GetProfitItemVirtualAddressInput{} }
func (m *GetProfitItemVirtualAddressInput) String() string { return proto.CompactTextString(m) }
func (*GetProfitItemVirtualAddressInput) ProtoMessage()    {}
func (*GetProfitItemVirtualAddressInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{18}
}

func (m *GetProfitItemVirtualAddressInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfitItemVirtualAddressInput.Unmarshal(m, b)
}
func (m *GetProfitItemVirtualAddressInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfitItemVirtualAddressInput.Marshal(b, m, deterministic)
}
func (m *GetProfitItemVirtualAddressInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfitItemVirtualAddressInput.Merge(m, src)
}
func (m *GetProfitItemVirtualAddressInput) XXX_Size() int {
	return xxx_messageInfo_GetProfitItemVirtualAddressInput.Size(m)
}
func (m *GetProfitItemVirtualAddressInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfitItemVirtualAddressInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfitItemVirtualAddressInput proto.InternalMessageInfo

func (m *GetProfitItemVirtualAddressInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *GetProfitItemVirtualAddressInput) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

type GetReleasedProfitsInformationInput struct {
	ProfitId             *aelf.Hash `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Period               int64      `protobuf:"zigzag64,2,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetReleasedProfitsInformationInput) Reset()         { *m = GetReleasedProfitsInformationInput{} }
func (m *GetReleasedProfitsInformationInput) String() string { return proto.CompactTextString(m) }
func (*GetReleasedProfitsInformationInput) ProtoMessage()    {}
func (*GetReleasedProfitsInformationInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{19}
}

func (m *GetReleasedProfitsInformationInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReleasedProfitsInformationInput.Unmarshal(m, b)
}
func (m *GetReleasedProfitsInformationInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReleasedProfitsInformationInput.Marshal(b, m, deterministic)
}
func (m *GetReleasedProfitsInformationInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReleasedProfitsInformationInput.Merge(m, src)
}
func (m *GetReleasedProfitsInformationInput) XXX_Size() int {
	return xxx_messageInfo_GetReleasedProfitsInformationInput.Size(m)
}
func (m *GetReleasedProfitsInformationInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReleasedProfitsInformationInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetReleasedProfitsInformationInput proto.InternalMessageInfo

func (m *GetReleasedProfitsInformationInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *GetReleasedProfitsInformationInput) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

type GetProfitDetailsInput struct {
	ProfitId             *aelf.Hash    `protobuf:"bytes,1,opt,name=profit_id,json=profitId,proto3" json:"profit_id,omitempty"`
	Receiver             *aelf.Address `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetProfitDetailsInput) Reset()         { *m = GetProfitDetailsInput{} }
func (m *GetProfitDetailsInput) String() string { return proto.CompactTextString(m) }
func (*GetProfitDetailsInput) ProtoMessage()    {}
func (*GetProfitDetailsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc8b2e678e8c7258, []int{20}
}

func (m *GetProfitDetailsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfitDetailsInput.Unmarshal(m, b)
}
func (m *GetProfitDetailsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfitDetailsInput.Marshal(b, m, deterministic)
}
func (m *GetProfitDetailsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfitDetailsInput.Merge(m, src)
}
func (m *GetProfitDetailsInput) XXX_Size() int {
	return xxx_messageInfo_GetProfitDetailsInput.Size(m)
}
func (m *GetProfitDetailsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfitDetailsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfitDetailsInput proto.InternalMessageInfo

func (m *GetProfitDetailsInput) GetProfitId() *aelf.Hash {
	if m != nil {
		return m.ProfitId
	}
	return nil
}

func (m *GetProfitDetailsInput) GetReceiver() *aelf.Address {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProfitItemInput)(nil), "profit.CreateProfitItemInput")
	proto.RegisterType((*ProfitItem)(nil), "profit.ProfitItem")
	proto.RegisterType((*SubProfitItem)(nil), "profit.SubProfitItem")
	proto.RegisterType((*AddWeightInput)(nil), "profit.AddWeightInput")
	proto.RegisterType((*SubWeightInput)(nil), "profit.SubWeightInput")
	proto.RegisterType((*AddWeightsInput)(nil), "profit.AddWeightsInput")
	proto.RegisterType((*SubWeightsInput)(nil), "profit.SubWeightsInput")
	proto.RegisterType((*WeightMap)(nil), "profit.WeightMap")
	proto.RegisterType((*ProfitInput)(nil), "profit.ProfitInput")
	proto.RegisterType((*ReleaseProfitInput)(nil), "profit.ReleaseProfitInput")
	proto.RegisterType((*ProfitDetails)(nil), "profit.ProfitDetails")
	proto.RegisterType((*ProfitDetail)(nil), "profit.ProfitDetail")
	proto.RegisterType((*AddProfitsInput)(nil), "profit.AddProfitsInput")
	proto.RegisterType((*RegisterSubProfitItemInput)(nil), "profit.RegisterSubProfitItemInput")
	proto.RegisterType((*CancelSubProfitItemInput)(nil), "profit.CancelSubProfitItemInput")
	proto.RegisterType((*ReleasedProfitsInformation)(nil), "profit.ReleasedProfitsInformation")
	proto.RegisterType((*CreatedProfitItems)(nil), "profit.CreatedProfitItems")
	proto.RegisterType((*GetCreatedProfitItemsInput)(nil), "profit.GetCreatedProfitItemsInput")
	proto.RegisterType((*GetProfitItemVirtualAddressInput)(nil), "profit.GetProfitItemVirtualAddressInput")
	proto.RegisterType((*GetReleasedProfitsInformationInput)(nil), "profit.GetReleasedProfitsInformationInput")
	proto.RegisterType((*GetProfitDetailsInput)(nil), "profit.GetProfitDetailsInput")
}

func init() { proto.RegisterFile("profit_contract.proto", fileDescriptor_bc8b2e678e8c7258) }

var fileDescriptor_bc8b2e678e8c7258 = []byte{
	// 1219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0xe3, 0x54,
	0x10, 0x5f, 0x27, 0xbb, 0x6d, 0x3c, 0xd9, 0x24, 0xdd, 0x57, 0x52, 0x2c, 0x57, 0x15, 0xc1, 0xd2,
	0xb2, 0x59, 0x16, 0xb9, 0x52, 0x41, 0xdd, 0xd3, 0x52, 0x4a, 0xa9, 0x4a, 0x24, 0x28, 0xc5, 0x15,
	0x8b, 0x84, 0x04, 0x96, 0x13, 0xbf, 0x74, 0x4d, 0x1d, 0x3b, 0xf2, 0x7b, 0x29, 0xec, 0x7e, 0x00,
	0xfe, 0xdc, 0x38, 0x20, 0x2e, 0x88, 0x2f, 0xc0, 0x11, 0xae, 0x7c, 0x04, 0x4e, 0x7c, 0x18, 0xb8,
	0x22, 0xbf, 0x3f, 0xb6, 0x5f, 0xe2, 0xb8, 0x2d, 0xec, 0xde, 0xe2, 0x99, 0x79, 0xf3, 0xe7, 0x37,
	0x93, 0xdf, 0x0c, 0x74, 0xa7, 0x49, 0x3c, 0x0e, 0xa8, 0x3b, 0x8a, 0x23, 0x9a, 0x78, 0x23, 0x6a,
	0x4f, 0x93, 0x98, 0xc6, 0x68, 0x85, 0x8b, 0xcd, 0x8e, 0x87, 0xc3, 0xf1, 0xf6, 0x28, 0x4e, 0x30,
	0x57, 0x98, 0x88, 0x09, 0xe2, 0x29, 0x0d, 0xe2, 0x88, 0x08, 0xd9, 0xe6, 0x59, 0x1c, 0x9f, 0x85,
	0x78, 0x9b, 0x7d, 0x0d, 0x67, 0xe3, 0x6d, 0x3c, 0x99, 0xd2, 0xa7, 0x5c, 0x69, 0xfd, 0xa5, 0x41,
	0xf7, 0x20, 0xc1, 0x1e, 0xc5, 0x27, 0xcc, 0xe5, 0x80, 0xe2, 0xc9, 0x20, 0x9a, 0xce, 0x28, 0x7a,
	0x15, 0x6e, 0xd3, 0x98, 0x7a, 0xa1, 0xfb, 0x15, 0x0e, 0xce, 0x9e, 0x50, 0x43, 0xeb, 0x69, 0x7d,
	0xe4, 0x34, 0x99, 0xec, 0x53, 0x26, 0xe2, 0x26, 0xe7, 0x38, 0x72, 0xc9, 0xd3, 0xc9, 0x30, 0x0e,
	0x8d, 0x5a, 0x4f, 0xeb, 0xeb, 0xa9, 0xc9, 0x39, 0x8e, 0x4e, 0x99, 0x08, 0xed, 0x40, 0x17, 0x7f,
	0x3d, 0x0d, 0x12, 0xec, 0xbb, 0x53, 0x9c, 0x04, 0xb1, 0xef, 0x46, 0xb3, 0xc9, 0x10, 0x27, 0x46,
	0x9d, 0xb9, 0x5b, 0x17, 0xca, 0x13, 0xa6, 0x3b, 0x66, 0x2a, 0xb4, 0x07, 0x5b, 0x09, 0x0e, 0xb1,
	0x47, 0xb0, 0xeb, 0x85, 0xa1, 0x1b, 0x8c, 0x5d, 0x6f, 0x12, 0xcf, 0x22, 0xea, 0x06, 0xc4, 0x7d,
	0x86, 0x93, 0xd8, 0xb8, 0xd9, 0xd3, 0xfa, 0x0d, 0xc7, 0x10, 0x46, 0xfb, 0x61, 0x38, 0x18, 0xef,
	0x33, 0x8b, 0x01, 0xf9, 0x0c, 0x27, 0xb1, 0xf5, 0x7b, 0x1d, 0x20, 0x2f, 0x07, 0xed, 0x42, 0xe7,
	0x22, 0x48, 0xe8, 0xcc, 0x0b, 0x5d, 0xcf, 0xf7, 0x13, 0x4c, 0x08, 0x2b, 0xa6, 0xb9, 0xd3, 0xb2,
	0x53, 0xb8, 0xec, 0x7d, 0x2e, 0x74, 0xda, 0xc2, 0x4a, 0x7c, 0x2f, 0x20, 0x50, 0x5b, 0x82, 0x40,
	0x6a, 0xc2, 0x33, 0x14, 0x55, 0x71, 0x13, 0x9e, 0x12, 0xba, 0x0b, 0xed, 0xd1, 0x2c, 0x49, 0x70,
	0x44, 0x05, 0x02, 0x2c, 0x7d, 0xe4, 0xb4, 0x84, 0x94, 0x97, 0xbe, 0x80, 0xe5, 0xad, 0x45, 0x2c,
	0xf7, 0x60, 0x8d, 0xcc, 0x86, 0xae, 0x18, 0x89, 0x80, 0xe2, 0x09, 0x31, 0x56, 0x7b, 0xf5, 0x7e,
	0x73, 0xa7, 0x6b, 0x73, 0xa1, 0x7d, 0x3a, 0x1b, 0xe6, 0x85, 0x3b, 0x6d, 0x52, 0xfc, 0x24, 0xe8,
	0x1e, 0xac, 0x8e, 0xd2, 0x5e, 0xc7, 0x89, 0xd1, 0x28, 0x03, 0x40, 0x6a, 0x97, 0x77, 0x4d, 0xff,
	0x1f, 0x5d, 0x83, 0x4b, 0xba, 0x76, 0x02, 0x2d, 0x25, 0x7d, 0x74, 0x0f, 0x74, 0x59, 0xab, 0x2f,
	0x3a, 0x06, 0x3c, 0xe1, 0xf7, 0x3d, 0xf2, 0xc4, 0x69, 0x70, 0xe5, 0xc0, 0x47, 0x1b, 0xb0, 0xa2,
	0xb4, 0x48, 0x7c, 0x59, 0x3f, 0x6b, 0xd0, 0xde, 0xf7, 0x7d, 0xde, 0x2b, 0x3e, 0xd5, 0xf7, 0xa1,
	0x91, 0xe0, 0x11, 0x0e, 0x2e, 0x70, 0x52, 0x3e, 0x04, 0x99, 0x5a, 0x0d, 0x5f, 0xbb, 0x52, 0xf8,
	0x7a, 0x31, 0x3c, 0xda, 0x02, 0xc0, 0x91, 0xaf, 0x76, 0x5d, 0xc7, 0x91, 0x80, 0xcd, 0xf2, 0xa1,
	0x7d, 0x3a, 0x1b, 0xbe, 0xe0, 0xe4, 0xac, 0x6f, 0x34, 0xe8, 0x64, 0x18, 0x10, 0x1e, 0xe7, 0xca,
	0xc0, 0x3e, 0x80, 0x55, 0x5e, 0x0b, 0x31, 0x6a, 0x6c, 0xd0, 0xee, 0xc8, 0x41, 0xe3, 0xfe, 0x3e,
	0xf4, 0xa6, 0x8e, 0xb4, 0xb8, 0xac, 0xdc, 0x33, 0xe8, 0x64, 0xe5, 0x8a, 0x3c, 0x1e, 0x80, 0x2e,
	0x0b, 0x4a, 0xff, 0x92, 0xf5, 0xc5, 0x82, 0x73, 0xfd, 0xd5, 0x2b, 0x3e, 0x06, 0x3d, 0xcb, 0xee,
	0x3a, 0x90, 0x2e, 0x9b, 0xa2, 0x5d, 0x68, 0x8a, 0xa1, 0xbc, 0x16, 0x78, 0xd6, 0x0f, 0x1a, 0x20,
	0x87, 0x0f, 0xfb, 0x7f, 0x79, 0x9f, 0xe6, 0x23, 0xb0, 0x14, 0xf9, 0xf0, 0xaf, 0x54, 0xae, 0xb0,
	0x8d, 0xf8, 0x5a, 0xa0, 0xab, 0x9b, 0x0b, 0x74, 0x65, 0xed, 0x41, 0x8b, 0xa7, 0xf2, 0x1e, 0xa6,
	0x5e, 0x10, 0x12, 0x64, 0xc3, 0xaa, 0xf8, 0x29, 0xf0, 0x7f, 0x49, 0x36, 0xb8, 0x68, 0xe7, 0x48,
	0x23, 0xeb, 0x27, 0x0d, 0x6e, 0x17, 0x35, 0x69, 0x50, 0x42, 0xbd, 0x24, 0xe3, 0x36, 0xb1, 0x25,
	0x98, 0x4c, 0x30, 0x9b, 0x3a, 0x17, 0xb5, 0xb9, 0xb9, 0x58, 0xfa, 0xef, 0x79, 0x03, 0x50, 0xe8,
	0x11, 0x2a, 0xe9, 0x4e, 0x19, 0xab, 0xb5, 0x54, 0xc3, 0xf3, 0x10, 0xd3, 0xf5, 0x25, 0x9b, 0x72,
	0x2e, 0x22, 0xd7, 0x07, 0x5a, 0x00, 0x5a, 0x53, 0x00, 0xcd, 0x1b, 0x50, 0x2f, 0x36, 0xc0, 0xfa,
	0x45, 0x03, 0xd3, 0xc1, 0x67, 0x01, 0xa1, 0x38, 0x51, 0x18, 0xeb, 0x9a, 0x71, 0x6d, 0x68, 0x15,
	0xf9, 0xbc, 0x6c, 0xaa, 0x9b, 0x39, 0x83, 0xfb, 0xe8, 0x35, 0xe8, 0xa4, 0xf6, 0x29, 0xf1, 0xbb,
	0x0a, 0x64, 0xa9, 0x9b, 0x34, 0xbe, 0xe8, 0xf2, 0x8f, 0x1a, 0x18, 0x07, 0x5e, 0x34, 0xc2, 0x61,
	0x49, 0x76, 0x9b, 0xa0, 0x33, 0x07, 0x91, 0x37, 0xc1, 0x2c, 0x3b, 0xdd, 0x69, 0xa4, 0x82, 0x63,
	0x6f, 0x82, 0x91, 0xc5, 0x33, 0xca, 0x0d, 0xc4, 0x46, 0x17, 0xfe, 0x99, 0xcd, 0x43, 0xbe, 0x85,
	0x98, 0x8d, 0xdc, 0x26, 0xf5, 0xd2, 0x75, 0x2a, 0x5e, 0x1d, 0x70, 0x23, 0xeb, 0x5b, 0x06, 0x1b,
	0xfb, 0x3f, 0xe4, 0x8d, 0x1a, 0xc7, 0xc9, 0xc4, 0x4b, 0xaf, 0x95, 0xab, 0xdc, 0x1b, 0x77, 0xa1,
	0xcd, 0xc1, 0x22, 0xae, 0xd2, 0xb0, 0x96, 0x90, 0x8a, 0x8d, 0xfb, 0x0a, 0x34, 0x03, 0xe2, 0x8a,
	0x3d, 0xc3, 0x9b, 0xd7, 0x70, 0x20, 0x20, 0x32, 0xb8, 0xf5, 0x36, 0x20, 0x7e, 0xf3, 0xf8, 0xc5,
	0xed, 0xd8, 0x07, 0x5d, 0x42, 0x2d, 0xff, 0x0d, 0xc5, 0x56, 0xe4, 0x4a, 0xeb, 0x10, 0xcc, 0x23,
	0x4c, 0x17, 0x5d, 0xc8, 0xfe, 0x67, 0x5b, 0x56, 0xab, 0xda, 0xb2, 0xd6, 0x08, 0x7a, 0x47, 0x98,
	0xe6, 0xef, 0x1f, 0x2b, 0xe7, 0xc7, 0xf3, 0x61, 0x0b, 0x0b, 0x83, 0x75, 0x84, 0xe9, 0x72, 0xdc,
	0x9f, 0x53, 0x98, 0x73, 0xe8, 0x66, 0xb5, 0x08, 0xb2, 0xb8, 0xa6, 0xe7, 0x22, 0x53, 0xd7, 0x2a,
	0x99, 0x7a, 0xe7, 0x0f, 0x80, 0x36, 0x0f, 0x75, 0x20, 0xee, 0x62, 0xf4, 0x01, 0x18, 0x83, 0x28,
	0xa0, 0x81, 0x17, 0x06, 0xcf, 0xf0, 0x9c, 0x6e, 0xc3, 0xe6, 0x17, 0xb0, 0x2d, 0x2f, 0x60, 0xfb,
	0x30, 0xbd, 0x80, 0xcd, 0x25, 0x72, 0xeb, 0x46, 0x7a, 0x69, 0xcd, 0x1f, 0xc5, 0x68, 0x4b, 0x32,
	0x63, 0xe9, 0xb9, 0x6c, 0x16, 0x8a, 0xb2, 0x6e, 0xa0, 0x47, 0xa0, 0x67, 0x4b, 0x17, 0x6d, 0xc8,
	0x97, 0xea, 0x2d, 0x52, 0x11, 0xff, 0x11, 0xe8, 0xd9, 0xae, 0xcc, 0x9f, 0xab, 0xd7, 0x42, 0x65,
	0xfa, 0x90, 0xaf, 0x7c, 0xf4, 0xf2, 0x42, 0x78, 0x72, 0x05, 0x07, 0xf9, 0xae, 0xce, 0x1d, 0xcc,
	0xed, 0xef, 0x4b, 0x33, 0x10, 0xd3, 0xa6, 0x64, 0x50, 0xa4, 0xe8, 0x0a, 0x07, 0x0f, 0x61, 0x85,
	0x5b, 0xa2, 0x75, 0x75, 0x23, 0x5d, 0xf6, 0xf0, 0x10, 0x5a, 0xca, 0xd2, 0x45, 0xa6, 0x7c, 0xbf,
	0xb8, 0x8b, 0x2b, 0xdc, 0x7c, 0x02, 0xdd, 0x52, 0x8a, 0x47, 0x56, 0xee, 0x6e, 0xd9, 0x06, 0xa8,
	0x70, 0xfb, 0x31, 0xac, 0x97, 0x30, 0x33, 0xea, 0x65, 0xb3, 0xb5, 0x84, 0xb6, 0x2b, 0x5c, 0x7e,
	0xc1, 0xfe, 0x79, 0x25, 0x7c, 0x96, 0x65, 0xba, 0x9c, 0xab, 0x4c, 0x53, 0x1d, 0xea, 0xa2, 0x81,
	0x75, 0xeb, 0xbb, 0xef, 0xff, 0xd1, 0x34, 0xb4, 0x0b, 0x2d, 0x85, 0xa5, 0x50, 0x61, 0xd2, 0x4d,
	0x34, 0xd7, 0x1c, 0x8a, 0x27, 0xf2, 0xdd, 0xe7, 0xb0, 0x59, 0xc1, 0x6e, 0xa8, 0x5f, 0xc8, 0xae,
	0x92, 0x02, 0x4d, 0x95, 0x06, 0xa4, 0xfb, 0x0b, 0xd8, 0xaa, 0xe4, 0x35, 0xf4, 0x7a, 0x21, 0xc0,
	0x25, 0xf4, 0x67, 0x5a, 0x73, 0x33, 0x52, 0x62, 0x28, 0xe3, 0x7e, 0x04, 0x6b, 0xf3, 0x44, 0x97,
	0x53, 0x43, 0x29, 0x05, 0x9a, 0xdd, 0xb2, 0x9b, 0x2a, 0x2b, 0xe4, 0x1d, 0xe8, 0x64, 0xcf, 0xc4,
	0x02, 0x2b, 0x1d, 0xf9, 0x3b, 0x1c, 0x86, 0xd3, 0x41, 0x44, 0x77, 0xdf, 0x7a, 0xec, 0x85, 0x33,
	0x2c, 0x3c, 0x98, 0xf6, 0x6f, 0x7f, 0xfe, 0xad, 0xdd, 0xdf, 0x3f, 0x0c, 0xc7, 0xb6, 0xe4, 0x3c,
	0x22, 0x9e, 0xda, 0x2a, 0x15, 0x9e, 0x52, 0x8f, 0xe2, 0x77, 0x8d, 0x5f, 0x6b, 0xdd, 0x52, 0xeb,
	0xe1, 0x0a, 0x9b, 0xae, 0x37, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x86, 0x0d, 0xc8, 0x83, 0x77,
	0x10, 0x00, 0x00,
}
