// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token_converter_contract.proto

package token_converter_contract

import (
	aelf "aelf"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Connector struct {
	Symbol                  string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	VirtualBalance          int64    `protobuf:"zigzag64,2,opt,name=virtual_balance,json=virtualBalance,proto3" json:"virtual_balance,omitempty"`
	Weight                  string   `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
	IsVirtualBalanceEnabled bool     `protobuf:"varint,4,opt,name=is_virtual_balance_enabled,json=isVirtualBalanceEnabled,proto3" json:"is_virtual_balance_enabled,omitempty"`
	IsPurchaseEnabled       bool     `protobuf:"varint,5,opt,name=is_purchase_enabled,json=isPurchaseEnabled,proto3" json:"is_purchase_enabled,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Connector) Reset()         { *m = Connector{} }
func (m *Connector) String() string { return proto.CompactTextString(m) }
func (*Connector) ProtoMessage()    {}
func (*Connector) Descriptor() ([]byte, []int) {
	return fileDescriptor_adbbaf6824dfdbb6, []int{0}
}

func (m *Connector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connector.Unmarshal(m, b)
}
func (m *Connector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connector.Marshal(b, m, deterministic)
}
func (m *Connector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connector.Merge(m, src)
}
func (m *Connector) XXX_Size() int {
	return xxx_messageInfo_Connector.Size(m)
}
func (m *Connector) XXX_DiscardUnknown() {
	xxx_messageInfo_Connector.DiscardUnknown(m)
}

var xxx_messageInfo_Connector proto.InternalMessageInfo

func (m *Connector) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Connector) GetVirtualBalance() int64 {
	if m != nil {
		return m.VirtualBalance
	}
	return 0
}

func (m *Connector) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *Connector) GetIsVirtualBalanceEnabled() bool {
	if m != nil {
		return m.IsVirtualBalanceEnabled
	}
	return false
}

func (m *Connector) GetIsPurchaseEnabled() bool {
	if m != nil {
		return m.IsPurchaseEnabled
	}
	return false
}

type TokenSymbol struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenSymbol) Reset()         { *m = TokenSymbol{} }
func (m *TokenSymbol) String() string { return proto.CompactTextString(m) }
func (*TokenSymbol) ProtoMessage()    {}
func (*TokenSymbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_adbbaf6824dfdbb6, []int{1}
}

func (m *TokenSymbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenSymbol.Unmarshal(m, b)
}
func (m *TokenSymbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenSymbol.Marshal(b, m, deterministic)
}
func (m *TokenSymbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenSymbol.Merge(m, src)
}
func (m *TokenSymbol) XXX_Size() int {
	return xxx_messageInfo_TokenSymbol.Size(m)
}
func (m *TokenSymbol) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenSymbol.DiscardUnknown(m)
}

var xxx_messageInfo_TokenSymbol proto.InternalMessageInfo

func (m *TokenSymbol) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type InitializeInput struct {
	BaseTokenSymbol      string        `protobuf:"bytes,1,opt,name=base_token_symbol,json=baseTokenSymbol,proto3" json:"base_token_symbol,omitempty"`
	FeeRate              string        `protobuf:"bytes,2,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	Connectors           []*Connector  `protobuf:"bytes,3,rep,name=connectors,proto3" json:"connectors,omitempty"`
	TokenContractAddress *aelf.Address `protobuf:"bytes,4,opt,name=token_contract_address,json=tokenContractAddress,proto3" json:"token_contract_address,omitempty"`
	FeeReceiverAddress   *aelf.Address `protobuf:"bytes,5,opt,name=fee_receiver_address,json=feeReceiverAddress,proto3" json:"fee_receiver_address,omitempty"`
	ManagerAddress       *aelf.Address `protobuf:"bytes,6,opt,name=manager_address,json=managerAddress,proto3" json:"manager_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InitializeInput) Reset()         { *m = InitializeInput{} }
func (m *InitializeInput) String() string { return proto.CompactTextString(m) }
func (*InitializeInput) ProtoMessage()    {}
func (*InitializeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_adbbaf6824dfdbb6, []int{2}
}

func (m *InitializeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeInput.Unmarshal(m, b)
}
func (m *InitializeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeInput.Marshal(b, m, deterministic)
}
func (m *InitializeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeInput.Merge(m, src)
}
func (m *InitializeInput) XXX_Size() int {
	return xxx_messageInfo_InitializeInput.Size(m)
}
func (m *InitializeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeInput.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeInput proto.InternalMessageInfo

func (m *InitializeInput) GetBaseTokenSymbol() string {
	if m != nil {
		return m.BaseTokenSymbol
	}
	return ""
}

func (m *InitializeInput) GetFeeRate() string {
	if m != nil {
		return m.FeeRate
	}
	return ""
}

func (m *InitializeInput) GetConnectors() []*Connector {
	if m != nil {
		return m.Connectors
	}
	return nil
}

func (m *InitializeInput) GetTokenContractAddress() *aelf.Address {
	if m != nil {
		return m.TokenContractAddress
	}
	return nil
}

func (m *InitializeInput) GetFeeReceiverAddress() *aelf.Address {
	if m != nil {
		return m.FeeReceiverAddress
	}
	return nil
}

func (m *InitializeInput) GetManagerAddress() *aelf.Address {
	if m != nil {
		return m.ManagerAddress
	}
	return nil
}

type BuyInput struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64    `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PayLimit             int64    `protobuf:"zigzag64,3,opt,name=pay_limit,json=payLimit,proto3" json:"pay_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyInput) Reset()         { *m = BuyInput{} }
func (m *BuyInput) String() string { return proto.CompactTextString(m) }
func (*BuyInput) ProtoMessage()    {}
func (*BuyInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_adbbaf6824dfdbb6, []int{3}
}

func (m *BuyInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyInput.Unmarshal(m, b)
}
func (m *BuyInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyInput.Marshal(b, m, deterministic)
}
func (m *BuyInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyInput.Merge(m, src)
}
func (m *BuyInput) XXX_Size() int {
	return xxx_messageInfo_BuyInput.Size(m)
}
func (m *BuyInput) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyInput.DiscardUnknown(m)
}

var xxx_messageInfo_BuyInput proto.InternalMessageInfo

func (m *BuyInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *BuyInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BuyInput) GetPayLimit() int64 {
	if m != nil {
		return m.PayLimit
	}
	return 0
}

type SellInput struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64    `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReceiveLimit         int64    `protobuf:"zigzag64,3,opt,name=receive_limit,json=receiveLimit,proto3" json:"receive_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellInput) Reset()         { *m = SellInput{} }
func (m *SellInput) String() string { return proto.CompactTextString(m) }
func (*SellInput) ProtoMessage()    {}
func (*SellInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_adbbaf6824dfdbb6, []int{4}
}

func (m *SellInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInput.Unmarshal(m, b)
}
func (m *SellInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInput.Marshal(b, m, deterministic)
}
func (m *SellInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInput.Merge(m, src)
}
func (m *SellInput) XXX_Size() int {
	return xxx_messageInfo_SellInput.Size(m)
}
func (m *SellInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInput.DiscardUnknown(m)
}

var xxx_messageInfo_SellInput proto.InternalMessageInfo

func (m *SellInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SellInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SellInput) GetReceiveLimit() int64 {
	if m != nil {
		return m.ReceiveLimit
	}
	return 0
}

// Events
type TokenBought struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BoughtAmount         int64    `protobuf:"zigzag64,2,opt,name=bought_amount,json=boughtAmount,proto3" json:"bought_amount,omitempty"`
	BaseAmount           int64    `protobuf:"zigzag64,3,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	FeeAmount            int64    `protobuf:"zigzag64,4,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenBought) Reset()         { *m = TokenBought{} }
func (m *TokenBought) String() string { return proto.CompactTextString(m) }
func (*TokenBought) ProtoMessage()    {}
func (*TokenBought) Descriptor() ([]byte, []int) {
	return fileDescriptor_adbbaf6824dfdbb6, []int{5}
}

func (m *TokenBought) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBought.Unmarshal(m, b)
}
func (m *TokenBought) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBought.Marshal(b, m, deterministic)
}
func (m *TokenBought) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBought.Merge(m, src)
}
func (m *TokenBought) XXX_Size() int {
	return xxx_messageInfo_TokenBought.Size(m)
}
func (m *TokenBought) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBought.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBought proto.InternalMessageInfo

func (m *TokenBought) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenBought) GetBoughtAmount() int64 {
	if m != nil {
		return m.BoughtAmount
	}
	return 0
}

func (m *TokenBought) GetBaseAmount() int64 {
	if m != nil {
		return m.BaseAmount
	}
	return 0
}

func (m *TokenBought) GetFeeAmount() int64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

type TokenSold struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SoldAmount           int64    `protobuf:"zigzag64,2,opt,name=sold_amount,json=soldAmount,proto3" json:"sold_amount,omitempty"`
	BaseAmount           int64    `protobuf:"zigzag64,3,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	FeeAmount            int64    `protobuf:"zigzag64,4,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenSold) Reset()         { *m = TokenSold{} }
func (m *TokenSold) String() string { return proto.CompactTextString(m) }
func (*TokenSold) ProtoMessage()    {}
func (*TokenSold) Descriptor() ([]byte, []int) {
	return fileDescriptor_adbbaf6824dfdbb6, []int{6}
}

func (m *TokenSold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenSold.Unmarshal(m, b)
}
func (m *TokenSold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenSold.Marshal(b, m, deterministic)
}
func (m *TokenSold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenSold.Merge(m, src)
}
func (m *TokenSold) XXX_Size() int {
	return xxx_messageInfo_TokenSold.Size(m)
}
func (m *TokenSold) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenSold.DiscardUnknown(m)
}

var xxx_messageInfo_TokenSold proto.InternalMessageInfo

func (m *TokenSold) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenSold) GetSoldAmount() int64 {
	if m != nil {
		return m.SoldAmount
	}
	return 0
}

func (m *TokenSold) GetBaseAmount() int64 {
	if m != nil {
		return m.BaseAmount
	}
	return 0
}

func (m *TokenSold) GetFeeAmount() int64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*Connector)(nil), "Connector")
	proto.RegisterType((*TokenSymbol)(nil), "TokenSymbol")
	proto.RegisterType((*InitializeInput)(nil), "InitializeInput")
	proto.RegisterType((*BuyInput)(nil), "BuyInput")
	proto.RegisterType((*SellInput)(nil), "SellInput")
	proto.RegisterType((*TokenBought)(nil), "TokenBought")
	proto.RegisterType((*TokenSold)(nil), "TokenSold")
}

func init() { proto.RegisterFile("token_converter_contract.proto", fileDescriptor_adbbaf6824dfdbb6) }

var fileDescriptor_adbbaf6824dfdbb6 = []byte{
	// 800 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6f, 0xe3, 0x54,
	0x10, 0xc6, 0xcd, 0x0f, 0xe2, 0x49, 0xda, 0x90, 0x47, 0x9b, 0x86, 0x94, 0xb6, 0x91, 0x2b, 0x44,
	0x54, 0x21, 0x47, 0x2a, 0x08, 0xf1, 0x4b, 0x40, 0x52, 0x42, 0x54, 0x09, 0x24, 0xe4, 0x54, 0xe5,
	0x68, 0x5e, 0x9c, 0x49, 0x6a, 0xe1, 0xf8, 0x59, 0xf6, 0x73, 0xab, 0xf0, 0x17, 0x94, 0x13, 0xe2,
	0xc4, 0x95, 0x33, 0x47, 0xae, 0xdc, 0x38, 0xef, 0x65, 0xff, 0x98, 0xdd, 0x95, 0xf6, 0xb4, 0xb2,
	0xdf, 0x73, 0x12, 0xa7, 0x49, 0x76, 0xbb, 0xda, 0x9b, 0xdf, 0xcc, 0x37, 0xdf, 0x8c, 0x67, 0xbe,
	0x19, 0x38, 0xe2, 0xec, 0x57, 0x74, 0x4d, 0x8b, 0xb9, 0x37, 0xe8, 0x73, 0xf4, 0xa3, 0x2f, 0xee,
	0x53, 0x8b, 0xeb, 0x9e, 0xcf, 0x38, 0xab, 0x97, 0x29, 0x3a, 0xa3, 0x96, 0xc5, 0x7c, 0x94, 0x06,
	0x12, 0x1b, 0x98, 0xc7, 0x6d, 0xe6, 0x06, 0xd2, 0x76, 0x34, 0x66, 0x6c, 0xec, 0x60, 0x2b, 0x7e,
	0x0d, 0xc2, 0x51, 0xeb, 0xd6, 0xa7, 0x9e, 0x87, 0x7e, 0xe2, 0x3f, 0x58, 0xf6, 0xe3, 0xc4, 0xe3,
	0x53, 0xe1, 0xd4, 0x1e, 0x2b, 0xa0, 0x9e, 0x33, 0xd7, 0x45, 0x8b, 0x33, 0x9f, 0x54, 0x21, 0x1f,
	0x4c, 0x27, 0x03, 0xe6, 0xd4, 0x94, 0x86, 0xd2, 0x54, 0x0d, 0xf9, 0x22, 0x1f, 0x42, 0xf9, 0xc6,
	0xf6, 0x79, 0x48, 0x1d, 0x73, 0x40, 0x1d, 0xea, 0x5a, 0x58, 0xdb, 0x6a, 0x28, 0x4d, 0x62, 0xec,
	0x48, 0x73, 0x47, 0x58, 0x23, 0x82, 0x5b, 0xb4, 0xc7, 0xd7, 0xbc, 0x96, 0x11, 0x04, 0xe2, 0x45,
	0xbe, 0x84, 0xba, 0x1d, 0x98, 0x4b, 0x1c, 0x26, 0xba, 0x74, 0xe0, 0xe0, 0xb0, 0x96, 0x6d, 0x28,
	0xcd, 0x82, 0xb1, 0x6f, 0x07, 0x57, 0x29, 0xb6, 0xae, 0x70, 0x13, 0x1d, 0xde, 0xb5, 0x03, 0xd3,
	0x0b, 0x7d, 0xeb, 0x9a, 0x06, 0xf3, 0xa8, 0x5c, 0x1c, 0x55, 0xb1, 0x83, 0x9f, 0xa4, 0x47, 0xe2,
	0xb5, 0x0f, 0xa0, 0x78, 0x19, 0xf5, 0xb5, 0x2f, 0x8a, 0x5f, 0xf3, 0x53, 0xda, 0xff, 0x5b, 0x50,
	0xbe, 0x70, 0x6d, 0x6e, 0x53, 0xc7, 0xfe, 0x0d, 0x2f, 0x5c, 0x2f, 0xe4, 0xe4, 0x14, 0x2a, 0x83,
	0x28, 0x87, 0x98, 0x4b, 0x2a, 0xac, 0x1c, 0x39, 0x16, 0x79, 0xdf, 0x83, 0xc2, 0x08, 0xd1, 0xf4,
	0x29, 0x17, 0xdd, 0x50, 0x8d, 0xb7, 0x47, 0x88, 0x06, 0xe5, 0x48, 0x4e, 0x01, 0xac, 0xa4, 0xa9,
	0x41, 0x2d, 0xd3, 0xc8, 0x34, 0x8b, 0x67, 0xa0, 0xcf, 0xfa, 0x6c, 0x2c, 0x78, 0xc9, 0x39, 0x54,
	0x67, 0x2a, 0x88, 0x67, 0x6f, 0xd2, 0xe1, 0xd0, 0xc7, 0x20, 0x88, 0xdb, 0x52, 0x3c, 0xdb, 0xd6,
	0xa3, 0x99, 0xeb, 0x6d, 0x61, 0x34, 0x76, 0x63, 0xf0, 0xb9, 0xc4, 0x4a, 0x2b, 0xf9, 0x06, 0x76,
	0xe3, 0x5a, 0xd0, 0x42, 0xfb, 0x06, 0xfd, 0x19, 0x45, 0x6e, 0x15, 0x05, 0x89, 0xca, 0x94, 0xc8,
	0x84, 0xe0, 0x53, 0x28, 0x4f, 0xa8, 0x4b, 0xc7, 0x0b, 0xb1, 0xf9, 0x55, 0xb1, 0x3b, 0x12, 0x25,
	0xdf, 0xda, 0xcf, 0x50, 0xe8, 0x84, 0x53, 0xd1, 0xbc, 0x75, 0xea, 0xa9, 0x42, 0x9e, 0x4e, 0x58,
	0xe8, 0x72, 0x29, 0x1a, 0xf9, 0x22, 0x07, 0xa0, 0x7a, 0x74, 0x6a, 0x3a, 0xf6, 0xc4, 0x16, 0x7a,
	0x21, 0x46, 0xc1, 0xa3, 0xd3, 0x1f, 0xa2, 0xb7, 0xf6, 0x0b, 0xa8, 0x7d, 0x74, 0x9c, 0xd7, 0x63,
	0x3e, 0x81, 0x6d, 0xd9, 0x8a, 0x14, 0x7b, 0x49, 0x1a, 0x45, 0x86, 0xbf, 0x14, 0xa9, 0x93, 0x0e,
	0x0b, 0x23, 0x8d, 0x1e, 0xa6, 0x93, 0x74, 0x72, 0x77, 0x7f, 0x3c, 0x51, 0x94, 0x59, 0xae, 0x13,
	0xd8, 0x1e, 0xc4, 0x40, 0x33, 0x95, 0xb2, 0x24, 0x8c, 0x6d, 0x91, 0xf8, 0x18, 0x8a, 0xb1, 0x7e,
	0x24, 0x44, 0xa4, 0x85, 0xc8, 0x24, 0x01, 0x87, 0x00, 0xd1, 0xa0, 0xa4, 0x3f, 0x1b, 0xfb, 0xd5,
	0x11, 0x4a, 0xf7, 0x17, 0xd9, 0xbf, 0xff, 0xab, 0x29, 0xda, 0x9f, 0x0a, 0xa8, 0x42, 0x69, 0xcc,
	0x19, 0xbe, 0xac, 0xae, 0x63, 0x28, 0x06, 0xcc, 0x19, 0xa6, 0xab, 0x82, 0xc8, 0xf4, 0x26, 0x6b,
	0x3a, 0x7b, 0x9e, 0x87, 0xea, 0xa5, 0x94, 0x9e, 0x38, 0x56, 0x89, 0x06, 0xc9, 0x67, 0x00, 0xf3,
	0x3d, 0x22, 0xef, 0xe8, 0x4b, 0x4b, 0x55, 0xaf, 0xea, 0xe2, 0x02, 0xe9, 0xc9, 0x05, 0xd2, 0xbb,
	0xd1, 0x05, 0xd2, 0xde, 0x22, 0x9f, 0x40, 0xa9, 0x8f, 0x7c, 0x7e, 0x7f, 0x16, 0x76, 0x64, 0x43,
	0xd4, 0x29, 0x64, 0x3a, 0xe1, 0x94, 0xa8, 0x7a, 0xa2, 0xbc, 0x0d, 0xd8, 0x8f, 0x20, 0x1b, 0xc9,
	0x88, 0x80, 0x3e, 0x53, 0xd3, 0x06, 0xf4, 0x77, 0x00, 0x7d, 0xe4, 0xdf, 0xcb, 0x2d, 0x7e, 0xff,
	0x1e, 0xae, 0xcf, 0x7d, 0xdb, 0x1d, 0x5f, 0x51, 0x27, 0xc4, 0x0d, 0x2c, 0xdf, 0xc2, 0x9e, 0x64,
	0x59, 0x5a, 0xb2, 0xf4, 0x2e, 0x6d, 0x60, 0xf8, 0x0a, 0x2a, 0x7d, 0xe4, 0x3f, 0xa6, 0x56, 0xed,
	0xd5, 0xa3, 0x7b, 0xb0, 0xdf, 0x43, 0x7e, 0xb9, 0xea, 0x4e, 0xac, 0x09, 0xaa, 0xa7, 0xb9, 0xb5,
	0xdc, 0xdd, 0xef, 0xcf, 0x14, 0x85, 0x74, 0x61, 0xaf, 0xb7, 0xf2, 0x47, 0x1e, 0x46, 0xd3, 0x86,
	0x4a, 0xef, 0xde, 0xdf, 0x3c, 0x8c, 0xa2, 0x05, 0xa5, 0xde, 0xa2, 0x50, 0x4a, 0xfa, 0xc2, 0x25,
	0xae, 0x2f, 0xc8, 0x26, 0x09, 0xb8, 0x00, 0xe8, 0xcd, 0x27, 0xb9, 0x2e, 0xd9, 0xc6, 0x09, 0xcf,
	0xcb, 0x27, 0x3d, 0xe4, 0x9d, 0xa5, 0xeb, 0xbf, 0x8e, 0x32, 0x55, 0x99, 0xa4, 0xa8, 0x7f, 0xfd,
	0xef, 0xa3, 0xa7, 0xca, 0xe7, 0xed, 0xae, 0x33, 0xd2, 0x93, 0x89, 0x04, 0x7a, 0x7a, 0x9b, 0xf4,
	0xd5, 0xcb, 0xd5, 0xe7, 0x94, 0x63, 0xa7, 0xf1, 0xcf, 0xd6, 0xe1, 0xc6, 0xe8, 0x41, 0x3e, 0x2e,
	0xe3, 0xe3, 0x17, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x9d, 0x8e, 0x9d, 0x52, 0x08, 0x00, 0x00,
}
