// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token_contract.proto

package token

import (
	aelf "aelf"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenInfo struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TokenName            string        `protobuf:"bytes,2,opt,name=tokenName,proto3" json:"tokenName,omitempty"`
	Supply               int64         `protobuf:"zigzag64,3,opt,name=supply,proto3" json:"supply,omitempty"`
	TotalSupply          int64         `protobuf:"zigzag64,4,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"`
	Decimals             int32         `protobuf:"zigzag32,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Issuer               *aelf.Address `protobuf:"bytes,6,opt,name=issuer,proto3" json:"issuer,omitempty"`
	IsBurnable           bool          `protobuf:"varint,7,opt,name=isBurnable,proto3" json:"isBurnable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{0}
}

func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (m *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(m, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenInfo) GetTokenName() string {
	if m != nil {
		return m.TokenName
	}
	return ""
}

func (m *TokenInfo) GetSupply() int64 {
	if m != nil {
		return m.Supply
	}
	return 0
}

func (m *TokenInfo) GetTotalSupply() int64 {
	if m != nil {
		return m.TotalSupply
	}
	return 0
}

func (m *TokenInfo) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *TokenInfo) GetIssuer() *aelf.Address {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *TokenInfo) GetIsBurnable() bool {
	if m != nil {
		return m.IsBurnable
	}
	return false
}

type CreateInput struct {
	Symbol               string          `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TokenName            string          `protobuf:"bytes,2,opt,name=tokenName,proto3" json:"tokenName,omitempty"`
	TotalSupply          int64           `protobuf:"zigzag64,3,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"`
	Decimals             int32           `protobuf:"zigzag32,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Issuer               *aelf.Address   `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	IsBurnable           bool            `protobuf:"varint,6,opt,name=isBurnable,proto3" json:"isBurnable,omitempty"`
	LockWhiteList        []*aelf.Address `protobuf:"bytes,7,rep,name=lockWhiteList,proto3" json:"lockWhiteList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateInput) Reset()         { *m = CreateInput{} }
func (m *CreateInput) String() string { return proto.CompactTextString(m) }
func (*CreateInput) ProtoMessage()    {}
func (*CreateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{1}
}

func (m *CreateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInput.Unmarshal(m, b)
}
func (m *CreateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInput.Marshal(b, m, deterministic)
}
func (m *CreateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInput.Merge(m, src)
}
func (m *CreateInput) XXX_Size() int {
	return xxx_messageInfo_CreateInput.Size(m)
}
func (m *CreateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInput proto.InternalMessageInfo

func (m *CreateInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CreateInput) GetTokenName() string {
	if m != nil {
		return m.TokenName
	}
	return ""
}

func (m *CreateInput) GetTotalSupply() int64 {
	if m != nil {
		return m.TotalSupply
	}
	return 0
}

func (m *CreateInput) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *CreateInput) GetIssuer() *aelf.Address {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *CreateInput) GetIsBurnable() bool {
	if m != nil {
		return m.IsBurnable
	}
	return false
}

func (m *CreateInput) GetLockWhiteList() []*aelf.Address {
	if m != nil {
		return m.LockWhiteList
	}
	return nil
}

type CreateNativeTokenInput struct {
	Symbol                          string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TokenName                       string        `protobuf:"bytes,2,opt,name=tokenName,proto3" json:"tokenName,omitempty"`
	TotalSupply                     int64         `protobuf:"zigzag64,3,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"`
	Decimals                        int32         `protobuf:"zigzag32,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Issuer                          *aelf.Address `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	IsBurnable                      bool          `protobuf:"varint,6,opt,name=isBurnable,proto3" json:"isBurnable,omitempty"`
	LockWhiteSystemContractNameList []*aelf.Hash  `protobuf:"bytes,7,rep,name=lockWhiteSystemContractNameList,proto3" json:"lockWhiteSystemContractNameList,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}      `json:"-"`
	XXX_unrecognized                []byte        `json:"-"`
	XXX_sizecache                   int32         `json:"-"`
}

func (m *CreateNativeTokenInput) Reset()         { *m = CreateNativeTokenInput{} }
func (m *CreateNativeTokenInput) String() string { return proto.CompactTextString(m) }
func (*CreateNativeTokenInput) ProtoMessage()    {}
func (*CreateNativeTokenInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{2}
}

func (m *CreateNativeTokenInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNativeTokenInput.Unmarshal(m, b)
}
func (m *CreateNativeTokenInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNativeTokenInput.Marshal(b, m, deterministic)
}
func (m *CreateNativeTokenInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNativeTokenInput.Merge(m, src)
}
func (m *CreateNativeTokenInput) XXX_Size() int {
	return xxx_messageInfo_CreateNativeTokenInput.Size(m)
}
func (m *CreateNativeTokenInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNativeTokenInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNativeTokenInput proto.InternalMessageInfo

func (m *CreateNativeTokenInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CreateNativeTokenInput) GetTokenName() string {
	if m != nil {
		return m.TokenName
	}
	return ""
}

func (m *CreateNativeTokenInput) GetTotalSupply() int64 {
	if m != nil {
		return m.TotalSupply
	}
	return 0
}

func (m *CreateNativeTokenInput) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *CreateNativeTokenInput) GetIssuer() *aelf.Address {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *CreateNativeTokenInput) GetIsBurnable() bool {
	if m != nil {
		return m.IsBurnable
	}
	return false
}

func (m *CreateNativeTokenInput) GetLockWhiteSystemContractNameList() []*aelf.Hash {
	if m != nil {
		return m.LockWhiteSystemContractNameList
	}
	return nil
}

type IssueInput struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string        `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	To                   *aelf.Address `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IssueInput) Reset()         { *m = IssueInput{} }
func (m *IssueInput) String() string { return proto.CompactTextString(m) }
func (*IssueInput) ProtoMessage()    {}
func (*IssueInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{3}
}

func (m *IssueInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueInput.Unmarshal(m, b)
}
func (m *IssueInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueInput.Marshal(b, m, deterministic)
}
func (m *IssueInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueInput.Merge(m, src)
}
func (m *IssueInput) XXX_Size() int {
	return xxx_messageInfo_IssueInput.Size(m)
}
func (m *IssueInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueInput.DiscardUnknown(m)
}

var xxx_messageInfo_IssueInput proto.InternalMessageInfo

func (m *IssueInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *IssueInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *IssueInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *IssueInput) GetTo() *aelf.Address {
	if m != nil {
		return m.To
	}
	return nil
}

type IssueNativeTokenInput struct {
	Symbol               string     `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64      `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string     `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	ToSystemContractName *aelf.Hash `protobuf:"bytes,4,opt,name=toSystemContractName,proto3" json:"toSystemContractName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IssueNativeTokenInput) Reset()         { *m = IssueNativeTokenInput{} }
func (m *IssueNativeTokenInput) String() string { return proto.CompactTextString(m) }
func (*IssueNativeTokenInput) ProtoMessage()    {}
func (*IssueNativeTokenInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{4}
}

func (m *IssueNativeTokenInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueNativeTokenInput.Unmarshal(m, b)
}
func (m *IssueNativeTokenInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueNativeTokenInput.Marshal(b, m, deterministic)
}
func (m *IssueNativeTokenInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueNativeTokenInput.Merge(m, src)
}
func (m *IssueNativeTokenInput) XXX_Size() int {
	return xxx_messageInfo_IssueNativeTokenInput.Size(m)
}
func (m *IssueNativeTokenInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueNativeTokenInput.DiscardUnknown(m)
}

var xxx_messageInfo_IssueNativeTokenInput proto.InternalMessageInfo

func (m *IssueNativeTokenInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *IssueNativeTokenInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *IssueNativeTokenInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *IssueNativeTokenInput) GetToSystemContractName() *aelf.Hash {
	if m != nil {
		return m.ToSystemContractName
	}
	return nil
}

type TransferInput struct {
	To                   *aelf.Address `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Symbol               string        `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string        `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransferInput) Reset()         { *m = TransferInput{} }
func (m *TransferInput) String() string { return proto.CompactTextString(m) }
func (*TransferInput) ProtoMessage()    {}
func (*TransferInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{5}
}

func (m *TransferInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferInput.Unmarshal(m, b)
}
func (m *TransferInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferInput.Marshal(b, m, deterministic)
}
func (m *TransferInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferInput.Merge(m, src)
}
func (m *TransferInput) XXX_Size() int {
	return xxx_messageInfo_TransferInput.Size(m)
}
func (m *TransferInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferInput.DiscardUnknown(m)
}

var xxx_messageInfo_TransferInput proto.InternalMessageInfo

func (m *TransferInput) GetTo() *aelf.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransferInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TransferInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransferInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type LockInput struct {
	From                 *aelf.Address `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *aelf.Address `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	LockId               *aelf.Hash    `protobuf:"bytes,3,opt,name=lockId,proto3" json:"lockId,omitempty"`
	Symbol               string        `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Usage                string        `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Amount               int64         `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LockInput) Reset()         { *m = LockInput{} }
func (m *LockInput) String() string { return proto.CompactTextString(m) }
func (*LockInput) ProtoMessage()    {}
func (*LockInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{6}
}

func (m *LockInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockInput.Unmarshal(m, b)
}
func (m *LockInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockInput.Marshal(b, m, deterministic)
}
func (m *LockInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockInput.Merge(m, src)
}
func (m *LockInput) XXX_Size() int {
	return xxx_messageInfo_LockInput.Size(m)
}
func (m *LockInput) XXX_DiscardUnknown() {
	xxx_messageInfo_LockInput.DiscardUnknown(m)
}

var xxx_messageInfo_LockInput proto.InternalMessageInfo

func (m *LockInput) GetFrom() *aelf.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *LockInput) GetTo() *aelf.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *LockInput) GetLockId() *aelf.Hash {
	if m != nil {
		return m.LockId
	}
	return nil
}

func (m *LockInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *LockInput) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *LockInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UnlockInput struct {
	From                 *aelf.Address `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *aelf.Address `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	LockId               *aelf.Hash    `protobuf:"bytes,3,opt,name=lockId,proto3" json:"lockId,omitempty"`
	Symbol               string        `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Usage                string        `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Amount               int64         `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnlockInput) Reset()         { *m = UnlockInput{} }
func (m *UnlockInput) String() string { return proto.CompactTextString(m) }
func (*UnlockInput) ProtoMessage()    {}
func (*UnlockInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{7}
}

func (m *UnlockInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockInput.Unmarshal(m, b)
}
func (m *UnlockInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockInput.Marshal(b, m, deterministic)
}
func (m *UnlockInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockInput.Merge(m, src)
}
func (m *UnlockInput) XXX_Size() int {
	return xxx_messageInfo_UnlockInput.Size(m)
}
func (m *UnlockInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockInput.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockInput proto.InternalMessageInfo

func (m *UnlockInput) GetFrom() *aelf.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *UnlockInput) GetTo() *aelf.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *UnlockInput) GetLockId() *aelf.Hash {
	if m != nil {
		return m.LockId
	}
	return nil
}

func (m *UnlockInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *UnlockInput) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *UnlockInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransferFromInput struct {
	From                 *aelf.Address `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *aelf.Address `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Symbol               string        `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string        `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransferFromInput) Reset()         { *m = TransferFromInput{} }
func (m *TransferFromInput) String() string { return proto.CompactTextString(m) }
func (*TransferFromInput) ProtoMessage()    {}
func (*TransferFromInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{8}
}

func (m *TransferFromInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferFromInput.Unmarshal(m, b)
}
func (m *TransferFromInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferFromInput.Marshal(b, m, deterministic)
}
func (m *TransferFromInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferFromInput.Merge(m, src)
}
func (m *TransferFromInput) XXX_Size() int {
	return xxx_messageInfo_TransferFromInput.Size(m)
}
func (m *TransferFromInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferFromInput.DiscardUnknown(m)
}

var xxx_messageInfo_TransferFromInput proto.InternalMessageInfo

func (m *TransferFromInput) GetFrom() *aelf.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransferFromInput) GetTo() *aelf.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransferFromInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TransferFromInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransferFromInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type ApproveInput struct {
	Spender              *aelf.Address `protobuf:"bytes,1,opt,name=spender,proto3" json:"spender,omitempty"`
	Symbol               string        `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ApproveInput) Reset()         { *m = ApproveInput{} }
func (m *ApproveInput) String() string { return proto.CompactTextString(m) }
func (*ApproveInput) ProtoMessage()    {}
func (*ApproveInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{9}
}

func (m *ApproveInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveInput.Unmarshal(m, b)
}
func (m *ApproveInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveInput.Marshal(b, m, deterministic)
}
func (m *ApproveInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveInput.Merge(m, src)
}
func (m *ApproveInput) XXX_Size() int {
	return xxx_messageInfo_ApproveInput.Size(m)
}
func (m *ApproveInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveInput.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveInput proto.InternalMessageInfo

func (m *ApproveInput) GetSpender() *aelf.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

func (m *ApproveInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ApproveInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UnApproveInput struct {
	Spender              *aelf.Address `protobuf:"bytes,1,opt,name=spender,proto3" json:"spender,omitempty"`
	Symbol               string        `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnApproveInput) Reset()         { *m = UnApproveInput{} }
func (m *UnApproveInput) String() string { return proto.CompactTextString(m) }
func (*UnApproveInput) ProtoMessage()    {}
func (*UnApproveInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{10}
}

func (m *UnApproveInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnApproveInput.Unmarshal(m, b)
}
func (m *UnApproveInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnApproveInput.Marshal(b, m, deterministic)
}
func (m *UnApproveInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnApproveInput.Merge(m, src)
}
func (m *UnApproveInput) XXX_Size() int {
	return xxx_messageInfo_UnApproveInput.Size(m)
}
func (m *UnApproveInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnApproveInput.DiscardUnknown(m)
}

var xxx_messageInfo_UnApproveInput proto.InternalMessageInfo

func (m *UnApproveInput) GetSpender() *aelf.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

func (m *UnApproveInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *UnApproveInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BurnInput struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64    `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BurnInput) Reset()         { *m = BurnInput{} }
func (m *BurnInput) String() string { return proto.CompactTextString(m) }
func (*BurnInput) ProtoMessage()    {}
func (*BurnInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{11}
}

func (m *BurnInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurnInput.Unmarshal(m, b)
}
func (m *BurnInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurnInput.Marshal(b, m, deterministic)
}
func (m *BurnInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurnInput.Merge(m, src)
}
func (m *BurnInput) XXX_Size() int {
	return xxx_messageInfo_BurnInput.Size(m)
}
func (m *BurnInput) XXX_DiscardUnknown() {
	xxx_messageInfo_BurnInput.DiscardUnknown(m)
}

var xxx_messageInfo_BurnInput proto.InternalMessageInfo

func (m *BurnInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *BurnInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ChargeTransactionFeesInput struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64    `protobuf:"zigzag64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeTransactionFeesInput) Reset()         { *m = ChargeTransactionFeesInput{} }
func (m *ChargeTransactionFeesInput) String() string { return proto.CompactTextString(m) }
func (*ChargeTransactionFeesInput) ProtoMessage()    {}
func (*ChargeTransactionFeesInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{12}
}

func (m *ChargeTransactionFeesInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeTransactionFeesInput.Unmarshal(m, b)
}
func (m *ChargeTransactionFeesInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeTransactionFeesInput.Marshal(b, m, deterministic)
}
func (m *ChargeTransactionFeesInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeTransactionFeesInput.Merge(m, src)
}
func (m *ChargeTransactionFeesInput) XXX_Size() int {
	return xxx_messageInfo_ChargeTransactionFeesInput.Size(m)
}
func (m *ChargeTransactionFeesInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeTransactionFeesInput.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeTransactionFeesInput proto.InternalMessageInfo

func (m *ChargeTransactionFeesInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ChargeTransactionFeesInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ClaimTransactionFeesInput struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Height               int64    `protobuf:"zigzag64,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimTransactionFeesInput) Reset()         { *m = ClaimTransactionFeesInput{} }
func (m *ClaimTransactionFeesInput) String() string { return proto.CompactTextString(m) }
func (*ClaimTransactionFeesInput) ProtoMessage()    {}
func (*ClaimTransactionFeesInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{13}
}

func (m *ClaimTransactionFeesInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimTransactionFeesInput.Unmarshal(m, b)
}
func (m *ClaimTransactionFeesInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimTransactionFeesInput.Marshal(b, m, deterministic)
}
func (m *ClaimTransactionFeesInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimTransactionFeesInput.Merge(m, src)
}
func (m *ClaimTransactionFeesInput) XXX_Size() int {
	return xxx_messageInfo_ClaimTransactionFeesInput.Size(m)
}
func (m *ClaimTransactionFeesInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimTransactionFeesInput.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimTransactionFeesInput proto.InternalMessageInfo

func (m *ClaimTransactionFeesInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ClaimTransactionFeesInput) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetTokenInfoInput struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenInfoInput) Reset()         { *m = GetTokenInfoInput{} }
func (m *GetTokenInfoInput) String() string { return proto.CompactTextString(m) }
func (*GetTokenInfoInput) ProtoMessage()    {}
func (*GetTokenInfoInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{14}
}

func (m *GetTokenInfoInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenInfoInput.Unmarshal(m, b)
}
func (m *GetTokenInfoInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenInfoInput.Marshal(b, m, deterministic)
}
func (m *GetTokenInfoInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenInfoInput.Merge(m, src)
}
func (m *GetTokenInfoInput) XXX_Size() int {
	return xxx_messageInfo_GetTokenInfoInput.Size(m)
}
func (m *GetTokenInfoInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenInfoInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenInfoInput proto.InternalMessageInfo

func (m *GetTokenInfoInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type GetBalanceInput struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Owner                *aelf.Address `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetBalanceInput) Reset()         { *m = GetBalanceInput{} }
func (m *GetBalanceInput) String() string { return proto.CompactTextString(m) }
func (*GetBalanceInput) ProtoMessage()    {}
func (*GetBalanceInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{15}
}

func (m *GetBalanceInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceInput.Unmarshal(m, b)
}
func (m *GetBalanceInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceInput.Marshal(b, m, deterministic)
}
func (m *GetBalanceInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceInput.Merge(m, src)
}
func (m *GetBalanceInput) XXX_Size() int {
	return xxx_messageInfo_GetBalanceInput.Size(m)
}
func (m *GetBalanceInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceInput proto.InternalMessageInfo

func (m *GetBalanceInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetBalanceInput) GetOwner() *aelf.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

type GetBalanceOutput struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Owner                *aelf.Address `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance              int64         `protobuf:"zigzag64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetBalanceOutput) Reset()         { *m = GetBalanceOutput{} }
func (m *GetBalanceOutput) String() string { return proto.CompactTextString(m) }
func (*GetBalanceOutput) ProtoMessage()    {}
func (*GetBalanceOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{16}
}

func (m *GetBalanceOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceOutput.Unmarshal(m, b)
}
func (m *GetBalanceOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceOutput.Marshal(b, m, deterministic)
}
func (m *GetBalanceOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceOutput.Merge(m, src)
}
func (m *GetBalanceOutput) XXX_Size() int {
	return xxx_messageInfo_GetBalanceOutput.Size(m)
}
func (m *GetBalanceOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceOutput proto.InternalMessageInfo

func (m *GetBalanceOutput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetBalanceOutput) GetOwner() *aelf.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *GetBalanceOutput) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type GetAllowanceInput struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Owner                *aelf.Address `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender              *aelf.Address `protobuf:"bytes,3,opt,name=spender,proto3" json:"spender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAllowanceInput) Reset()         { *m = GetAllowanceInput{} }
func (m *GetAllowanceInput) String() string { return proto.CompactTextString(m) }
func (*GetAllowanceInput) ProtoMessage()    {}
func (*GetAllowanceInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{17}
}

func (m *GetAllowanceInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllowanceInput.Unmarshal(m, b)
}
func (m *GetAllowanceInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllowanceInput.Marshal(b, m, deterministic)
}
func (m *GetAllowanceInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllowanceInput.Merge(m, src)
}
func (m *GetAllowanceInput) XXX_Size() int {
	return xxx_messageInfo_GetAllowanceInput.Size(m)
}
func (m *GetAllowanceInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllowanceInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllowanceInput proto.InternalMessageInfo

func (m *GetAllowanceInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetAllowanceInput) GetOwner() *aelf.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *GetAllowanceInput) GetSpender() *aelf.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

type GetAllowanceOutput struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Owner                *aelf.Address `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender              *aelf.Address `protobuf:"bytes,3,opt,name=spender,proto3" json:"spender,omitempty"`
	Allowance            int64         `protobuf:"zigzag64,4,opt,name=allowance,proto3" json:"allowance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAllowanceOutput) Reset()         { *m = GetAllowanceOutput{} }
func (m *GetAllowanceOutput) String() string { return proto.CompactTextString(m) }
func (*GetAllowanceOutput) ProtoMessage()    {}
func (*GetAllowanceOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{18}
}

func (m *GetAllowanceOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllowanceOutput.Unmarshal(m, b)
}
func (m *GetAllowanceOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllowanceOutput.Marshal(b, m, deterministic)
}
func (m *GetAllowanceOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllowanceOutput.Merge(m, src)
}
func (m *GetAllowanceOutput) XXX_Size() int {
	return xxx_messageInfo_GetAllowanceOutput.Size(m)
}
func (m *GetAllowanceOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllowanceOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllowanceOutput proto.InternalMessageInfo

func (m *GetAllowanceOutput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetAllowanceOutput) GetOwner() *aelf.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *GetAllowanceOutput) GetSpender() *aelf.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

func (m *GetAllowanceOutput) GetAllowance() int64 {
	if m != nil {
		return m.Allowance
	}
	return 0
}

type CrossChainTransferInput struct {
	To                   *aelf.Address `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	TokenInfo            *TokenInfo    `protobuf:"bytes,2,opt,name=tokenInfo,proto3" json:"tokenInfo,omitempty"`
	Amount               int64         `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string        `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	ToChainId            int32         `protobuf:"varint,5,opt,name=toChainId,proto3" json:"toChainId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CrossChainTransferInput) Reset()         { *m = CrossChainTransferInput{} }
func (m *CrossChainTransferInput) String() string { return proto.CompactTextString(m) }
func (*CrossChainTransferInput) ProtoMessage()    {}
func (*CrossChainTransferInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{19}
}

func (m *CrossChainTransferInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossChainTransferInput.Unmarshal(m, b)
}
func (m *CrossChainTransferInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossChainTransferInput.Marshal(b, m, deterministic)
}
func (m *CrossChainTransferInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossChainTransferInput.Merge(m, src)
}
func (m *CrossChainTransferInput) XXX_Size() int {
	return xxx_messageInfo_CrossChainTransferInput.Size(m)
}
func (m *CrossChainTransferInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossChainTransferInput.DiscardUnknown(m)
}

var xxx_messageInfo_CrossChainTransferInput proto.InternalMessageInfo

func (m *CrossChainTransferInput) GetTo() *aelf.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CrossChainTransferInput) GetTokenInfo() *TokenInfo {
	if m != nil {
		return m.TokenInfo
	}
	return nil
}

func (m *CrossChainTransferInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CrossChainTransferInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *CrossChainTransferInput) GetToChainId() int32 {
	if m != nil {
		return m.ToChainId
	}
	return 0
}

type CrossChainReceiveTokenInput struct {
	FromChainId              int32        `protobuf:"varint,1,opt,name=fromChainId,proto3" json:"fromChainId,omitempty"`
	ParentChainHeight        int64        `protobuf:"varint,2,opt,name=parentChainHeight,proto3" json:"parentChainHeight,omitempty"`
	TransferTransactionBytes []byte       `protobuf:"bytes,3,opt,name=transferTransactionBytes,proto3" json:"transferTransactionBytes,omitempty"`
	MerklePath               []*aelf.Hash `protobuf:"bytes,4,rep,name=merklePath,proto3" json:"merklePath,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}     `json:"-"`
	XXX_unrecognized         []byte       `json:"-"`
	XXX_sizecache            int32        `json:"-"`
}

func (m *CrossChainReceiveTokenInput) Reset()         { *m = CrossChainReceiveTokenInput{} }
func (m *CrossChainReceiveTokenInput) String() string { return proto.CompactTextString(m) }
func (*CrossChainReceiveTokenInput) ProtoMessage()    {}
func (*CrossChainReceiveTokenInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{20}
}

func (m *CrossChainReceiveTokenInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossChainReceiveTokenInput.Unmarshal(m, b)
}
func (m *CrossChainReceiveTokenInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossChainReceiveTokenInput.Marshal(b, m, deterministic)
}
func (m *CrossChainReceiveTokenInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossChainReceiveTokenInput.Merge(m, src)
}
func (m *CrossChainReceiveTokenInput) XXX_Size() int {
	return xxx_messageInfo_CrossChainReceiveTokenInput.Size(m)
}
func (m *CrossChainReceiveTokenInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossChainReceiveTokenInput.DiscardUnknown(m)
}

var xxx_messageInfo_CrossChainReceiveTokenInput proto.InternalMessageInfo

func (m *CrossChainReceiveTokenInput) GetFromChainId() int32 {
	if m != nil {
		return m.FromChainId
	}
	return 0
}

func (m *CrossChainReceiveTokenInput) GetParentChainHeight() int64 {
	if m != nil {
		return m.ParentChainHeight
	}
	return 0
}

func (m *CrossChainReceiveTokenInput) GetTransferTransactionBytes() []byte {
	if m != nil {
		return m.TransferTransactionBytes
	}
	return nil
}

func (m *CrossChainReceiveTokenInput) GetMerklePath() []*aelf.Hash {
	if m != nil {
		return m.MerklePath
	}
	return nil
}

// EventsCreateInput
type Transferred struct {
	From                 *aelf.Address `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *aelf.Address `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Symbol               string        `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string        `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Transferred) Reset()         { *m = Transferred{} }
func (m *Transferred) String() string { return proto.CompactTextString(m) }
func (*Transferred) ProtoMessage()    {}
func (*Transferred) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{21}
}

func (m *Transferred) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transferred.Unmarshal(m, b)
}
func (m *Transferred) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transferred.Marshal(b, m, deterministic)
}
func (m *Transferred) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transferred.Merge(m, src)
}
func (m *Transferred) XXX_Size() int {
	return xxx_messageInfo_Transferred.Size(m)
}
func (m *Transferred) XXX_DiscardUnknown() {
	xxx_messageInfo_Transferred.DiscardUnknown(m)
}

var xxx_messageInfo_Transferred proto.InternalMessageInfo

func (m *Transferred) GetFrom() *aelf.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transferred) GetTo() *aelf.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transferred) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Transferred) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transferred) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type Approved struct {
	Owner                *aelf.Address `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender              *aelf.Address `protobuf:"bytes,2,opt,name=spender,proto3" json:"spender,omitempty"`
	Symbol               string        `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Approved) Reset()         { *m = Approved{} }
func (m *Approved) String() string { return proto.CompactTextString(m) }
func (*Approved) ProtoMessage()    {}
func (*Approved) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{22}
}

func (m *Approved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approved.Unmarshal(m, b)
}
func (m *Approved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approved.Marshal(b, m, deterministic)
}
func (m *Approved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approved.Merge(m, src)
}
func (m *Approved) XXX_Size() int {
	return xxx_messageInfo_Approved.Size(m)
}
func (m *Approved) XXX_DiscardUnknown() {
	xxx_messageInfo_Approved.DiscardUnknown(m)
}

var xxx_messageInfo_Approved proto.InternalMessageInfo

func (m *Approved) GetOwner() *aelf.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Approved) GetSpender() *aelf.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

func (m *Approved) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Approved) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UnApproved struct {
	Owner                *aelf.Address `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender              *aelf.Address `protobuf:"bytes,2,opt,name=spender,proto3" json:"spender,omitempty"`
	Symbol               string        `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnApproved) Reset()         { *m = UnApproved{} }
func (m *UnApproved) String() string { return proto.CompactTextString(m) }
func (*UnApproved) ProtoMessage()    {}
func (*UnApproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{23}
}

func (m *UnApproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnApproved.Unmarshal(m, b)
}
func (m *UnApproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnApproved.Marshal(b, m, deterministic)
}
func (m *UnApproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnApproved.Merge(m, src)
}
func (m *UnApproved) XXX_Size() int {
	return xxx_messageInfo_UnApproved.Size(m)
}
func (m *UnApproved) XXX_DiscardUnknown() {
	xxx_messageInfo_UnApproved.DiscardUnknown(m)
}

var xxx_messageInfo_UnApproved proto.InternalMessageInfo

func (m *UnApproved) GetOwner() *aelf.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *UnApproved) GetSpender() *aelf.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

func (m *UnApproved) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *UnApproved) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Burned struct {
	Burner               *aelf.Address `protobuf:"bytes,1,opt,name=burner,proto3" json:"burner,omitempty"`
	Symbol               string        `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64         `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Burned) Reset()         { *m = Burned{} }
func (m *Burned) String() string { return proto.CompactTextString(m) }
func (*Burned) ProtoMessage()    {}
func (*Burned) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{24}
}

func (m *Burned) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Burned.Unmarshal(m, b)
}
func (m *Burned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Burned.Marshal(b, m, deterministic)
}
func (m *Burned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Burned.Merge(m, src)
}
func (m *Burned) XXX_Size() int {
	return xxx_messageInfo_Burned.Size(m)
}
func (m *Burned) XXX_DiscardUnknown() {
	xxx_messageInfo_Burned.DiscardUnknown(m)
}

var xxx_messageInfo_Burned proto.InternalMessageInfo

func (m *Burned) GetBurner() *aelf.Address {
	if m != nil {
		return m.Burner
	}
	return nil
}

func (m *Burned) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Burned) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type IsInWhiteListInput struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Address              *aelf.Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IsInWhiteListInput) Reset()         { *m = IsInWhiteListInput{} }
func (m *IsInWhiteListInput) String() string { return proto.CompactTextString(m) }
func (*IsInWhiteListInput) ProtoMessage()    {}
func (*IsInWhiteListInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf91a63cc88e7ad, []int{25}
}

func (m *IsInWhiteListInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsInWhiteListInput.Unmarshal(m, b)
}
func (m *IsInWhiteListInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsInWhiteListInput.Marshal(b, m, deterministic)
}
func (m *IsInWhiteListInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsInWhiteListInput.Merge(m, src)
}
func (m *IsInWhiteListInput) XXX_Size() int {
	return xxx_messageInfo_IsInWhiteListInput.Size(m)
}
func (m *IsInWhiteListInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IsInWhiteListInput.DiscardUnknown(m)
}

var xxx_messageInfo_IsInWhiteListInput proto.InternalMessageInfo

func (m *IsInWhiteListInput) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *IsInWhiteListInput) GetAddress() *aelf.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenInfo)(nil), "token.TokenInfo")
	proto.RegisterType((*CreateInput)(nil), "token.CreateInput")
	proto.RegisterType((*CreateNativeTokenInput)(nil), "token.CreateNativeTokenInput")
	proto.RegisterType((*IssueInput)(nil), "token.IssueInput")
	proto.RegisterType((*IssueNativeTokenInput)(nil), "token.IssueNativeTokenInput")
	proto.RegisterType((*TransferInput)(nil), "token.TransferInput")
	proto.RegisterType((*LockInput)(nil), "token.LockInput")
	proto.RegisterType((*UnlockInput)(nil), "token.UnlockInput")
	proto.RegisterType((*TransferFromInput)(nil), "token.TransferFromInput")
	proto.RegisterType((*ApproveInput)(nil), "token.ApproveInput")
	proto.RegisterType((*UnApproveInput)(nil), "token.UnApproveInput")
	proto.RegisterType((*BurnInput)(nil), "token.BurnInput")
	proto.RegisterType((*ChargeTransactionFeesInput)(nil), "token.ChargeTransactionFeesInput")
	proto.RegisterType((*ClaimTransactionFeesInput)(nil), "token.ClaimTransactionFeesInput")
	proto.RegisterType((*GetTokenInfoInput)(nil), "token.GetTokenInfoInput")
	proto.RegisterType((*GetBalanceInput)(nil), "token.GetBalanceInput")
	proto.RegisterType((*GetBalanceOutput)(nil), "token.GetBalanceOutput")
	proto.RegisterType((*GetAllowanceInput)(nil), "token.GetAllowanceInput")
	proto.RegisterType((*GetAllowanceOutput)(nil), "token.GetAllowanceOutput")
	proto.RegisterType((*CrossChainTransferInput)(nil), "token.CrossChainTransferInput")
	proto.RegisterType((*CrossChainReceiveTokenInput)(nil), "token.CrossChainReceiveTokenInput")
	proto.RegisterType((*Transferred)(nil), "token.Transferred")
	proto.RegisterType((*Approved)(nil), "token.Approved")
	proto.RegisterType((*UnApproved)(nil), "token.UnApproved")
	proto.RegisterType((*Burned)(nil), "token.Burned")
	proto.RegisterType((*IsInWhiteListInput)(nil), "token.IsInWhiteListInput")
}

func init() { proto.RegisterFile("token_contract.proto", fileDescriptor_7bf91a63cc88e7ad) }

var fileDescriptor_7bf91a63cc88e7ad = []byte{
	// 1330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0x67, 0xf6, 0x5f, 0xb2, 0x2f, 0x09, 0xed, 0x0e, 0x69, 0xba, 0xdd, 0xfe, 0x61, 0x3b, 0x50,
	0x35, 0x2a, 0xc8, 0x95, 0x5a, 0x54, 0x41, 0x41, 0x48, 0xd9, 0xd0, 0x3f, 0x5b, 0xd2, 0x50, 0xb9,
	0x69, 0x39, 0xa2, 0xc9, 0xee, 0x24, 0x6b, 0xc5, 0xf6, 0x58, 0xf6, 0x6c, 0xab, 0x7c, 0x83, 0x72,
	0xe2, 0x0a, 0xe2, 0x82, 0x84, 0x38, 0xc0, 0x81, 0x03, 0x17, 0x84, 0xf8, 0x1c, 0x5c, 0x11, 0x5f,
	0x02, 0x71, 0x42, 0x42, 0x1e, 0x8f, 0xed, 0xd9, 0xb5, 0x77, 0xda, 0x0d, 0x11, 0xa2, 0x37, 0xcf,
	0x3c, 0xbf, 0xdf, 0xfb, 0xbd, 0x99, 0x37, 0x6f, 0x7e, 0x03, 0xab, 0x82, 0x1f, 0x30, 0xff, 0xb3,
	0x01, 0xf7, 0x45, 0x48, 0x07, 0xc2, 0x0a, 0x42, 0x2e, 0x38, 0xae, 0xcb, 0xd9, 0xce, 0x09, 0xca,
	0xdc, 0xbd, 0xab, 0x03, 0x1e, 0xb2, 0x64, 0xbe, 0x83, 0xe5, 0x04, 0x0f, 0x84, 0xc3, 0xfd, 0x48,
	0xcd, 0x9d, 0xdd, 0xe7, 0x7c, 0xdf, 0x65, 0x57, 0xe5, 0x68, 0x77, 0xbc, 0x77, 0x95, 0x79, 0x81,
	0x38, 0x54, 0xc6, 0x0b, 0xd3, 0xc6, 0xa7, 0x21, 0x0d, 0x02, 0x16, 0x2a, 0x67, 0xf2, 0x3b, 0x82,
	0xe6, 0x4e, 0x1c, 0xab, 0xef, 0xef, 0x71, 0xbc, 0x06, 0x8d, 0xe8, 0xd0, 0xdb, 0xe5, 0x6e, 0x1b,
	0x75, 0xd1, 0x7a, 0xd3, 0x56, 0x23, 0x7c, 0x0e, 0x9a, 0x92, 0xd0, 0x36, 0xf5, 0x58, 0xbb, 0x22,
	0x4d, 0xf9, 0x84, 0xf4, 0x1a, 0x07, 0x81, 0x7b, 0xd8, 0xae, 0x76, 0xd1, 0x3a, 0xb6, 0xd5, 0x08,
	0x77, 0x61, 0x49, 0x70, 0x41, 0xdd, 0x87, 0x89, 0xb1, 0x26, 0x8d, 0xfa, 0x14, 0xee, 0xc0, 0xe2,
	0x90, 0x0d, 0x1c, 0x8f, 0xba, 0x51, 0xbb, 0xde, 0x45, 0xeb, 0x2d, 0x3b, 0x1b, 0xe3, 0x4b, 0xd0,
	0x70, 0xa2, 0x68, 0xcc, 0xc2, 0x76, 0xa3, 0x8b, 0xd6, 0x97, 0xae, 0xad, 0x58, 0x71, 0xee, 0xd6,
	0xc6, 0x70, 0x18, 0xb2, 0x28, 0xb2, 0x95, 0x11, 0x5f, 0x00, 0x70, 0xa2, 0xde, 0x38, 0xf4, 0xe9,
	0xae, 0xcb, 0xda, 0x0b, 0x5d, 0xb4, 0xbe, 0x68, 0x6b, 0x33, 0xe4, 0x6f, 0x04, 0x4b, 0x9b, 0x21,
	0xa3, 0x82, 0xf5, 0xfd, 0x60, 0x2c, 0x8e, 0x98, 0xe2, 0x54, 0x2a, 0x55, 0x73, 0x2a, 0xb5, 0x99,
	0xa9, 0xd4, 0x5f, 0x3c, 0x95, 0xc6, 0x74, 0x2a, 0xf8, 0x3a, 0xac, 0xb8, 0x7c, 0x70, 0xf0, 0xe9,
	0xc8, 0x11, 0x6c, 0xcb, 0x89, 0x44, 0x7b, 0xa1, 0x5b, 0x2d, 0xa2, 0x4d, 0xfe, 0x43, 0xbe, 0xaf,
	0xc0, 0x5a, 0x92, 0xff, 0x36, 0x15, 0xce, 0x13, 0xa6, 0x36, 0xfb, 0x25, 0x5f, 0x8a, 0x1d, 0x78,
	0x3d, 0x4b, 0xf3, 0xe1, 0x61, 0x24, 0x98, 0xb7, 0xa9, 0x0e, 0x50, 0xcc, 0x51, 0x5b, 0x1c, 0x48,
	0xf0, 0xef, 0xd2, 0x68, 0x64, 0x3f, 0xcf, 0x85, 0x70, 0x80, 0x7e, 0x1c, 0xdf, 0xbc, 0x3c, 0x6b,
	0xd0, 0xa0, 0x1e, 0x1f, 0xfb, 0x42, 0xae, 0x0d, 0xb6, 0xd5, 0x08, 0x63, 0xa8, 0x79, 0xcc, 0xe3,
	0x72, 0x45, 0x9a, 0xb6, 0xfc, 0xc6, 0xe7, 0xa1, 0x22, 0xb8, 0x5c, 0x84, 0x42, 0xaa, 0x15, 0xc1,
	0xc9, 0xd7, 0x08, 0x4e, 0xc9, 0x88, 0x2f, 0xbc, 0x37, 0xf3, 0x04, 0xff, 0x30, 0x6e, 0x2e, 0xc5,
	0x54, 0x15, 0x1d, 0x7d, 0x65, 0x4a, 0xff, 0x23, 0x21, 0xac, 0xec, 0x84, 0xd4, 0x8f, 0xf6, 0x58,
	0x98, 0x90, 0x4a, 0xb2, 0x41, 0x33, 0xb2, 0xd1, 0x38, 0x57, 0x66, 0x70, 0xae, 0x96, 0x72, 0xae,
	0xe5, 0x9c, 0xc9, 0xcf, 0x08, 0x9a, 0x5b, 0x7c, 0x70, 0x90, 0x04, 0xbc, 0x08, 0xb5, 0xbd, 0x90,
	0x7b, 0xe5, 0x21, 0xa5, 0x49, 0x71, 0xaa, 0xcc, 0xe2, 0x44, 0xa0, 0x11, 0xef, 0x7a, 0x7f, 0x28,
	0x63, 0x4f, 0x66, 0xad, 0x2c, 0x1a, 0xef, 0xda, 0x04, 0xef, 0x55, 0xa8, 0x8f, 0x23, 0xba, 0xcf,
	0x64, 0xa9, 0x36, 0xed, 0x64, 0xa0, 0x65, 0x13, 0x97, 0x65, 0x35, 0xcd, 0x86, 0xfc, 0x82, 0x60,
	0xe9, 0x91, 0xef, 0xbe, 0x94, 0xdc, 0xbf, 0x42, 0xd0, 0x4a, 0xb7, 0xfa, 0x76, 0xc8, 0xbd, 0xe3,
	0xca, 0x20, 0x67, 0x57, 0x9d, 0x51, 0x11, 0xb5, 0xd2, 0x8a, 0xa8, 0x6b, 0x15, 0xb1, 0x0f, 0xcb,
	0x1b, 0x41, 0x10, 0xf2, 0x27, 0xea, 0x58, 0x5e, 0x86, 0x85, 0x28, 0x60, 0xfe, 0x90, 0x85, 0xe5,
	0xc4, 0x52, 0xeb, 0xbc, 0xe5, 0x48, 0x1c, 0x78, 0xf5, 0x91, 0xff, 0xdf, 0x84, 0x7a, 0x1f, 0x9a,
	0x71, 0x2b, 0x3b, 0xd2, 0x51, 0x27, 0x5b, 0xd0, 0xd9, 0x1c, 0xd1, 0x70, 0x9f, 0xc9, 0x1d, 0xa3,
	0x83, 0x58, 0x0b, 0xdc, 0x66, 0x2c, 0x3a, 0x1a, 0xda, 0xc7, 0x70, 0x66, 0xd3, 0xa5, 0x8e, 0x37,
	0x2f, 0xd8, 0x88, 0x39, 0xfb, 0xa3, 0x0c, 0x2c, 0x19, 0x91, 0xb7, 0xa0, 0x75, 0x87, 0x89, 0x4c,
	0x4f, 0x18, 0x41, 0xc8, 0x36, 0x9c, 0xb8, 0xc3, 0x44, 0x8f, 0xba, 0xd4, 0x1f, 0x3c, 0xa7, 0xe5,
	0xbe, 0x01, 0x75, 0xfe, 0xd4, 0x67, 0x61, 0x79, 0xa5, 0x25, 0x36, 0xe2, 0xc0, 0xc9, 0x1c, 0xef,
	0x93, 0xb1, 0xf8, 0xb7, 0x80, 0xb8, 0x0d, 0x0b, 0xbb, 0x09, 0x9a, 0xda, 0xbe, 0x74, 0x48, 0x0e,
	0x65, 0x9e, 0x1b, 0xae, 0xcb, 0x9f, 0x1e, 0x0f, 0x79, 0xbd, 0xd4, 0xaa, 0xa6, 0x52, 0x23, 0x5f,
	0x22, 0xc0, 0x7a, 0xec, 0xe3, 0x48, 0xf4, 0x45, 0x83, 0xc7, 0xca, 0x80, 0xa6, 0x81, 0xd5, 0xd1,
	0xcd, 0x27, 0xc8, 0x4f, 0x08, 0x4e, 0x6f, 0x86, 0x3c, 0x8a, 0x36, 0x47, 0xd4, 0xf1, 0xe7, 0xba,
	0x3a, 0x2c, 0x25, 0x39, 0xe2, 0xaa, 0x51, 0x54, 0x4f, 0x5a, 0x72, 0xc6, 0xca, 0xaa, 0xc9, 0xce,
	0x7f, 0x99, 0xe7, 0x4a, 0x49, 0xe4, 0x8c, 0xa4, 0xd4, 0x1f, 0xca, 0xce, 0x52, 0xb7, 0xf3, 0x09,
	0xf2, 0x1b, 0x82, 0xb3, 0x39, 0x69, 0x9b, 0x0d, 0xd8, 0xe4, 0x45, 0xdc, 0x85, 0xa5, 0xb8, 0xd3,
	0xa5, 0xfe, 0x48, 0xfa, 0xeb, 0x53, 0xf8, 0x6d, 0x68, 0x05, 0x34, 0x64, 0xbe, 0x90, 0x13, 0x77,
	0xf3, 0x73, 0x51, 0xb5, 0x8b, 0x06, 0x7c, 0x13, 0xda, 0x42, 0xad, 0x8c, 0x76, 0xe4, 0x7a, 0x87,
	0x82, 0x45, 0x32, 0x97, 0x65, 0x7b, 0xa6, 0x1d, 0x5f, 0x01, 0xf0, 0x58, 0x78, 0xe0, 0xb2, 0x07,
	0x54, 0x8c, 0xda, 0xb5, 0x82, 0xc0, 0xd1, 0xac, 0xe4, 0x47, 0x04, 0x4b, 0xe9, 0x16, 0x84, 0x6c,
	0x88, 0xd7, 0x0d, 0xcd, 0xbc, 0x57, 0x7f, 0xf6, 0xc5, 0x9f, 0x08, 0xa9, 0x9e, 0xfe, 0xe6, 0xcc,
	0x9e, 0x9e, 0xfe, 0x17, 0xef, 0xd8, 0xf9, 0xc9, 0xd6, 0x9e, 0x9a, 0x8e, 0xd0, 0xe1, 0x6f, 0xd6,
	0xbe, 0xf9, 0xb5, 0x8d, 0xc8, 0xb7, 0x08, 0x16, 0x55, 0xf7, 0x1d, 0xe2, 0x2b, 0x69, 0xd9, 0x9a,
	0xe8, 0xaa, 0xea, 0xb5, 0xf2, 0xea, 0x35, 0x91, 0xce, 0x8a, 0xf8, 0x68, 0xcc, 0x15, 0xcb, 0xef,
	0x10, 0x40, 0x76, 0x4b, 0xfc, 0x8f, 0x79, 0x46, 0xd0, 0x88, 0x6f, 0x18, 0x16, 0x97, 0x67, 0x63,
	0x37, 0xfe, 0x32, 0x73, 0x54, 0xff, 0x68, 0x41, 0x2b, 0xe6, 0xa0, 0xd5, 0x92, 0xa0, 0x8f, 0x00,
	0xf7, 0xa3, 0xbe, 0x9f, 0x3d, 0x3e, 0xcc, 0x7d, 0xf1, 0x32, 0x2c, 0xd0, 0x84, 0x44, 0x79, 0x73,
	0x4a, 0xad, 0xd7, 0xfe, 0x00, 0x58, 0x91, 0x27, 0x32, 0x55, 0xa7, 0xf8, 0x06, 0x34, 0x92, 0x37,
	0x0d, 0xc6, 0xaa, 0x4b, 0x68, 0x4f, 0xbc, 0xce, 0x9a, 0x95, 0x3c, 0x7a, 0xad, 0xf4, 0xd1, 0x6b,
	0xdd, 0x8a, 0x5f, 0xc4, 0xe4, 0x15, 0xbc, 0x05, 0xad, 0xc2, 0x5b, 0x08, 0x9f, 0x9f, 0x80, 0x98,
	0x56, 0xe2, 0x06, 0xb4, 0x77, 0xa0, 0x2e, 0xc5, 0x3b, 0x6e, 0x29, 0x84, 0xfc, 0xf1, 0x60, 0xf0,
	0xba, 0x07, 0x27, 0xa7, 0x25, 0x3f, 0x3e, 0xa7, 0x03, 0xcc, 0xc1, 0xe0, 0x26, 0x2c, 0xa6, 0x67,
	0x1c, 0xaf, 0xa6, 0xfd, 0x52, 0xef, 0xbb, 0x06, 0xdf, 0x1e, 0x2c, 0xeb, 0x92, 0x0f, 0xb7, 0xa7,
	0xfc, 0x33, 0x1d, 0x68, 0xc0, 0x78, 0x17, 0x16, 0xd4, 0x51, 0xc0, 0xaf, 0x29, 0x77, 0x5d, 0x40,
	0x19, 0x3c, 0x3f, 0x80, 0x66, 0x76, 0x8c, 0xf0, 0x29, 0xe5, 0x3b, 0x29, 0xbf, 0x0c, 0xde, 0xd7,
	0xa0, 0x16, 0x3f, 0x12, 0x70, 0x7a, 0x47, 0x64, 0x2f, 0x06, 0x83, 0xcf, 0x0d, 0x68, 0x24, 0xf2,
	0x3c, 0xab, 0x19, 0x4d, 0xad, 0x9b, 0x63, 0xc5, 0x27, 0x29, 0x8b, 0x95, 0x09, 0x37, 0x83, 0xcf,
	0x0e, 0x9c, 0x2a, 0x95, 0x68, 0xf8, 0x62, 0x5a, 0x6b, 0x33, 0x05, 0x9c, 0x01, 0xd5, 0x86, 0xd5,
	0x32, 0xa9, 0x86, 0xbb, 0x29, 0xe8, 0x2c, 0x1d, 0x67, 0xc0, 0xdc, 0x06, 0x5c, 0xbc, 0xb2, 0xf1,
	0x85, 0xec, 0x48, 0x94, 0xde, 0xe6, 0x06, 0xbc, 0xc7, 0xb0, 0x56, 0x7e, 0x9b, 0x62, 0x52, 0xc0,
	0x2c, 0x5c, 0xb6, 0x06, 0xdc, 0xf7, 0xa0, 0xf5, 0x90, 0x89, 0xdb, 0x8c, 0x3d, 0xe0, 0xdc, 0x55,
	0x1d, 0x02, 0x6b, 0x77, 0x9f, 0xc1, 0x75, 0x03, 0x96, 0x75, 0x51, 0x9a, 0x15, 0x7a, 0x41, 0xa9,
	0x76, 0x0a, 0x92, 0x83, 0xd4, 0x9f, 0x7d, 0xfe, 0x17, 0x42, 0xf8, 0x23, 0x80, 0x5c, 0x5a, 0xe2,
	0xb5, 0x1c, 0x40, 0x57, 0xaf, 0x9d, 0xd3, 0x85, 0xf9, 0x44, 0x9c, 0xa5, 0x28, 0xf7, 0x24, 0x91,
	0x4c, 0xb9, 0xe9, 0x44, 0x26, 0xa5, 0x64, 0xe7, 0x4c, 0x89, 0x65, 0x12, 0xeb, 0x3e, 0xac, 0x4c,
	0xb4, 0x5a, 0x7c, 0x26, 0x6b, 0x21, 0xd3, 0x0d, 0xb8, 0xd3, 0x29, 0x2c, 0x4d, 0x8f, 0x73, 0xf7,
	0x31, 0x75, 0xc7, 0x4c, 0xc1, 0xf5, 0x2e, 0xfd, 0x50, 0x21, 0x1b, 0xb7, 0xdc, 0x3d, 0x2b, 0x6d,
	0xb1, 0x91, 0x75, 0x7f, 0xec, 0x0a, 0x47, 0xae, 0x84, 0x75, 0x9f, 0x45, 0xf1, 0xf3, 0x31, 0xda,
	0x6d, 0x48, 0x84, 0xeb, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xae, 0xde, 0xda, 0x4b, 0xb5, 0x14,
	0x00, 0x00,
}
