// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vote_contract.proto

package vote

import (
	aelf "aelf"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Events
type Voted struct {
	VotingItemId         *aelf.Hash           `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Voter                *aelf.Address        `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	SnapshotNumber       int64                `protobuf:"zigzag64,3,opt,name=snapshot_number,json=snapshotNumber,proto3" json:"snapshot_number,omitempty"`
	Amount               int64                `protobuf:"zigzag64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	VoteTimestamp        *timestamp.Timestamp `protobuf:"bytes,5,opt,name=vote_timestamp,json=voteTimestamp,proto3" json:"vote_timestamp,omitempty"`
	Option               string               `protobuf:"bytes,6,opt,name=option,proto3" json:"option,omitempty"`
	VoteId               *aelf.Hash           `protobuf:"bytes,7,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Voted) Reset()         { *m = Voted{} }
func (m *Voted) String() string { return proto.CompactTextString(m) }
func (*Voted) ProtoMessage()    {}
func (*Voted) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{0}
}

func (m *Voted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voted.Unmarshal(m, b)
}
func (m *Voted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voted.Marshal(b, m, deterministic)
}
func (m *Voted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voted.Merge(m, src)
}
func (m *Voted) XXX_Size() int {
	return xxx_messageInfo_Voted.Size(m)
}
func (m *Voted) XXX_DiscardUnknown() {
	xxx_messageInfo_Voted.DiscardUnknown(m)
}

var xxx_messageInfo_Voted proto.InternalMessageInfo

func (m *Voted) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *Voted) GetVoter() *aelf.Address {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *Voted) GetSnapshotNumber() int64 {
	if m != nil {
		return m.SnapshotNumber
	}
	return 0
}

func (m *Voted) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Voted) GetVoteTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.VoteTimestamp
	}
	return nil
}

func (m *Voted) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *Voted) GetVoteId() *aelf.Hash {
	if m != nil {
		return m.VoteId
	}
	return nil
}

type Withdrawn struct {
	VoteId               *aelf.Hash `protobuf:"bytes,1,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Withdrawn) Reset()         { *m = Withdrawn{} }
func (m *Withdrawn) String() string { return proto.CompactTextString(m) }
func (*Withdrawn) ProtoMessage()    {}
func (*Withdrawn) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{1}
}

func (m *Withdrawn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Withdrawn.Unmarshal(m, b)
}
func (m *Withdrawn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Withdrawn.Marshal(b, m, deterministic)
}
func (m *Withdrawn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdrawn.Merge(m, src)
}
func (m *Withdrawn) XXX_Size() int {
	return xxx_messageInfo_Withdrawn.Size(m)
}
func (m *Withdrawn) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdrawn.DiscardUnknown(m)
}

var xxx_messageInfo_Withdrawn proto.InternalMessageInfo

func (m *Withdrawn) GetVoteId() *aelf.Hash {
	if m != nil {
		return m.VoteId
	}
	return nil
}

// Messages
type VotingRegisterInput struct {
	StartTimestamp       *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp         *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	AcceptedCurrency     string               `protobuf:"bytes,3,opt,name=accepted_currency,json=acceptedCurrency,proto3" json:"accepted_currency,omitempty"`
	IsLockToken          bool                 `protobuf:"varint,4,opt,name=is_lock_token,json=isLockToken,proto3" json:"is_lock_token,omitempty"`
	TotalSnapshotNumber  int64                `protobuf:"zigzag64,5,opt,name=total_snapshot_number,json=totalSnapshotNumber,proto3" json:"total_snapshot_number,omitempty"`
	Options              []string             `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VotingRegisterInput) Reset()         { *m = VotingRegisterInput{} }
func (m *VotingRegisterInput) String() string { return proto.CompactTextString(m) }
func (*VotingRegisterInput) ProtoMessage()    {}
func (*VotingRegisterInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{2}
}

func (m *VotingRegisterInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotingRegisterInput.Unmarshal(m, b)
}
func (m *VotingRegisterInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotingRegisterInput.Marshal(b, m, deterministic)
}
func (m *VotingRegisterInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotingRegisterInput.Merge(m, src)
}
func (m *VotingRegisterInput) XXX_Size() int {
	return xxx_messageInfo_VotingRegisterInput.Size(m)
}
func (m *VotingRegisterInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VotingRegisterInput.DiscardUnknown(m)
}

var xxx_messageInfo_VotingRegisterInput proto.InternalMessageInfo

func (m *VotingRegisterInput) GetStartTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.StartTimestamp
	}
	return nil
}

func (m *VotingRegisterInput) GetEndTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.EndTimestamp
	}
	return nil
}

func (m *VotingRegisterInput) GetAcceptedCurrency() string {
	if m != nil {
		return m.AcceptedCurrency
	}
	return ""
}

func (m *VotingRegisterInput) GetIsLockToken() bool {
	if m != nil {
		return m.IsLockToken
	}
	return false
}

func (m *VotingRegisterInput) GetTotalSnapshotNumber() int64 {
	if m != nil {
		return m.TotalSnapshotNumber
	}
	return 0
}

func (m *VotingRegisterInput) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type VotingItem struct {
	VotingItemId                  *aelf.Hash           `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	AcceptedCurrency              string               `protobuf:"bytes,2,opt,name=accepted_currency,json=acceptedCurrency,proto3" json:"accepted_currency,omitempty"`
	IsLockToken                   bool                 `protobuf:"varint,3,opt,name=is_lock_token,json=isLockToken,proto3" json:"is_lock_token,omitempty"`
	CurrentSnapshotNumber         int64                `protobuf:"zigzag64,4,opt,name=current_snapshot_number,json=currentSnapshotNumber,proto3" json:"current_snapshot_number,omitempty"`
	TotalSnapshotNumber           int64                `protobuf:"zigzag64,5,opt,name=total_snapshot_number,json=totalSnapshotNumber,proto3" json:"total_snapshot_number,omitempty"`
	Options                       []string             `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	RegisterTimestamp             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=register_timestamp,json=registerTimestamp,proto3" json:"register_timestamp,omitempty"`
	StartTimestamp                *timestamp.Timestamp `protobuf:"bytes,8,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp                  *timestamp.Timestamp `protobuf:"bytes,9,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	CurrentSnapshotStartTimestamp *timestamp.Timestamp `protobuf:"bytes,10,opt,name=current_snapshot_start_timestamp,json=currentSnapshotStartTimestamp,proto3" json:"current_snapshot_start_timestamp,omitempty"`
	Sponsor                       *aelf.Address        `protobuf:"bytes,11,opt,name=sponsor,proto3" json:"sponsor,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}             `json:"-"`
	XXX_unrecognized              []byte               `json:"-"`
	XXX_sizecache                 int32                `json:"-"`
}

func (m *VotingItem) Reset()         { *m = VotingItem{} }
func (m *VotingItem) String() string { return proto.CompactTextString(m) }
func (*VotingItem) ProtoMessage()    {}
func (*VotingItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{3}
}

func (m *VotingItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotingItem.Unmarshal(m, b)
}
func (m *VotingItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotingItem.Marshal(b, m, deterministic)
}
func (m *VotingItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotingItem.Merge(m, src)
}
func (m *VotingItem) XXX_Size() int {
	return xxx_messageInfo_VotingItem.Size(m)
}
func (m *VotingItem) XXX_DiscardUnknown() {
	xxx_messageInfo_VotingItem.DiscardUnknown(m)
}

var xxx_messageInfo_VotingItem proto.InternalMessageInfo

func (m *VotingItem) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *VotingItem) GetAcceptedCurrency() string {
	if m != nil {
		return m.AcceptedCurrency
	}
	return ""
}

func (m *VotingItem) GetIsLockToken() bool {
	if m != nil {
		return m.IsLockToken
	}
	return false
}

func (m *VotingItem) GetCurrentSnapshotNumber() int64 {
	if m != nil {
		return m.CurrentSnapshotNumber
	}
	return 0
}

func (m *VotingItem) GetTotalSnapshotNumber() int64 {
	if m != nil {
		return m.TotalSnapshotNumber
	}
	return 0
}

func (m *VotingItem) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *VotingItem) GetRegisterTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterTimestamp
	}
	return nil
}

func (m *VotingItem) GetStartTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.StartTimestamp
	}
	return nil
}

func (m *VotingItem) GetEndTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.EndTimestamp
	}
	return nil
}

func (m *VotingItem) GetCurrentSnapshotStartTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.CurrentSnapshotStartTimestamp
	}
	return nil
}

func (m *VotingItem) GetSponsor() *aelf.Address {
	if m != nil {
		return m.Sponsor
	}
	return nil
}

type VoteInput struct {
	VotingItemId         *aelf.Hash    `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Voter                *aelf.Address `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	Amount               int64         `protobuf:"zigzag64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Option               string        `protobuf:"bytes,4,opt,name=option,proto3" json:"option,omitempty"`
	VoteId               *aelf.Hash    `protobuf:"bytes,5,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VoteInput) Reset()         { *m = VoteInput{} }
func (m *VoteInput) String() string { return proto.CompactTextString(m) }
func (*VoteInput) ProtoMessage()    {}
func (*VoteInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{4}
}

func (m *VoteInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteInput.Unmarshal(m, b)
}
func (m *VoteInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteInput.Marshal(b, m, deterministic)
}
func (m *VoteInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteInput.Merge(m, src)
}
func (m *VoteInput) XXX_Size() int {
	return xxx_messageInfo_VoteInput.Size(m)
}
func (m *VoteInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteInput.DiscardUnknown(m)
}

var xxx_messageInfo_VoteInput proto.InternalMessageInfo

func (m *VoteInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *VoteInput) GetVoter() *aelf.Address {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *VoteInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *VoteInput) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *VoteInput) GetVoteId() *aelf.Hash {
	if m != nil {
		return m.VoteId
	}
	return nil
}

type WithdrawInput struct {
	VoteId               *aelf.Hash `protobuf:"bytes,1,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WithdrawInput) Reset()         { *m = WithdrawInput{} }
func (m *WithdrawInput) String() string { return proto.CompactTextString(m) }
func (*WithdrawInput) ProtoMessage()    {}
func (*WithdrawInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{5}
}

func (m *WithdrawInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawInput.Unmarshal(m, b)
}
func (m *WithdrawInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawInput.Marshal(b, m, deterministic)
}
func (m *WithdrawInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawInput.Merge(m, src)
}
func (m *WithdrawInput) XXX_Size() int {
	return xxx_messageInfo_WithdrawInput.Size(m)
}
func (m *WithdrawInput) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawInput.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawInput proto.InternalMessageInfo

func (m *WithdrawInput) GetVoteId() *aelf.Hash {
	if m != nil {
		return m.VoteId
	}
	return nil
}

type GetVotingResultInput struct {
	VotingItemId         *aelf.Hash `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	SnapshotNumber       int64      `protobuf:"zigzag64,2,opt,name=snapshot_number,json=snapshotNumber,proto3" json:"snapshot_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetVotingResultInput) Reset()         { *m = GetVotingResultInput{} }
func (m *GetVotingResultInput) String() string { return proto.CompactTextString(m) }
func (*GetVotingResultInput) ProtoMessage()    {}
func (*GetVotingResultInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{6}
}

func (m *GetVotingResultInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVotingResultInput.Unmarshal(m, b)
}
func (m *GetVotingResultInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVotingResultInput.Marshal(b, m, deterministic)
}
func (m *GetVotingResultInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVotingResultInput.Merge(m, src)
}
func (m *GetVotingResultInput) XXX_Size() int {
	return xxx_messageInfo_GetVotingResultInput.Size(m)
}
func (m *GetVotingResultInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVotingResultInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetVotingResultInput proto.InternalMessageInfo

func (m *GetVotingResultInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *GetVotingResultInput) GetSnapshotNumber() int64 {
	if m != nil {
		return m.SnapshotNumber
	}
	return 0
}

type VotingResult struct {
	VotingItemId           *aelf.Hash           `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Results                map[string]int64     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag64,2,opt,name=value,proto3"`
	SnapshotNumber         int64                `protobuf:"zigzag64,3,opt,name=snapshot_number,json=snapshotNumber,proto3" json:"snapshot_number,omitempty"`
	VotersCount            int64                `protobuf:"zigzag64,4,opt,name=voters_count,json=votersCount,proto3" json:"voters_count,omitempty"`
	SnapshotStartTimestamp *timestamp.Timestamp `protobuf:"bytes,5,opt,name=snapshot_start_timestamp,json=snapshotStartTimestamp,proto3" json:"snapshot_start_timestamp,omitempty"`
	SnapshotEndTimestamp   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=snapshot_end_timestamp,json=snapshotEndTimestamp,proto3" json:"snapshot_end_timestamp,omitempty"`
	VotesAmount            int64                `protobuf:"zigzag64,7,opt,name=votes_amount,json=votesAmount,proto3" json:"votes_amount,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *VotingResult) Reset()         { *m = VotingResult{} }
func (m *VotingResult) String() string { return proto.CompactTextString(m) }
func (*VotingResult) ProtoMessage()    {}
func (*VotingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{7}
}

func (m *VotingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotingResult.Unmarshal(m, b)
}
func (m *VotingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotingResult.Marshal(b, m, deterministic)
}
func (m *VotingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotingResult.Merge(m, src)
}
func (m *VotingResult) XXX_Size() int {
	return xxx_messageInfo_VotingResult.Size(m)
}
func (m *VotingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VotingResult.DiscardUnknown(m)
}

var xxx_messageInfo_VotingResult proto.InternalMessageInfo

func (m *VotingResult) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *VotingResult) GetResults() map[string]int64 {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *VotingResult) GetSnapshotNumber() int64 {
	if m != nil {
		return m.SnapshotNumber
	}
	return 0
}

func (m *VotingResult) GetVotersCount() int64 {
	if m != nil {
		return m.VotersCount
	}
	return 0
}

func (m *VotingResult) GetSnapshotStartTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.SnapshotStartTimestamp
	}
	return nil
}

func (m *VotingResult) GetSnapshotEndTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.SnapshotEndTimestamp
	}
	return nil
}

func (m *VotingResult) GetVotesAmount() int64 {
	if m != nil {
		return m.VotesAmount
	}
	return 0
}

type TakeSnapshotInput struct {
	VotingItemId         *aelf.Hash `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	SnapshotNumber       int64      `protobuf:"zigzag64,2,opt,name=snapshot_number,json=snapshotNumber,proto3" json:"snapshot_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TakeSnapshotInput) Reset()         { *m = TakeSnapshotInput{} }
func (m *TakeSnapshotInput) String() string { return proto.CompactTextString(m) }
func (*TakeSnapshotInput) ProtoMessage()    {}
func (*TakeSnapshotInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{8}
}

func (m *TakeSnapshotInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeSnapshotInput.Unmarshal(m, b)
}
func (m *TakeSnapshotInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeSnapshotInput.Marshal(b, m, deterministic)
}
func (m *TakeSnapshotInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeSnapshotInput.Merge(m, src)
}
func (m *TakeSnapshotInput) XXX_Size() int {
	return xxx_messageInfo_TakeSnapshotInput.Size(m)
}
func (m *TakeSnapshotInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeSnapshotInput.DiscardUnknown(m)
}

var xxx_messageInfo_TakeSnapshotInput proto.InternalMessageInfo

func (m *TakeSnapshotInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *TakeSnapshotInput) GetSnapshotNumber() int64 {
	if m != nil {
		return m.SnapshotNumber
	}
	return 0
}

type VotingRecord struct {
	VotingItemId         *aelf.Hash           `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Voter                *aelf.Address        `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	SnapshotNumber       int64                `protobuf:"zigzag64,3,opt,name=snapshot_number,json=snapshotNumber,proto3" json:"snapshot_number,omitempty"`
	Amount               int64                `protobuf:"zigzag64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	WithdrawTimestamp    *timestamp.Timestamp `protobuf:"bytes,5,opt,name=withdraw_timestamp,json=withdrawTimestamp,proto3" json:"withdraw_timestamp,omitempty"`
	VoteTimestamp        *timestamp.Timestamp `protobuf:"bytes,6,opt,name=vote_timestamp,json=voteTimestamp,proto3" json:"vote_timestamp,omitempty"`
	IsWithdrawn          bool                 `protobuf:"varint,7,opt,name=is_withdrawn,json=isWithdrawn,proto3" json:"is_withdrawn,omitempty"`
	Option               string               `protobuf:"bytes,8,opt,name=option,proto3" json:"option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VotingRecord) Reset()         { *m = VotingRecord{} }
func (m *VotingRecord) String() string { return proto.CompactTextString(m) }
func (*VotingRecord) ProtoMessage()    {}
func (*VotingRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{9}
}

func (m *VotingRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotingRecord.Unmarshal(m, b)
}
func (m *VotingRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotingRecord.Marshal(b, m, deterministic)
}
func (m *VotingRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotingRecord.Merge(m, src)
}
func (m *VotingRecord) XXX_Size() int {
	return xxx_messageInfo_VotingRecord.Size(m)
}
func (m *VotingRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_VotingRecord.DiscardUnknown(m)
}

var xxx_messageInfo_VotingRecord proto.InternalMessageInfo

func (m *VotingRecord) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *VotingRecord) GetVoter() *aelf.Address {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *VotingRecord) GetSnapshotNumber() int64 {
	if m != nil {
		return m.SnapshotNumber
	}
	return 0
}

func (m *VotingRecord) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *VotingRecord) GetWithdrawTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.WithdrawTimestamp
	}
	return nil
}

func (m *VotingRecord) GetVoteTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.VoteTimestamp
	}
	return nil
}

func (m *VotingRecord) GetIsWithdrawn() bool {
	if m != nil {
		return m.IsWithdrawn
	}
	return false
}

func (m *VotingRecord) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

type AddOptionInput struct {
	VotingItemId         *aelf.Hash `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Option               string     `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddOptionInput) Reset()         { *m = AddOptionInput{} }
func (m *AddOptionInput) String() string { return proto.CompactTextString(m) }
func (*AddOptionInput) ProtoMessage()    {}
func (*AddOptionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{10}
}

func (m *AddOptionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOptionInput.Unmarshal(m, b)
}
func (m *AddOptionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOptionInput.Marshal(b, m, deterministic)
}
func (m *AddOptionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOptionInput.Merge(m, src)
}
func (m *AddOptionInput) XXX_Size() int {
	return xxx_messageInfo_AddOptionInput.Size(m)
}
func (m *AddOptionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOptionInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddOptionInput proto.InternalMessageInfo

func (m *AddOptionInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *AddOptionInput) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

type RemoveOptionInput struct {
	VotingItemId         *aelf.Hash `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Option               string     `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RemoveOptionInput) Reset()         { *m = RemoveOptionInput{} }
func (m *RemoveOptionInput) String() string { return proto.CompactTextString(m) }
func (*RemoveOptionInput) ProtoMessage()    {}
func (*RemoveOptionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{11}
}

func (m *RemoveOptionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOptionInput.Unmarshal(m, b)
}
func (m *RemoveOptionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOptionInput.Marshal(b, m, deterministic)
}
func (m *RemoveOptionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOptionInput.Merge(m, src)
}
func (m *RemoveOptionInput) XXX_Size() int {
	return xxx_messageInfo_RemoveOptionInput.Size(m)
}
func (m *RemoveOptionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOptionInput.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOptionInput proto.InternalMessageInfo

func (m *RemoveOptionInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *RemoveOptionInput) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

type AddOptionsInput struct {
	VotingItemId         *aelf.Hash `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Options              []string   `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddOptionsInput) Reset()         { *m = AddOptionsInput{} }
func (m *AddOptionsInput) String() string { return proto.CompactTextString(m) }
func (*AddOptionsInput) ProtoMessage()    {}
func (*AddOptionsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{12}
}

func (m *AddOptionsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOptionsInput.Unmarshal(m, b)
}
func (m *AddOptionsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOptionsInput.Marshal(b, m, deterministic)
}
func (m *AddOptionsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOptionsInput.Merge(m, src)
}
func (m *AddOptionsInput) XXX_Size() int {
	return xxx_messageInfo_AddOptionsInput.Size(m)
}
func (m *AddOptionsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOptionsInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddOptionsInput proto.InternalMessageInfo

func (m *AddOptionsInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *AddOptionsInput) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type RemoveOptionsInput struct {
	VotingItemId         *aelf.Hash `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	Options              []string   `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RemoveOptionsInput) Reset()         { *m = RemoveOptionsInput{} }
func (m *RemoveOptionsInput) String() string { return proto.CompactTextString(m) }
func (*RemoveOptionsInput) ProtoMessage()    {}
func (*RemoveOptionsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{13}
}

func (m *RemoveOptionsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOptionsInput.Unmarshal(m, b)
}
func (m *RemoveOptionsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOptionsInput.Marshal(b, m, deterministic)
}
func (m *RemoveOptionsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOptionsInput.Merge(m, src)
}
func (m *RemoveOptionsInput) XXX_Size() int {
	return xxx_messageInfo_RemoveOptionsInput.Size(m)
}
func (m *RemoveOptionsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOptionsInput.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOptionsInput proto.InternalMessageInfo

func (m *RemoveOptionsInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

func (m *RemoveOptionsInput) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type VotedItems struct {
	VotedItemVoteIds     map[string]*VotedIds `protobuf:"bytes,1,rep,name=voted_item_vote_ids,json=votedItemVoteIds,proto3" json:"voted_item_vote_ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VotedItems) Reset()         { *m = VotedItems{} }
func (m *VotedItems) String() string { return proto.CompactTextString(m) }
func (*VotedItems) ProtoMessage()    {}
func (*VotedItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{14}
}

func (m *VotedItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotedItems.Unmarshal(m, b)
}
func (m *VotedItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotedItems.Marshal(b, m, deterministic)
}
func (m *VotedItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotedItems.Merge(m, src)
}
func (m *VotedItems) XXX_Size() int {
	return xxx_messageInfo_VotedItems.Size(m)
}
func (m *VotedItems) XXX_DiscardUnknown() {
	xxx_messageInfo_VotedItems.DiscardUnknown(m)
}

var xxx_messageInfo_VotedItems proto.InternalMessageInfo

func (m *VotedItems) GetVotedItemVoteIds() map[string]*VotedIds {
	if m != nil {
		return m.VotedItemVoteIds
	}
	return nil
}

type VotedIds struct {
	ActiveVotes          []*aelf.Hash `protobuf:"bytes,1,rep,name=active_votes,json=activeVotes,proto3" json:"active_votes,omitempty"`
	WithdrawnVotes       []*aelf.Hash `protobuf:"bytes,2,rep,name=withdrawn_votes,json=withdrawnVotes,proto3" json:"withdrawn_votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VotedIds) Reset()         { *m = VotedIds{} }
func (m *VotedIds) String() string { return proto.CompactTextString(m) }
func (*VotedIds) ProtoMessage()    {}
func (*VotedIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{15}
}

func (m *VotedIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotedIds.Unmarshal(m, b)
}
func (m *VotedIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotedIds.Marshal(b, m, deterministic)
}
func (m *VotedIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotedIds.Merge(m, src)
}
func (m *VotedIds) XXX_Size() int {
	return xxx_messageInfo_VotedIds.Size(m)
}
func (m *VotedIds) XXX_DiscardUnknown() {
	xxx_messageInfo_VotedIds.DiscardUnknown(m)
}

var xxx_messageInfo_VotedIds proto.InternalMessageInfo

func (m *VotedIds) GetActiveVotes() []*aelf.Hash {
	if m != nil {
		return m.ActiveVotes
	}
	return nil
}

func (m *VotedIds) GetWithdrawnVotes() []*aelf.Hash {
	if m != nil {
		return m.WithdrawnVotes
	}
	return nil
}

type GetVotingIdsInput struct {
	Voter                *aelf.Address `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	VotingItemId         *aelf.Hash    `protobuf:"bytes,2,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetVotingIdsInput) Reset()         { *m = GetVotingIdsInput{} }
func (m *GetVotingIdsInput) String() string { return proto.CompactTextString(m) }
func (*GetVotingIdsInput) ProtoMessage()    {}
func (*GetVotingIdsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{16}
}

func (m *GetVotingIdsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVotingIdsInput.Unmarshal(m, b)
}
func (m *GetVotingIdsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVotingIdsInput.Marshal(b, m, deterministic)
}
func (m *GetVotingIdsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVotingIdsInput.Merge(m, src)
}
func (m *GetVotingIdsInput) XXX_Size() int {
	return xxx_messageInfo_GetVotingIdsInput.Size(m)
}
func (m *GetVotingIdsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVotingIdsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetVotingIdsInput proto.InternalMessageInfo

func (m *GetVotingIdsInput) GetVoter() *aelf.Address {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *GetVotingIdsInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

type GetVotingItemInput struct {
	VotingItemId         *aelf.Hash `protobuf:"bytes,1,opt,name=voting_item_id,json=votingItemId,proto3" json:"voting_item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetVotingItemInput) Reset()         { *m = GetVotingItemInput{} }
func (m *GetVotingItemInput) String() string { return proto.CompactTextString(m) }
func (*GetVotingItemInput) ProtoMessage()    {}
func (*GetVotingItemInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{17}
}

func (m *GetVotingItemInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVotingItemInput.Unmarshal(m, b)
}
func (m *GetVotingItemInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVotingItemInput.Marshal(b, m, deterministic)
}
func (m *GetVotingItemInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVotingItemInput.Merge(m, src)
}
func (m *GetVotingItemInput) XXX_Size() int {
	return xxx_messageInfo_GetVotingItemInput.Size(m)
}
func (m *GetVotingItemInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVotingItemInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetVotingItemInput proto.InternalMessageInfo

func (m *GetVotingItemInput) GetVotingItemId() *aelf.Hash {
	if m != nil {
		return m.VotingItemId
	}
	return nil
}

type GetVotingRecordsInput struct {
	Ids                  []*aelf.Hash `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetVotingRecordsInput) Reset()         { *m = GetVotingRecordsInput{} }
func (m *GetVotingRecordsInput) String() string { return proto.CompactTextString(m) }
func (*GetVotingRecordsInput) ProtoMessage()    {}
func (*GetVotingRecordsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{18}
}

func (m *GetVotingRecordsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVotingRecordsInput.Unmarshal(m, b)
}
func (m *GetVotingRecordsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVotingRecordsInput.Marshal(b, m, deterministic)
}
func (m *GetVotingRecordsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVotingRecordsInput.Merge(m, src)
}
func (m *GetVotingRecordsInput) XXX_Size() int {
	return xxx_messageInfo_GetVotingRecordsInput.Size(m)
}
func (m *GetVotingRecordsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVotingRecordsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetVotingRecordsInput proto.InternalMessageInfo

func (m *GetVotingRecordsInput) GetIds() []*aelf.Hash {
	if m != nil {
		return m.Ids
	}
	return nil
}

type VotingRecords struct {
	Records              []*VotingRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VotingRecords) Reset()         { *m = VotingRecords{} }
func (m *VotingRecords) String() string { return proto.CompactTextString(m) }
func (*VotingRecords) ProtoMessage()    {}
func (*VotingRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8ae2cae2dbbaf5, []int{19}
}

func (m *VotingRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VotingRecords.Unmarshal(m, b)
}
func (m *VotingRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VotingRecords.Marshal(b, m, deterministic)
}
func (m *VotingRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VotingRecords.Merge(m, src)
}
func (m *VotingRecords) XXX_Size() int {
	return xxx_messageInfo_VotingRecords.Size(m)
}
func (m *VotingRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_VotingRecords.DiscardUnknown(m)
}

var xxx_messageInfo_VotingRecords proto.InternalMessageInfo

func (m *VotingRecords) GetRecords() []*VotingRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Voted)(nil), "vote.Voted")
	proto.RegisterType((*Withdrawn)(nil), "vote.Withdrawn")
	proto.RegisterType((*VotingRegisterInput)(nil), "vote.VotingRegisterInput")
	proto.RegisterType((*VotingItem)(nil), "vote.VotingItem")
	proto.RegisterType((*VoteInput)(nil), "vote.VoteInput")
	proto.RegisterType((*WithdrawInput)(nil), "vote.WithdrawInput")
	proto.RegisterType((*GetVotingResultInput)(nil), "vote.GetVotingResultInput")
	proto.RegisterType((*VotingResult)(nil), "vote.VotingResult")
	proto.RegisterMapType((map[string]int64)(nil), "vote.VotingResult.ResultsEntry")
	proto.RegisterType((*TakeSnapshotInput)(nil), "vote.TakeSnapshotInput")
	proto.RegisterType((*VotingRecord)(nil), "vote.VotingRecord")
	proto.RegisterType((*AddOptionInput)(nil), "vote.AddOptionInput")
	proto.RegisterType((*RemoveOptionInput)(nil), "vote.RemoveOptionInput")
	proto.RegisterType((*AddOptionsInput)(nil), "vote.AddOptionsInput")
	proto.RegisterType((*RemoveOptionsInput)(nil), "vote.RemoveOptionsInput")
	proto.RegisterType((*VotedItems)(nil), "vote.VotedItems")
	proto.RegisterMapType((map[string]*VotedIds)(nil), "vote.VotedItems.VotedItemVoteIdsEntry")
	proto.RegisterType((*VotedIds)(nil), "vote.VotedIds")
	proto.RegisterType((*GetVotingIdsInput)(nil), "vote.GetVotingIdsInput")
	proto.RegisterType((*GetVotingItemInput)(nil), "vote.GetVotingItemInput")
	proto.RegisterType((*GetVotingRecordsInput)(nil), "vote.GetVotingRecordsInput")
	proto.RegisterType((*VotingRecords)(nil), "vote.VotingRecords")
}

func init() { proto.RegisterFile("vote_contract.proto", fileDescriptor_ae8ae2cae2dbbaf5) }

var fileDescriptor_ae8ae2cae2dbbaf5 = []byte{
	// 1291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0xff, 0xdb, 0xf9, 0x3e, 0xf9, 0x6a, 0x26, 0x6d, 0xd7, 0x7f, 0x2f, 0x68, 0xb3, 0x5e, 0x60,
	0x2b, 0x3e, 0x52, 0xe8, 0xc2, 0xb2, 0x5b, 0xb4, 0xac, 0xb2, 0x55, 0xd9, 0x8d, 0x58, 0x01, 0x72,
	0x4b, 0x91, 0x90, 0x90, 0x71, 0xed, 0x69, 0x6b, 0x9a, 0xd8, 0xc1, 0x33, 0xc9, 0xaa, 0x6f, 0x00,
	0x6f, 0xc1, 0x0d, 0x37, 0x5c, 0x72, 0x03, 0x82, 0x07, 0xe0, 0x06, 0xf1, 0x2a, 0xdc, 0x20, 0xb8,
	0x45, 0x1e, 0x7b, 0xe2, 0xb1, 0x9d, 0x26, 0x6d, 0xa0, 0x12, 0x57, 0xc9, 0x9c, 0x39, 0xe7, 0x37,
	0xe7, 0xcc, 0x39, 0xe7, 0x77, 0xc6, 0xd0, 0x9e, 0x78, 0x14, 0x1b, 0x96, 0xe7, 0x52, 0xdf, 0xb4,
	0x68, 0x77, 0xe4, 0x7b, 0xd4, 0x43, 0xf9, 0x40, 0xa8, 0x36, 0x4d, 0x3c, 0x38, 0xda, 0xb4, 0x3c,
	0x1f, 0x87, 0x62, 0x15, 0x31, 0x81, 0x37, 0xa2, 0x8e, 0xe7, 0x92, 0x48, 0x76, 0xfd, 0xd8, 0xf3,
	0x8e, 0x07, 0x78, 0x93, 0xad, 0x0e, 0xc7, 0x47, 0x9b, 0x78, 0x38, 0xa2, 0x67, 0xd1, 0xe6, 0x8d,
	0xf4, 0x26, 0x75, 0x86, 0x98, 0x50, 0x73, 0x38, 0x0a, 0x15, 0xb4, 0x6f, 0x65, 0x28, 0x1c, 0x78,
	0x14, 0xdb, 0xe8, 0x75, 0x68, 0x4c, 0x3c, 0xea, 0xb8, 0xc7, 0x86, 0x43, 0xf1, 0xd0, 0x70, 0x6c,
	0x45, 0xea, 0x48, 0x1b, 0xd5, 0x2d, 0xe8, 0x06, 0x87, 0x76, 0x9f, 0x98, 0xe4, 0x44, 0xaf, 0x85,
	0x1a, 0x7d, 0x8a, 0x87, 0x7d, 0x1b, 0xdd, 0x82, 0x42, 0xe0, 0xa6, 0xaf, 0xc8, 0x4c, 0xb1, 0x1e,
	0x2a, 0xf6, 0x6c, 0xdb, 0xc7, 0x84, 0xe8, 0xe1, 0x1e, 0xba, 0x0d, 0x4d, 0xe2, 0x9a, 0x23, 0x72,
	0xe2, 0x51, 0xc3, 0x1d, 0x0f, 0x0f, 0xb1, 0xaf, 0xe4, 0x3a, 0xd2, 0x06, 0xd2, 0x1b, 0x5c, 0xfc,
	0x01, 0x93, 0xa2, 0x75, 0x28, 0x9a, 0x43, 0x6f, 0xec, 0x52, 0x25, 0xcf, 0xf6, 0xa3, 0x15, 0xea,
	0x31, 0xbf, 0xb0, 0x31, 0xf5, 0x5c, 0x29, 0xb0, 0xe3, 0xd4, 0x6e, 0x18, 0x5b, 0x97, 0xc7, 0xd6,
	0xdd, 0xe7, 0x1a, 0x7a, 0x3d, 0xb0, 0x98, 0x2e, 0x03, 0xe8, 0xf0, 0xce, 0x94, 0x62, 0x47, 0xda,
	0xa8, 0xe8, 0xd1, 0x0a, 0xdd, 0x82, 0x12, 0x83, 0x76, 0x6c, 0xa5, 0x94, 0x89, 0xb5, 0x18, 0x6c,
	0xf5, 0xed, 0xed, 0xfc, 0x37, 0x3f, 0x2b, 0x92, 0x76, 0x17, 0x2a, 0x9f, 0x38, 0xf4, 0xc4, 0xf6,
	0xcd, 0x67, 0x09, 0x3b, 0x69, 0x81, 0xdd, 0x4f, 0x32, 0xb4, 0x0f, 0xd8, 0xa5, 0xe9, 0xf8, 0xd8,
	0x21, 0x14, 0xfb, 0x7d, 0x77, 0x34, 0xa6, 0x68, 0x07, 0x9a, 0x84, 0x9a, 0x3e, 0x15, 0xc2, 0x92,
	0x16, 0x86, 0xd5, 0x60, 0x26, 0x71, 0x5c, 0x0f, 0xa1, 0x8e, 0x5d, 0x5b, 0x80, 0x90, 0x17, 0x42,
	0xd4, 0xb0, 0x6b, 0xc7, 0x00, 0xaf, 0x40, 0xcb, 0xb4, 0x2c, 0x3c, 0xa2, 0xd8, 0x36, 0xac, 0xb1,
	0xef, 0x63, 0xd7, 0x3a, 0x63, 0xe9, 0xa9, 0xe8, 0x2b, 0x7c, 0x63, 0x27, 0x92, 0x23, 0x0d, 0xea,
	0x0e, 0x31, 0x06, 0x9e, 0x75, 0x6a, 0x50, 0xef, 0x14, 0xbb, 0x2c, 0x4f, 0x65, 0xbd, 0xea, 0x90,
	0xa7, 0x9e, 0x75, 0xba, 0x1f, 0x88, 0xd0, 0x16, 0xac, 0x51, 0x8f, 0x9a, 0x03, 0x23, 0x9d, 0xf3,
	0x02, 0xcb, 0x69, 0x9b, 0x6d, 0xee, 0x25, 0x13, 0xaf, 0x40, 0x29, 0xaa, 0x68, 0xa5, 0xd8, 0xc9,
	0x6d, 0x54, 0x74, 0xbe, 0xd4, 0xfe, 0xc8, 0x03, 0x1c, 0x4c, 0x2b, 0x6e, 0x89, 0x0a, 0x9d, 0x19,
	0x9f, 0x7c, 0xd1, 0xf8, 0x72, 0xd9, 0xf8, 0xee, 0xc2, 0xb5, 0x10, 0x87, 0x66, 0x22, 0x0c, 0xab,
	0x76, 0x2d, 0xda, 0x4e, 0xc5, 0xf8, 0xaf, 0xde, 0x0b, 0xea, 0x03, 0xf2, 0xa3, 0x6a, 0x12, 0x92,
	0x5f, 0x5a, 0x98, 0xfc, 0x16, 0xb7, 0x8a, 0x2b, 0x60, 0x46, 0x1d, 0x96, 0xff, 0x79, 0x1d, 0x56,
	0x2e, 0x59, 0x87, 0x16, 0x74, 0x32, 0xd7, 0x9a, 0x76, 0x0b, 0x16, 0x62, 0x3e, 0x9f, 0xba, 0xfb,
	0xbd, 0xa4, 0x97, 0xb7, 0xa1, 0x44, 0x46, 0x9e, 0x4b, 0x3c, 0x5f, 0xa9, 0xce, 0x22, 0x2c, 0xbe,
	0xab, 0xfd, 0x20, 0x41, 0x25, 0xe0, 0xc4, 0xb0, 0x53, 0xaf, 0x88, 0x17, 0x63, 0xba, 0xcb, 0x25,
	0xe8, 0x2e, 0xe6, 0xaa, 0xfc, 0x79, 0x5c, 0x55, 0x38, 0x8f, 0x73, 0xb4, 0x37, 0xa1, 0xce, 0x59,
	0x2a, 0x74, 0xfe, 0x22, 0x4c, 0xa5, 0x7d, 0x09, 0xab, 0x8f, 0x31, 0xe5, 0x2c, 0x45, 0xc6, 0x03,
	0xba, 0x6c, 0xe4, 0x33, 0xc8, 0x5e, 0x9e, 0x45, 0xf6, 0xda, 0x6f, 0x39, 0xa8, 0x89, 0x07, 0x2e,
	0x71, 0xd6, 0x7d, 0x28, 0xf9, 0xcc, 0x96, 0x28, 0x72, 0x27, 0xb7, 0x51, 0xdd, 0xba, 0xd1, 0x0d,
	0xe2, 0xe9, 0x8a, 0xb0, 0xdd, 0xf0, 0x87, 0xec, 0xba, 0xd4, 0x3f, 0xd3, 0xb9, 0xfe, 0xc5, 0x67,
	0xd2, 0x4d, 0xa8, 0xb1, 0x6c, 0x11, 0xc3, 0x12, 0x26, 0x53, 0x35, 0x94, 0xed, 0xb0, 0x7c, 0xed,
	0x83, 0x72, 0x6e, 0xc9, 0x2e, 0x1e, 0x54, 0xeb, 0x64, 0x76, 0xad, 0x7e, 0x04, 0xd3, 0x1d, 0x23,
	0xd9, 0x5a, 0xc5, 0x85, 0x98, 0xab, 0xdc, 0x72, 0x57, 0x6c, 0xb1, 0x28, 0x14, 0x62, 0x44, 0x55,
	0x57, 0x8a, 0x43, 0x21, 0x3d, 0x26, 0x52, 0xb7, 0xa1, 0x26, 0xde, 0x17, 0x5a, 0x81, 0xdc, 0x29,
	0x3e, 0x63, 0x89, 0xa8, 0xe8, 0xc1, 0x5f, 0xb4, 0x0a, 0x85, 0x89, 0x39, 0x18, 0xe3, 0x28, 0xab,
	0xe1, 0x62, 0x5b, 0xbe, 0x27, 0x69, 0x2e, 0xb4, 0xf6, 0xcd, 0x53, 0xcc, 0x5b, 0xef, 0xca, 0x0b,
	0xe8, 0x77, 0x39, 0x2e, 0x20, 0xcb, 0xf3, 0xff, 0xbb, 0xcf, 0x97, 0x3e, 0xa0, 0x67, 0x51, 0x4b,
	0x5e, 0xaa, 0x32, 0x5a, 0xdc, 0x2a, 0x4e, 0x61, 0xf6, 0x25, 0x54, 0xbc, 0xec, 0x4b, 0xe8, 0x26,
	0xd4, 0x1c, 0x62, 0x70, 0x68, 0x97, 0x55, 0x01, 0x1b, 0x71, 0xf1, 0xe3, 0x26, 0x26, 0xa0, 0xb2,
	0x48, 0x40, 0xda, 0xa7, 0xd0, 0xe8, 0xd9, 0xf6, 0x87, 0x6c, 0xb1, 0x6c, 0x7a, 0x63, 0x6c, 0x39,
	0x81, 0xfd, 0x19, 0xb4, 0x74, 0x3c, 0xf4, 0x26, 0xf8, 0xaa, 0xe0, 0x9b, 0x53, 0xd7, 0xc9, 0xb2,
	0xe0, 0xc2, 0x38, 0x96, 0x93, 0xcf, 0x94, 0xcf, 0x01, 0x89, 0xde, 0x5f, 0xc1, 0x09, 0x3f, 0x4a,
	0xec, 0x21, 0x84, 0xed, 0x40, 0x93, 0xa0, 0x8f, 0xc3, 0x8f, 0x06, 0x3b, 0x44, 0x8e, 0x08, 0x9e,
	0x28, 0x12, 0xa3, 0xc1, 0x97, 0xa6, 0x34, 0x18, 0xa9, 0xc7, 0x7f, 0xd9, 0x50, 0xb3, 0x23, 0x36,
	0x5c, 0x99, 0xa4, 0xc4, 0xea, 0x1e, 0xac, 0xcd, 0x54, 0x9d, 0x41, 0x04, 0x2f, 0x88, 0x44, 0x50,
	0xdd, 0x6a, 0x88, 0x67, 0xda, 0x24, 0x49, 0x0c, 0x65, 0x2e, 0x46, 0xaf, 0x41, 0xcd, 0xb4, 0xa8,
	0x33, 0xc1, 0xcc, 0x67, 0xee, 0xb0, 0x78, 0x21, 0xd5, 0x70, 0x3f, 0xb0, 0x20, 0xe8, 0x0e, 0x34,
	0xa7, 0x95, 0x1a, 0x59, 0xc8, 0x19, 0x8b, 0xc6, 0x54, 0x85, 0x19, 0x69, 0x5f, 0x40, 0x6b, 0x3a,
	0xcc, 0xfa, 0x36, 0xe1, 0x63, 0x30, 0x6a, 0x75, 0x69, 0x4e, 0xab, 0x67, 0x13, 0x26, 0xcf, 0x4f,
	0x98, 0xf6, 0x1e, 0xa0, 0xf8, 0xac, 0x40, 0xb4, 0x5c, 0xe2, 0xb5, 0xb7, 0x60, 0x4d, 0x18, 0xc0,
	0x01, 0x9d, 0x45, 0x7e, 0x3f, 0x07, 0xb9, 0x38, 0xb1, 0xa2, 0x7d, 0x20, 0xd6, 0x1e, 0x40, 0x3d,
	0x61, 0x83, 0x5e, 0x0d, 0x46, 0x22, 0xfb, 0x1b, 0x99, 0xa0, 0xe4, 0x48, 0x0c, 0xb6, 0x74, 0xae,
	0xb2, 0xf5, 0x4b, 0x99, 0x51, 0x28, 0xde, 0x89, 0x3e, 0x3d, 0xd1, 0x63, 0x68, 0xf7, 0x5d, 0x87,
	0x3a, 0xe6, 0x20, 0x21, 0x5e, 0xcf, 0xd0, 0xcb, 0x6e, 0xf0, 0x85, 0xa9, 0x9e, 0x23, 0xd7, 0xfe,
	0x87, 0x1e, 0x42, 0x99, 0x7f, 0xed, 0xa0, 0xff, 0x27, 0x5d, 0x10, 0xbe, 0x81, 0xe6, 0x00, 0xbc,
	0x01, 0xf9, 0xc0, 0x05, 0xd4, 0x8c, 0xeb, 0x6a, 0x91, 0xc9, 0x7d, 0x28, 0x73, 0x0e, 0x43, 0xed,
	0xd0, 0x2c, 0xf1, 0x14, 0x9a, 0x63, 0xda, 0x83, 0x9a, 0x38, 0xbb, 0xd0, 0xb5, 0xd0, 0x3c, 0x33,
	0xcf, 0xe6, 0x40, 0xbc, 0x03, 0x95, 0x29, 0xc3, 0xa0, 0xd5, 0xd0, 0x3e, 0xc9, 0x96, 0xf3, 0xcf,
	0x17, 0xf9, 0x83, 0x9f, 0x9f, 0x61, 0xc4, 0x39, 0x10, 0x0f, 0x00, 0x62, 0x86, 0x43, 0x6b, 0x29,
	0x07, 0xc8, 0x22, 0xf3, 0x1d, 0xa8, 0x27, 0x18, 0x0c, 0x29, 0x59, 0x17, 0x16, 0x82, 0x3c, 0x82,
	0x7a, 0xa2, 0x1b, 0x38, 0x48, 0xb6, 0x45, 0xd4, 0x15, 0xb1, 0x28, 0x02, 0xb1, 0x56, 0xf8, 0xea,
	0xeb, 0xbf, 0x24, 0x09, 0x3d, 0x81, 0x66, 0xea, 0x29, 0x8a, 0xd4, 0x14, 0x8a, 0xf0, 0x42, 0x55,
	0x51, 0xf6, 0xc9, 0xc7, 0x91, 0xde, 0x65, 0x3d, 0xf5, 0xd4, 0xa4, 0x98, 0x24, 0xf1, 0x84, 0x36,
	0x9a, 0x67, 0x7f, 0x2f, 0xe1, 0x09, 0x7b, 0x62, 0xcc, 0xb1, 0x0c, 0xf6, 0xb9, 0xe5, 0xfb, 0xb0,
	0x92, 0xee, 0x66, 0x74, 0x3d, 0x13, 0x44, 0xdc, 0xe5, 0x6a, 0x3b, 0x8b, 0x45, 0x38, 0xd8, 0xdb,
	0xfc, 0x52, 0x39, 0xf7, 0x27, 0xb9, 0x4b, 0xb8, 0xc9, 0x48, 0x21, 0x8e, 0xbf, 0x26, 0xf2, 0x20,
	0x2f, 0xaa, 0x0c, 0x37, 0xaa, 0x29, 0xee, 0x8e, 0xec, 0xd5, 0x97, 0xbf, 0xff, 0xf5, 0x4f, 0xe9,
	0xc5, 0xde, 0xee, 0xe0, 0xa8, 0xcb, 0x99, 0x20, 0x9c, 0x24, 0x5d, 0x91, 0x1c, 0xf6, 0xa8, 0x49,
	0xf1, 0xa3, 0xf5, 0xef, 0xe4, 0xf6, 0x0c, 0xcd, 0xc3, 0x22, 0xab, 0x91, 0x3b, 0x7f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x10, 0x81, 0x46, 0x99, 0xe3, 0x12, 0x00, 0x00,
}
